### ISSUE TITLE
possible to set maximum number of markings?

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes-Front-End#518] opened 2015-06-10 13:57 UTC
The maximum number of markings would be helpful to prevent errors. (Maybe minimum too but maximum would be a lot more helpful)

**Comment by ggdhines** [comment] 2015-06-10 13:58
related to #488

**Comment by vrooje** [comment] 2015-06-17 14:02
Agreed. One specific use: in the GZ Bar project I only want people to draw 2 lines.

**Comment by aliburchard** [comment] 2015-06-18 10:31
Yes please! There are lots of cases where I want just one or two marks per tool.

**Comment by aliburchard** [comment] 2016-01-04 11:06
This is in high demand from a number of project builders, and is now causing some serious issues with trying to interpret Whales as Individuals data (i.e. @ggdhines built in aggregation, as wonderful as it is, won't work because we can't force it to limit the number of clusters to 2), so we're having to customize the aggregation code for what is a very *very* common use case.

@brian-c -- any way we can bump this up the priority list? At @eatyourgreens or @itsravenous -- is this by any chance related/important to anything you're working on?

**Comment by ggdhines** [comment] 2016-01-04 11:57
Having a minimum number of markings might also be useful.

**Comment by tedcheese** [comment] 2016-01-04 16:12
Aggregations are critical to using this data but at present the aggregation results are returning too many points. For Whales as Individuals (https://www.zooniverse.org/projects/tedcheese/whales-as-individuals) it would be *ideal* if we could set an aggregation threshold for point clouds based on results from volunteer input with another tool, in this case, the number of boxes drawn.

Specifically, step 1 the user draws a box around each whale tail, then step 2 they mark tail tip points, and step 3 they mark tail center 'V' points. If there's one tail in the photo, there will be one box thus should be two tail tips and one center V. Therefore, the ideal would be that aggregation could force a maximum of (2 tip points)*(# of boxes) and (1 center V point)*(# of boxes) for each image. Because whale tails are sometimes only partially visible, there are times when there are less tips and center points visible, thus a maximum, but not an absolute number of point cloud aggregations.

**Comment by ggdhines** [comment] 2016-01-04 16:41
@tedcheese no matter how we do this, we aren't going to be able to enforce a maximum number of points for classifications already done. I don't want all that data going to waste. Would it be possible to say something like only take clusters which have markings from at least 50% of the users? If you have some good standard data - or some users you trust, we could look into that.

**Comment by tedcheese** [comment] 2016-01-04 18:30
@ggdhines thanks. The issue is not *which* clusters we use, it is how clusters are divided. When I look at the aggregated tail tip point data for workflow 84 I see multiple clusters that are within ~ 20 pixels of each other, such that in order to use the aggregated data I need to further aggregate points. So maybe some kind of user-set thresholding allowing us to adjust how sensitive clustering is?

**Comment by ggdhines** [comment] 2016-01-04 18:45
@tedcheese  - the way algorithm works (or at least should work) is that a cluster is only divided up into smaller clusters if the parent cluster contains multiple markings from the same user. I don't pay any attention to the distance between clusters - the algorithm has to work for multiple projects and there may be other projects where it is perfectly reasonable to have two clusters with in 20 pixels of each other. Can you send me some subject ids so I can confirm this is what is happening with your data? Won't solve the problem but would make me feel comfortable that the algorithm is doing what it should. 
I don't think we really have things set up so that you can specify certain parameters in the aggregation run. I'm sure that will happen but don't think its a priority. In the mean time, you might need to take a download of your raw classifications/markings and run something like DBscan over it (DBscan allows you to set exactly such a sensitivity threshold). I can probably help with that but not sure of when I'll have the time. Feel free to send the subject ids to greg@zooniverse.org

**Comment by brian-c** [comment] 2016-03-18 15:14
Closed by #2147

**Closed by brian-c** 2016-03-18 15:14 UTC
Labels: feature request, project builder
