### ISSUE TITLE
Unread/new  message count should be decremented once you click on the private message thread

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1035] opened 2015-07-11 00:44 UTC
If I get a new message currently the envelope icon gets filed in. If I click on it and go to my inbox and then to the message thread with the new message, the icon still stays dark. It's only if I navigate away from the mailbox does the icon change to the un-filled no new messages version.

A few times now I've been confused looking but at the filled mailicon and think there is another new message, but then I find out there is no other unread messages in my inbox.

I think it would be helpful like most apps if you click on the thread with the new message, that the website update the unread message count and reflect that in the state of the mailbox icon

**Comment by parrish** [comment] 2015-09-16 20:58
Yep.  It's a duplicate of #1540

**Closed by parrish** 2015-09-16 20:58 UTC
