### ISSUE TITLE
Bug in Survey Task Characteristics CSV Upload

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/Panoptes-Front-End#5646] opened 2020-03-11 19:20 UTC
## Expected behavior

When uploading characteristics CSV to survey task, values in newly uploaded file should overwrite existing values, even if characteristic-value pair (e.g., Color=Blue) already exist.

## Current behavior

As reported by [FISHstory](https://www.zooniverse.org/projects/safmcadmin/fishstory) project team by email during beta review: if a characteristics CSV is uploaded, then uploaded again with different Y/N values, the changes are not correctly adopted -- new Y characteristics are added, but changes from Y-to-N are not made.

## Steps to replicate

I was able to replicate this behavior using survey task on a test workflow (https://www.zooniverse.org/lab/8749/workflows/11387): see T0 and use the following characteristic CSV files to upload characteristics v1 ([link to CSV](https://www.dropbox.com/s/7tivh24q1v6gwmi/birdspecies_characteristics_1.csv?dl=0)), upload characteristics v2 ([link to CSV](https://www.dropbox.com/s/f75kmfm15l0jttk/birdspecies_characteristics_2.csv?dl=0)), and clear current choices ([link to CSV](https://www.dropbox.com/s/6vak0ezb7z4lu47/birdspecies_characteristics_clear.csv?dl=0)) to reset and try again.

## Additional information

I think the solution is to remove this conditional
https://github.com/zooniverse/Panoptes-Front-End/blob/106444641e596b5e491a34ae692341b86b75c486/app/classifier/tasks/survey/editor.cjsx#L448-L449
and always call the command in the second line.

I'm assigning @mcbouslog here as he was the one to last change the relevant code as part of https://github.com/zooniverse/Panoptes-Front-End/pull/2894.

**Comment by lcjohnso** [comment] 2020-04-05 16:24
Re-upping this Issue -- it just came up with the Snapshot team in a ticket regarding [Snapshot Karoo](https://www.zooniverse.org/projects/shuebner729/snapshot-karoo) that @shaunanoordin was helping out on.

**Comment by shaunanoordin** [comment] 2020-04-07 17:49
@lcjohnso Thanks for tagging me in, and sorry for the late reply! Right, I've taken a look at the specific conditional that you pointed out in `app/classifier/tasks/survey/editor.cjsx` and...

1. oh gods, it's CoffeeScript
2. I'm not sure if removing the conditional itself is the solution, i.e. ...
  ```
  if @state.task.choices[choiceID]?.characteristics[characteristicID].indexOf(valueID) is -1
    @state.task.choices[choiceID]?.characteristics[characteristicID].push valueID
  -->
  @state.task.choices[choiceID]?.characteristics[characteristicID].push valueID
  ```
  ...since that just seems to add values to array without _replacing_ anything, which I thought was the problem with Snapshot Karoo? i.e. `['Y'].add('N') --> ['Y', 'N'] instead of ['N']` That said, (a) I didn't spend as much time analysing this problem as you have, and (b) my ability to read CoffeeScript is crap anyway, so I might be talking about my butt about this.
3. I'll be happy to take on trying to implement the suggested fix, provided that I can set up my own test cases, in addition to your test CSVs. (Thoughts: I should test adding a new characteristics CSV to a fresh new survey workflow, as well test replacing an existing characteristics CSV on an old workflow.)
4. it's telling that the next line of code says `addConfusion()` 😐

**Comment by lcjohnso** [comment] 2020-04-08 16:19
Hi @shaunanoordin -- Thanks for taking a look and thinking through the solution I proposed.

I agree that my solution isn't the right one after your helpful evaluation.  Instead, is it possible that we're missing an `else` statement with an assignment command as part of this conditional?  One that would replace the existing characteristic value with the one in the new CSV that's being processed?  Basically, an assignment command to the new value?

Tagging @mcbouslog here to keep him in the loop, but acknowledging that because of parenting duties, he likely won't have time to dig in on this.  One path forward, perhaps Mark could give us some direction about how we might fix the implementation, and leave the coding / testing to Shaun?  But let me be clear: this is a "nice-to-have" fix where we have a usable workaround at the moment.  Keep this as a low-priority task -- no need to let it disrupt other work for either of you!

**Comment by mcbouslog** [comment] 2020-04-13 16:20
I think I have a fix for this, will push up later today, but I think the key question is if there'd ever be a scenario where a specific characteristic (i.e. "Size") would/could/should have multiple values (i.e. "Small" **_AND_** "Big"). I don't think so, I think we'd always want just one Size (i.e. Small), Color (Striped), Tail (Short), etc., but am still thinking through.

Also I plan to quickly test with the set of example CSVs before opening PR. So stay tuned, thanks for patience!

**Comment by mcbouslog** [comment] 2020-04-14 15:06
There are scenarios where a characteristic may have multiple values, i.e. an Aardvark's color filter may include "red" and "brown", as included in the survey task example CSVs. Nonetheless, I think I have an (updated) fix I'll open a PR with shortly.

**Comment by shaunanoordin** [comment] 2020-04-14 16:08
@mcbouslog I can confirm that certain characteristics _must_ have multiple values.

Below is an example of a CSV from Snapshot Karoo. Note, for example, that the Oryx has pattern = 'solid' and 'bands'

```
Name,Like=cat or dog; likeCatDog.png,Like=cow or horse; likeCowHorse.png,Like=antelope/deer; likeAntelopeDeer.png,Like=primate; likePrimate.png,Like=weasel; likeWeasel.png,Like=bird; likeBird.png,Like=other; likeOther.png,Pattern=solid; patternSolid.png,Pattern=stripes; patternStripe.png,Pattern=bands; patternBand.png,Pattern=spots; patternSpots.png,color=tan/yellow; coatTan.jpg,color=red; coatRed.jpg,color=brown; coatBrown.jpg,color=white; coatWhite.jpg,color=gray; coatGray.jpg,color=black; coatBlack.jpg,Horns=straight; hornsStraight.png,Horns=curved; hornsCurved.png,Horns=spiral; hornsSpiral.png,Horns=u-shaped; hornsUshaped.png,Tail=smooth; tailSmooth.png,Tail=bushy; tailBushy.png,Tail=tufted; tailTufted.png,Tail=long; tailLong.png,Tail=short; tailShort.png,Build=stocky; buildStocky.png,Build=lanky; buildLanky.png,Build=Large;buildLarge.png,Build=small; buildSmall.png,Build=low-slung; buildLowSlung.png
Aardvark/Antbear,N,N,N,N,Y,N,Y,Y,N,N,N,N,Y,Y,N,Y,N,N,N,N,N,Y,N,N,Y,N,Y,N,N,Y,Y
Aardwolf,Y,N,N,N,N,N,N,N,Y,N,N,Y,N,Y,N,Y,N,N,N,N,N,N,Y,N,N,N,N,Y,N,N,N
Baboon ,N,N,N,Y,N,N,Y,Y,N,N,N,Y,N,Y,N,Y,N,N,N,N,N,Y,N,N,Y,N,N,Y,N,Y,N
Bird (other),N,N,N,N,N,Y,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,N,N,N,Y,N,N,Y,Y,N,N,N,Y,N
Birds of prey,N,N,N,N,N,Y,N,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,N,N,N,Y,N,N,Y,Y,N,N,N,Y,N
Black-footed cat,Y,N,N,N,N,N,N,N,N,N,Y,Y,N,Y,N,N,N,N,N,N,N,Y,N,N,Y,N,Y,N,N,Y,Y
Bustard (Kori),N,N,N,N,N,Y,N,N,N,N,Y,N,N,Y,Y,Y,N,N,N,N,N,N,N,N,Y,N,N,Y,Y,N,N
Bustard (Ludwig's),N,N,N,N,N,Y,N,N,N,N,Y,N,N,Y,Y,Y,N,N,N,N,N,N,N,N,Y,N,N,Y,Y,N,N
Caracal,Y,N,N,N,N,N,N,Y,N,N,N,Y,Y,Y,Y,N,N,N,N,N,N,Y,N,N,Y,N,N,Y,Y,Y,N
Crane (Blue),N,N,N,N,N,Y,N,Y,N,N,N,N,N,N,N,Y,N,N,N,N,N,N,N,N,Y,N,N,Y,N,N,N
Domestic animal,N,Y,N,N,N,N,N,Y,N,N,Y,Y,Y,Y,Y,Y,Y,N,N,N,Y,N,N,Y,N,N,Y,N,Y,N,N
Duiker ,N,N,Y,N,N,N,N,Y,N,N,N,Y,Y,Y,N,Y,Y,Y,N,N,N,N,Y,N,N,Y,N,Y,N,Y,N
Eland ,N,Y,Y,N,N,N,N,Y,Y,N,N,Y,Y,Y,Y,Y,N,Y,N,Y,N,N,N,Y,Y,N,Y,N,Y,N,N
Fox (Bat-eared),Y,N,N,N,N,N,N,Y,N,N,N,N,Y,Y,N,Y,N,N,N,N,N,N,Y,N,N,N,N,N,N,Y,Y
Fox (Cape),Y,N,N,N,N,N,N,Y,N,N,N,N,Y,Y,N,Y,N,N,N,N,N,N,Y,N,N,N,N,N,N,Y,Y
Gemsbok/Oryx,N,N,Y,N,N,N,N,Y,N,Y,N,Y,N,Y,Y,Y,Y,Y,Y,N,N,N,N,Y,Y,N,N,Y,Y,N,N
Genet ,Y,N,N,N,Y,N,N,N,Y,Y,Y,N,N,Y,N,Y,Y,N,N,N,N,Y,Y,N,Y,N,N,N,N,Y,Y
Ground Squirrel,N,N,N,N,Y,N,Y,Y,Y,N,N,N,Y,Y,N,Y,N,N,N,N,N,N,Y,N,Y,N,N,N,N,Y,Y
Hare ,N,N,N,N,N,N,Y,Y,N,N,N,Y,N,Y,Y,Y,N,N,N,N,N,N,Y,N,N,Y,N,N,N,Y,Y
Hartebeest (Red),N,Y,Y,N,N,N,N,Y,N,N,N,Y,Y,Y,N,N,N,N,Y,Y,N,Y,N,Y,Y,N,Y,Y,Y,N,N
Honey Badger ,Y,N,N,N,Y,N,N,Y,N,Y,N,N,N,N,Y,Y,Y,N,N,N,N,Y,Y,N,N,N,Y,N,N,Y,Y
Human,N,N,N,N,N,N,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N
Hyena (Brown),Y,N,N,N,N,N,N,Y,N,N,N,N,N,Y,N,N,N,N,N,N,N,N,Y,N,N,Y,N,Y,N,N,N
Jackal (Black-backed),Y,N,N,N,N,N,N,Y,N,Y,N,Y,Y,Y,Y,Y,Y,N,N,N,N,N,Y,N,Y,N,N,Y,N,Y,N
Klipspringer,N,N,Y,N,N,N,N,Y,N,N,N,Y,N,Y,N,Y,N,Y,N,N,N,N,N,Y,N,Y,N,N,N,Y,N
Kudu ,N,Y,Y,N,N,N,N,Y,Y,N,N,Y,Y,Y,Y,Y,N,N,Y,Y,N,N,Y,N,N,Y,Y,Y,Y,N,N
Leopard,Y,N,N,N,N,N,N,N,N,N,Y,Y,N,N,N,N,Y,N,N,N,N,Y,N,N,Y,N,Y,Y,Y,N,N
Lion (cub),Y,N,N,N,N,N,N,Y,N,N,N,Y,Y,N,N,N,N,N,N,N,N,Y,N,Y,Y,N,Y,Y,N,Y,N
Lion (female),Y,N,N,N,N,N,N,Y,N,N,N,Y,Y,N,N,N,N,N,N,N,N,Y,N,Y,Y,N,Y,Y,Y,N,N
Lion (male),Y,N,N,N,N,N,N,Y,N,N,N,Y,Y,N,N,N,N,N,N,N,N,Y,N,Y,Y,N,Y,N,Y,N,N
Meerkat/Suricate,N,N,N,N,Y,N,N,N,N,Y,N,Y,N,N,N,N,N,N,N,N,N,Y,N,N,Y,N,N,N,N,Y,Y
Mongoose (Small/Cape Grey),N,N,N,N,Y,N,N,Y,N,N,N,N,N,N,N,Y,N,N,N,N,N,N,Y,N,Y,N,N,N,N,Y,Y
Mongoose (Water),N,N,N,N,Y,N,N,Y,N,N,N,N,Y,Y,N,N,N,N,N,N,N,N,Y,N,Y,N,N,N,N,Y,Y
Mongoose (Yellow),N,N,N,N,Y,N,N,Y,N,N,N,Y,N,N,N,N,N,N,N,N,N,N,Y,N,Y,N,N,N,N,Y,Y
Monkey (Vervet),N,N,N,Y,N,N,N,Y,N,N,N,N,N,N,Y,Y,Y,N,N,N,N,N,N,N,Y,N,N,Y,N,Y,N
Ostrich,N,N,N,N,N,Y,Y,Y,N,N,N,N,N,Y,N,Y,Y,N,Y,N,N,N,Y,N,N,N,N,Y,Y,N,N
Otter (Cape Clawless),N,N,N,N,Y,N,N,Y,N,N,N,N,Y,Y,N,N,N,N,N,N,N,Y,N,N,Y,N,N,N,N,Y,Y
Polecat (Striped),N,N,N,N,Y,N,N,N,Y,N,N,N,N,N,Y,N,Y,N,N,N,N,Y,N,N,Y,N,N,N,N,Y,Y
Porcupine,N,N,N,N,N,N,Y,Y,N,N,Y,N,N,N,Y,N,Y,N,N,N,N,N,Y,N,N,Y,Y,N,N,Y,Y
Rabbit (Red Rock),N,N,N,N,N,N,Y,Y,N,N,N,N,N,N,N,Y,N,N,N,N,N,N,N,Y,N,Y,N,N,N,Y,N
Rabbit (Riverine),N,N,N,N,N,N,Y,Y,N,N,N,N,N,N,N,Y,N,N,N,N,N,N,N,Y,N,Y,N,N,N,Y,N
Reedbuck (Mountain),N,N,Y,N,N,N,N,Y,N,N,N,Y,Y,Y,N,Y,N,N,Y,N,N,N,Y,N,N,Y,N,Y,N,N,N
Reptiles/Amphibians,N,N,N,N,N,N,Y,Y,N,Y,Y,Y,Y,Y,Y,Y,Y,N,N,N,N,Y,N,N,Y,Y,N,N,N,Y,Y
Rhebok (Grey),N,N,Y,N,N,N,N,Y,N,N,N,Y,N,Y,N,Y,N,N,N,N,N,N,N,Y,N,N,N,Y,N,N,N
Rhinoceros (Black),N,N,N,N,N,N,Y,Y,N,N,N,N,N,N,N,Y,N,N,N,N,N,Y,N,N,N,N,Y,N,Y,N,N
Rock hyrax/Dassie,N,N,N,N,N,N,Y,Y,N,N,N,N,N,Y,N,Y,N,N,N,N,N,Y,N,N,N,Y,N,N,N,Y,Y
Rodent,N,N,N,N,N,N,Y,Y,N,Y,N,Y,Y,Y,Y,Y,Y,N,N,N,N,Y,Y,Y,Y,N,N,Y,N,Y,Y
Secretary Bird,N,N,N,N,N,Y,N,Y,N,Y,N,N,N,N,Y,Y,Y,N,N,N,N,N,N,N,Y,N,N,Y,Y,N,N
Springbok,N,N,Y,N,N,N,N,N,N,Y,N,Y,N,Y,Y,N,N,N,Y,N,N,N,N,Y,N,N,N,Y,N,N,N
Steenbok,N,N,Y,N,N,N,N,Y,N,N,N,Y,Y,Y,Y,N,N,Y,N,N,N,N,N,Y,N,N,N,Y,N,N,N
Tortoise,N,N,N,N,N,N,Y,N,N,Y,Y,Y,N,Y,N,N,N,N,N,N,N,Y,N,N,N,Y,N,N,N,Y,Y
Warthog,N,N,N,N,N,N,Y,Y,N,N,N,N,N,Y,N,Y,N,N,N,N,N,Y,N,Y,N,N,Y,N,N,N,Y
Weasel (Striped),Y,N,N,N,Y,N,N,N,Y,Y,Y,N,Y,Y,N,N,Y,N,N,N,N,N,Y,N,Y,N,N,Y,N,Y,N
Wild Cat,Y,N,N,N,N,N,N,Y,Y,N,N,Y,N,N,N,Y,N,N,N,N,N,Y,N,N,Y,N,N,N,N,Y,N
Zebra (Burchell's),N,Y,N,N,N,N,N,N,Y,N,N,N,N,N,Y,N,Y,N,N,N,N,N,Y,N,Y,N,Y,N,N,N,N
Zebra (Mountain),N,Y,N,N,N,N,N,N,Y,N,N,N,N,N,Y,N,Y,N,N,N,N,N,Y,N,Y,N,Y,N,N,N,N
Fire,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N
No Animals Present,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N
```

**Closed** 2020-04-16 12:53 UTC
Labels: bug
