### ISSUE TITLE
Feedback for question task types - potential bug

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#4891] opened 2018-09-13 21:14 UTC
## Expected behavior
Feedback for question task types to work as expected/documented. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

Email from <jordannelson1.2014@u.northwestern.edu, researcher at Northwestern University building the Earthscope project: https://www.zooniverse.org/lab/6465 

Hi Laura,

I'm testing the single-question task feedback you've enabled for our project 'Earthquake Detective' (project 6465)--thank you!

A possible bug (wasn't sure if I should put this to github since I haven't inspected the code too closely): it seems the '#feedback_N_answer' might be feeding the 'correct' index value (0 or 1 e.g.) into the Boolean interpreter for '#feedback_N_successMessage' vs '#feedback_N_failureMessage'--that is, if 0 is the index of the correct answer, and the 0th answer is selected by a user, the '#feedback_N_failureMessage' message spits out as if the evaluation of 'success' were false (0?). For this reason, I had to put the desired 'success message' into the 'failure message' field for any 'feedback_N_answer'==0 in order to achieve the correct functionality. 

I haven't tested this too extensively, but here's a link to my manifest (https://drive.google.com/file/d/1cmN-P5DOznngD0bZSVnl5K7Oqx5D4z7B/view?usp=sharing) as it was originally written (without swapping feedback message fields) so you can have a look to tell me if I made a field error or typo, etc.

The feedback functionality does work, though. Thanks for enabling it for our testing,

-Jordan

## Additional information

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment] 2018-09-13 21:52
Here’s the feedback rule code, if that helps debug this. https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/features/feedback/shared/strategies/single-answer-question/reducer.js

**Comment by eatyourgreens** [comment] 2018-09-13 21:55
That code should return true if the supplied answer is 0 and the rule answer is 0. It just compares the two as strings.

**Comment by monadnoc** [comment] 2018-10-11 03:15
The feedback rule code snippet does appear very straightforward

This bug is more generically malicious than originally thought: the feedback always returns the #feedback_N_failureMessage failure message when #feedback_N_answer is 0.

To clarify, below is a snapshot of data classified as 'Noise' in a workflow--Noise is the 0th (first) position of the two possible answers, so #feedback_N_answer is 0 in the manifest. When 'Earthquake' (second, lower answer button) is selected, the failure message appears, as might be desired:
![noise_answered_as_eq](https://user-images.githubusercontent.com/41121628/46778365-00e86580-ccd9-11e8-9e2c-6587ce432a49.png)
(The failure message is actually miss-written here and should say "actually this is from noise," but that is beside the point.) The point is that when 'Noise,' (first, upper answer button) is selected, the same failure message also appears:
![noise_answered_as_noise](https://user-images.githubusercontent.com/41121628/46778452-558be080-ccd9-11e8-8a50-37bdada66e52.png)

So the feedback really doesn't seem to be comparing anything correctly if it returns the failure message regardless of the button/answer. 

Of course, perhaps '0' should never be used as the #feedback_N_answer number, but the feedback works for #feedback_N_answer equal to 1 (the second, lower answer button), so if this is the case, what is the #feedback_N_answer for the first, upper button?

**Comment by trouille** [comment] 2018-10-11 12:29
@monadnoc If you haven't already, could you create a small subject set of ~10 subjects with the needed metadata/feedback files and test on that small set. Then please link the subject files and metadata/feedback here (through a google drive link or other). 

@mcbouslog -- once @monadnoc has done that, could you look into this so @rogerhutchings  can stay focused on TESS? Good way to gain more knowledge of how the feedback system works.

**Comment by eatyourgreens** [comment] 2018-10-11 13:35
By the way, you can reproduce this bug if you change the expected answer to '0' (and the supplied answer to 0) in the test for a correct answer: https://github.com/zooniverse/Panoptes-Front-End/blob/edac5a92e31b7075d482fadbbf87eaa5013cce57/app/features/feedback/shared/strategies/single-answer-question/reducer.spec.js#L14-L18

**Comment by monadnoc** [comment] 2018-10-11 13:36
Here is a subject set of 16 .mp3 +.png subjects (32 data files) with a manifest (1 .csv) that was used for testing.

https://drive.google.com/drive/folders/1pmo_RlLz_xVDnuICZp47bKRRDlyEzPpd?usp=sharing

**Comment by eatyourgreens** [comment] 2018-10-11 13:38
I think that happens because `const answerId = annotations || -1` will set `answerId` to -1 if annotations is 0 ie. false.

**Comment by eatyourgreens** [comment] 2018-10-11 13:39
Also, the naming is confusing in the reducer. `annotations` is actually a single annotation value, not a set of annotations.

**Comment by eatyourgreens** [comment] 2018-10-11 13:54
Fixed by #4983.

**Closed** 2018-10-11 15:51 UTC
Labels: Project: feedback, bug
