### ISSUE TITLE
Logging in on preview version breaks css

### ISSUE THREAD

**Issue by chrislintott** [zooniverse/Panoptes-Front-End#457] opened 2015-06-02 09:21 UTC
![screen shot 2015-06-02 at 10 06 48](https://cloud.githubusercontent.com/assets/423607/7932551/032c8f5e-0911-11e5-8257-772a5a2d45e8.png)

(Chrome 43.0.2357.81, not repeated on current demo site)

**Comment by brian-c** [comment] 2015-06-02 13:02
Couldn't reproduce this, are you sure it's changing on sign-in? It looked okay before?

Design for that section has changes coming, too: #364.

**Comment by srallen** [comment] 2015-06-02 14:18
I've noticed this issue in webkit browsers, but can't get it to reproduce consistently. That being said and as I noted in the earlier issue, another design iteration is coming for the actual content. I'll update it once I get a more concrete design from @heathv.

**Comment by chrissnyder** [comment] 2015-06-16 16:00
Fixed via https://github.com/zooniverse/Panoptes-Front-End/pull/547

**Closed by chrissnyder** 2015-06-16 16:00 UTC
