### ISSUE TITLE
adding intro text in Project Builder: make character limit explicit

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#2239] opened 2016-02-29 19:47 UTC
I didn't realize there was a 1500-character limit on the introduction text for a project. I'm working on a project where there's a lot of branding images and required "this project doesn't express the official opinion of..." etc. text that needs to show on the front page. I went over the limit and the text wouldn't save, and I didn't know why until I happened to mouseover the box.

I think we should message this a bit more explicitly.

**Comment by aliburchard** [comment] 2016-03-02 11:47
should we just take off that character limit?

**Comment by alexbfree** [comment] 2016-03-02 13:54
It does seem rather arbitrary

**Comment by vrooje** [comment] 2016-03-21 23:14
Yeah, I'd be a fan of that, or increasing it...

**Comment by vrooje** [comment] 2016-04-23 19:42
@brian-c or others ( @marten ? @camallen ? @parrish ?), can we remove the character limit, at least temporarily? It's basically impossible to use the introduction for anything useful in our Ecuador earthquake response project because the character limit is only barely high enough to include all the logos of partners -- and we need a few paragraphs of text in there besides.

I can put it in the Research tab but that is really not ideal as there's other stuff that needs to go there... so if this is possible it would be fantastic to do this very very soon.

**Comment by camallen** [comment] 2016-04-23 21:12
Pretty sure its a front end restriction only. Submitting the data via the client directly would circumvent it as a workaround

**Comment by brian-c** [comment] 2016-04-23 23:52
@camallen Looks like a back-end thing, sorry:

https://github.com/zooniverse/Panoptes/blob/master/app/models/project_content.rb#L8

Presumably we could just delete this line?

**Comment by vrooje** [comment] 2016-04-23 23:59
Ah, is that why I got a 400 trying to update the text via the API?

**Comment by camallen** [comment] 2016-04-24 22:12
Ha, thanks @brian-c. Should we have a limit and if so what size?

**Comment by alexbfree** [comment] 2016-04-26 14:21
Note that Roger has added a character counter, which has been merged in #2493. This should at least make it easier to see what the problem is. We definitely need to increase this limit though.
4000? 5000?

**Comment by vrooje** [comment] 2016-04-26 15:10
I'd be in favor of a higher limit like 5k; perhaps with a warning right
below the counter that says something like "The longer your intro is, the
less likely people are to read it."

**Comment by parrish** [comment] 2016-04-26 15:54
I think this might be a similar problem to the Talk character limit.

>  a lot of branding images

In cases where a user is entering a lot of links or images, the amount of markdown or URL characters can cause the character length to grow far faster than the actual text content.

If we move the validation client-side, we could find the visible character count from the rendered markdown.

I think `innerText` would be the best representation of the actual text, but I know that has some cross-broswer variability.  It might just be best to bump the limit and add a caveat.

@brian-c, is this an awful idea?

**Comment by alexbfree** [comment] 2016-04-26 16:03
We could strip out any html tags before calculating length.

**Comment by vrooje** [comment] 2016-04-26 16:06
Maybe count html tags as a fixed length? Images should count in some way
but people shouldn't be penalised for good title tags or long URLs.

**Comment by parrish** [comment] 2016-04-26 16:13
> We could strip out any html tags before calculating length.

[o̘̝̙ NO N*̶͑̾̾​̅ͫ͏̙̤͇̫͛͆̾Ȏ̘̝̙ͧ̌ͨO̼ͫ̑͆O͊̒ͪͩͬ̚̚​͖͉̗̩̳̟̍ͫͥͨO N͊̒ͬͪͩ̚̚Θ​̃ͤ͂̾̆](http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags#answer-1732454)

Let's just let the browser render it if we approach this

**Comment by brian-c** [comment] 2016-04-26 16:18
I think we're seriously overthinking this. We've got a counter now. Why don't we just increase the character limit?

**Comment by parrish** [comment] 2016-04-26 16:19
>  It might just be best to bump the limit and add a caveat.

Could be.

**Closed** 2016-04-26 20:19 UTC
