### ISSUE TITLE
Should commenting on a subject set the focus_id and focus_type?

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#1548] opened 2015-09-10 17:00 UTC
Not sure if this is a front-end bug, or even a bug, but querying the talk API for comments by `focus_id` and `focus_type`, to get comments for a subject, only ever returns the first comment for a subject ID. Looks like focus isn't set for subsequent comments.

You can see an example here: https://www.zooniverse.org/projects/adrianevans/fossil-finder/talk/subjects/703283 only shows one comment. Any replies submitted from that page don't seem to have `focus_id` or `focus_type` set, and only show up on the full discussion https://www.zooniverse.org/projects/adrianevans/fossil-finder/talk/97/3787/

**Comment by aweiksnar** [comment] 2015-09-10 18:26
Duplicate of #1250 - We're planning to rethink that page, but I'll try to get a patch up for this in the meantime.

If you do need to fetch those comments from the api for anything `https://talk-staging.zooniverse.org/discussions?subject_default=true&focus_id=3156&focus_type=Subject` will grab the ones from that subject thread

**Closed by aweiksnar** 2015-09-10 18:26 UTC
