### ISSUE TITLE
Organizations: a way for researchers to easily filter Talk and Collections to subjects from their expedition(s)

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2972] opened 2016-09-05 19:55 UTC
## Expected behavior

Auto-tagging subjects by related expedition/workflow, or something in subject metadata, so a researcher can easily filter Talk/Notes for subjects related to their expedition(s)
## Additional information
- **Operating system:**
- **Browser:**

**Comment by mcbouslog** [comment] 2017-08-02 19:15
Original idea may have been for org-level Talk that included all related project Talk activity, but I believe current plan is for a org-related project to have Talk just like any other project (they may leave org) and have org have it's own Talk, but find a way to link the org and related project Talks through something like a pinned Board throughout.

Somewhat duplicate of #3012, closing this issue to focus discussion in that issue.

**Closed by mcbouslog** 2017-08-02 19:15 UTC
Labels: talk
