### ISSUE TITLE
Zooniverse landing page needs sorting and/or search

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#903] opened 2015-06-30 15:34 UTC
The Zooniverse landing page seems like a jumble right now. With 33 projects on 2 pages, it's already unwieldy. (And although I appreciate that Snapshot Serengeti is first, it's currently 'paused', so really **shouldn't** be first.) I really liked how the old Zooniverse page had projects sorted by themes. Would be nice to at least be able to sort by theme. As the number of projects grow, it's going to be vital to be able to search, as well.

**Comment by DarrenMcRoy** [comment] 2015-06-30 15:38
We're working on this. :-)

Duplicate of #701, discussion also in #680 and https://github.com/zooniverse/Panoptes/issues/1042.

**Closed by DarrenMcRoy** 2015-06-30 15:38 UTC
