### ISSUE TITLE
Add invert button to Talk subject viewer

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#5094] opened 2018-11-27 05:38 UTC
## Requested behavior
Add invert button to Talk subject viewer.

## Current behavior
Subjects viewed within Talk do not have the invert button.

**Comment by eatyourgreens** [comment] 2018-11-27 08:33
Duplicate of #4706, I think.

**Comment by eatyourgreens** [comment] 2018-11-27 08:41
Also request for survey projects here: https://www.zooniverse.org/talk/17/610656?comment=1311667

**Closed** 2019-03-04 13:26 UTC
Labels: enhancement, talk
