### ISSUE TITLE
Improve Project Thumbnails

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#700] opened 2015-06-24 14:33 UTC
1. Images look pixellated and are oddly cropped.
2. Usernames should use "display name" rather than lowercase username.
3. Each project should have a description line - and maybe some kind of call to action?

Compare:
![new-zoo](https://cloud.githubusercontent.com/assets/1473244/8332453/eaf913a4-1a85-11e5-8e4e-06b75d10d650.png)
and
![new-personal](https://cloud.githubusercontent.com/assets/1473244/8332528/35c8aba6-1a86-11e5-80e3-8b33fc6166ad.png)
and
![pixellated](https://cloud.githubusercontent.com/assets/1473244/8332532/3daa0d88-1a86-11e5-8aef-788a995d8633.png)
to
![old](https://cloud.githubusercontent.com/assets/1473244/8332540/48ee640a-1a86-11e5-858f-a15b6c5a269b.png)

See also #688 , the buttons could be improved too as white on white is odd.

**Comment by DarrenMcRoy** [comment] 2015-06-24 14:46
Duplicate of #655, discussion also going on in #681.

**Closed by DarrenMcRoy** 2015-06-24 14:46 UTC
