### ISSUE TITLE
hashtags on sidebar: duplicate tags showing up

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#923] opened 2015-07-01 13:43 UTC
Seems like a bug:

![screen shot 2015-07-01 at 14 32 58](https://cloud.githubusercontent.com/assets/2357126/8455835/76409e9a-1fff-11e5-9aa6-3a73717a12fa.jpg)

**Comment by aweiksnar** [comment] 2015-07-01 13:48
Duplicate of #831, There's a an open PR for this (#909)

**Closed** 2015-07-01 13:48 UTC
Labels: duplicate, talk
