### ISSUE TITLE
Drop down for the list of existing collections doesn't work properly

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2056] opened 2015-12-24 10:19 UTC
I've started using Panoptes collections in big and noticed a bug:

When I click on the drop-down to open the list of existing collections, it closes immediately. It only stays opened as long as I keep the mouse button down on the drop-down arrow. Once I put my finger up from the button, the list closes/disappears. The only way to keep it opened is to click and hold the button down while moving the cursor to the left, on the 'Collection name' text. Then it stays opened. (Not sure it is the problem, but after clicking on the drop-down a scroll bar appears on the right side of it which makes the space for the head line *Add Subject to Collection* text too narrow and so it divides into two lines - it moves the *collection* word down. It also moves the drop down for opening the list down, so the cursor doesn't stay on it. Could this be causing closing of the list?

Why this is so irritating: When the list is longer and I need to scroll down to choose a collection which is not displayed on the first four positions, it is a big problem. I'm using a track point so I can't scroll other way then by using the scroll bar on the side of the window. When I know the names of the collection which are hidden, then I can type their names. But since there are all collections from all Panoptes projects displayed in the same list, it will become a problem soon. 

And one more thing.. The list of collections doesn't display what project they are related to, so I'm afraid I will put the image into a 'wrong' one. I would like to keep the collections separated for each project. When we have such similar projects like Whales as indi and Snapshot at sea, it will be difficult to recognize what project is my Humpback collection related to since we see humpbacks in both projects, unless I add the project name into the name of the collection. Is this a final solution for the list of collections, or are you about to change that somehow? Please, consider that :) I believe I am not the only one who would like to keep the collections for individual projects.

Hope it makes sense.
Working on Chromium, Ubuntu at this moment, unable to test other browsers today.

**Comment by camallen** [comment] 2016-01-25 15:30
@yshish is this still a problem? I can't reproduce on my ubuntu linux box using Chrome.

**Comment by MvGulik** [comment] 2016-04-10 02:26
Same problem with Chrome on Windows.
This problem, in my case, got triggered after I created a 5th collection.

*Looks at posts date's ... and feels something dropping.* :(

**Comment by MvGulik** [comment] 2016-04-10 10:16
Taking a peek at it (*mainly to fix this locally*) it seems a general simple problem (_source_).
1) If you click (__Mouse-Button-Down__) on the known-collections field to open the collection-names list. ...
2) And the displayed known-collection-list is bigger than the "Add subject to Collection" box. ...
The "Add subject to Collection" box ... gets re-sized. (*that's generally never a good thing when its initiated on a user action, As it has the potential to trigger those really annoying "User having to fight the system" features.*)
Than, when releasing the mouse button (__Mouse-Button-Up__) (*at the same location, as where simulation a normal single mouse click*) The list gets closed again, because when the mouse button goose up again, its nowhere near where the list is displayed, ... of course.

:(

[Aye, sir. The more they overthink the plumbing, the easier it is to stop up the drain.](http://www.youtube.com/watch?v=n3V4C3XNOJU)

**Comment by MvGulik** [comment] 2016-04-10 10:45
>(Not sure it is the problem, but after clicking on the drop-down a scroll bar appears on the right side of it which makes the space for the head line Add Subject to Collection text too narrow and so it divides into two lines - it moves the collection word down. It also moves the drop down for opening the list down, so the cursor doesn't stay on it. Could this be causing closing of the list?)

Yes, it is.
(_kinda mist that part. Gives an easy workable local fix in the form of a "white-space: nowrap;" attached to the header-text-line in question._)

**Comment by camallen** [comment] 2016-04-11 11:05
@MvGulik thanks for a working reproduction of the bug!! 

This is definitely a problem and renders the collect for drop down (default state) unusable. Looks like react-select now offers the `autosize` options in v1.0, so we could either try this or use component css to fix the issue.

**Comment by yshish** [comment] 2016-04-11 15:06
@camallen Oops, so sorry for ignoring your question from Jan 25! I've been extremely busy and the notification got somehow lost among flood of other messages.

Yes, it is still a problem and it is very irritating :]

Thanks for looking at this.

**Comment by chrislintott** [comment] 2016-05-03 15:54
Assigned to @parrish - think this is in your bailiwick.

**Closed** 2016-05-04 16:20 UTC
Labels: bug

**Comment by MvGulik** [comment] 2016-05-04 16:33
Might as well add that for me locally, fixing the vertical scroll-bar (*for the target window/frame*) to be always on, did the trick on stabelizing the window/frame content. Although that's probably more of a workaround than a true fix (*Although "true fix" is kinda relative*).
