### ISSUE TITLE
Have focus move up to the top of the page when you move to the next page on the list of projects

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1698] opened 2015-10-05 13:14 UTC
When you move to the next page of the live projects list, you don't get moved up to the top of the page you have to scroll all the way up to see the list of projects. I think the focus should move up automatically to make it easier for someone perusing the projects list

I'm using Firefox 41.0.1 on OS X Yosemite

Screenshot of what I see after moving to the 2nd page below:

![screen shot 2015-10-05 at 9 13 04 pm](https://cloud.githubusercontent.com/assets/753325/10281283/fdb6fbfc-6ba5-11e5-8d04-5870543b18e5.png)

**Comment by CKrawczyk** [comment] 2015-10-05 13:27
Duplicate of https://github.com/zooniverse/Panoptes-Front-End/issues/957

**Closed** 2015-10-05 13:29 UTC
