### ISSUE TITLE
Updating background *on homepage* doesn't work

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes-Front-End#4688] opened 2018-06-11 13:38 UTC
I'd like to point out that if this feature is broken, we might consider removing it instead of fixing it. I'm not sure what the point of it is. We're not myspace, we probably don't need to let people upload a different background.

## Expected behavior

New background appears.

## Current behavior

No background appears. Error in console log states:

![image](https://user-images.githubusercontent.com/277/41234687-c6c81a16-6d84-11e8-9d0c-a2ded6d6c9d3.png)

```
Creating resource for 1_003.png, image/png
main-20f88aa5b7da68e89377.js:1 Uploading 1_003.png => https://zooniverse-static.s3.amazonaws.com/panoptes-uploads.zooniverse.org/production/user_profile_header/asdf.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=asdf%2F20180611%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180611T133307Z&X-Amz-Expires=10800&X-Amz-Security-Token=asdf&X-Amz-SignedHeaders=content-type%3Bhost&x-amz-acl=public-read&X-Amz-Signature=asdf
/api/users/299778/profile_header?http_cache=true:1 Failed to load resource: the server responded with a status of 404 ()
vendor-95668f862e2004eaeaa8.js:1 Uncaught (in promise) Error: No profile_header exists for user #299778
    at n.handleError (vendor-95668f862e2004eaeaa8.js:1)
```

## Steps to replicate

Go to homepage. Click "Update background". Choose image, click ok.

## Additional information

- **Operating system:** Ubuntu 18.04
- **Browser:** Chromium 66.0.3359.181

**Comment by eatyourgreens** [comment] 2018-06-11 14:00
No problems here, updating the background on my profile just now (Chrome, OSX.)

**Comment by eatyourgreens** [comment] 2018-06-25 17:04
I’m unable to reproduce this. Do we know how many volunteers have profile header images? We should check if this is used before removing it.

**Comment by eatyourgreens** [comment] 2018-08-08 10:10
Closing this because it couldn't be reproduced.

**Closed by eatyourgreens** 2018-08-08 10:10 UTC
