### ISSUE TITLE
Adding a magnifier feature from Talk 2.0 into panoptes Talk 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#979] opened 2015-07-06 01:31 UTC
future feature request - I've seen a few request on P4T Talk to have the magnifier that exists on P4 Talk on the new panoptes talk. I don't think the magnifier is implemented in all of Talk 2.0 but for some projects like P4. 

Basically you moused over the subject and a zoom in window showed up that could move around the image to see different parts at higher resolution 

Since you can't see my mouse in a screenshot, I faked a mouse pointer in the image

![screen shot 2015-07-06 at 9 26 06 am](https://cloud.githubusercontent.com/assets/753325/8514403/a09f4b58-23c1-11e5-9f05-c126515ee24e.png)

**Comment by chrissnyder** [comment] 2015-10-13 20:05
Consolidating into https://github.com/zooniverse/Panoptes-Front-End/issues/1271

**Comment by aweiksnar** [comment] 2015-10-13 20:10
Since talk uses the general subject-viewer component for displaying, I saw this issue as more related to adding zoom to the site in general than the subject page specifically

**Comment by chrissnyder** [comment] 2015-10-13 20:12
Fair enough, reopening for discussion.

**Comment by aweiksnar** [comment] 2015-10-13 20:15
@chrissnyder Duplicate of #278 then?

**Comment by DarrenMcRoy** [comment] 2015-10-13 20:16
If it's about adding zoom to the site generally, is there any consideration to having an *optional* zoom function for the classification interface?

I know that some research teams do not want it for fear that it will taint their classifications by adding a variable, but others may indeed want it to make things easier for users --

Oh, yes, as Alex just writes, there is an issue already open about that #278

**Comment by chrissnyder** [comment] 2015-10-13 20:19
@DarrenMcRoy Different consideration I'd say, though not without merit.

@aweiksnar Also think thats different. #278 is the retinas's crop task, so zooming in on part of an image as an explicit part of a workflow.

This may or may not be added directly to the subject viewer. Could wrap the component in a ZoomHover component or some such, so wouldn't have to be added site-wide if we didn't want.

**Comment by aweiksnar** [comment] 2015-10-13 20:49
My 2 cents on the talk-specific zoom- I think that if we do offer zoom it should be done site wide ~ and optional per project, since there's demand for it in both places. Volunteers will likely expect it when classifying if it's in talk, similar to how they requested the collect/favorite icons in talk that were on the classification page

**Comment by DarrenMcRoy** [comment] 2015-10-13 20:52
By optional per project, you mean it's either in both Talk and the classification interface, or in neither?

**Comment by aweiksnar** [comment] 2015-10-13 20:53
Yeah that'd be my vote

**Comment by mschwamb** [comment] 2015-10-14 02:50
What about being about to click and seeing a larger scaled version of the image instead? At some point I presume with the redesign the size of the image on the subject page will change but people like especially in talk being to see a lager image to tease out details to discuss.

**Comment by chrislintott** [comment] 2015-10-19 09:42
It’s a bad idea to allow this in the main interface, as it makes analysis of classifications very difficult.

**Comment by mschwamb** [comment] 2015-10-19 09:55
And just to clarify, I'm only asking for a feature to view a larger version of the subject image in Talk not in the classification interface to echo @chrislintott's comment.

**Closed** 2015-10-19 16:16 UTC
Labels: feature request, talk
