### ISSUE TITLE
New private message notification mark doesn't disappear after reading the message

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#1540] opened 2015-09-08 20:51 UTC
When I receive a private message and open it, the red notification mark doesn't disappear. It stays displayed there even after leaving the Profile page and visiting the Talk. (I came back to the Profile page to check whether it means I've received another message and figured out it just hasn't disappear yet.) Only reloading the Profile page helps. 

This happens always.

**Comment by DarrenMcRoy** [comment] 2015-09-08 20:52
I've noticed this as well.

**Comment by yshish** [comment] 2015-09-08 20:55
Btw, when I'm on the Talk page, the notification mark about a new message doesn't appear when a new message comes. I have to reload the page first. Then I figure out that the message is waiting there for some time already. Could it appear immediately without reloading please?

**Comment by DarrenMcRoy** [comment] 2015-09-08 21:08
Mmmm... that second one may not be possible? At least, how Reddit works is that the icon only appears as red once you've gone to a new page after a message has been sent. Aren't people generally going to be going to new pages on Talk all the time?

**Comment by yshish** [comment] 2015-09-08 21:15
Well, if it's not possible, then it's not possible but it would be nice and useful. I'm used to Discussion Forums where this works, so I'm used to it). 

When you're waiting for a reply to your private message, then you have to keep reloading to see the red dot. So if you stay on the Talk just waiting (without reloading the page), you will wait "forever", won't you?

**Comment by edpaget** [comment] 2015-09-08 21:16
It's definitely possible.

**Comment by mschwamb** [comment] 2015-09-08 23:30
duplicate of #1035 in case that one should be closed.

**Comment by parrish** [comment] 2015-09-16 21:02
@aweiksnar This is actually due to a hashchange event not being fired.  I'm looking for a way to pickup location changes beyond a interval poll.

Maybe, is it possible to have a global [`routerWillLeave`](https://github.com/rackt/react-router/blob/master/docs/api/Lifecycle.md#routerwillleavenextlocation) implementation?

**Comment by aweiksnar** [comment] 2015-09-17 14:58
Yeah I'll bet this is doable via lifecycle methods / react-router routes. I had something similiar-ish in that PR for css classes on different pages. Didn't realize that the switch to non-hashed URLs affected this

**Comment by parrish** [comment] 2015-09-17 18:04
Which PR was that?

**Comment by aweiksnar** [comment] 2015-09-17 18:16
#1486

**Closed** 2015-09-17 20:13 UTC
