### ISSUE TITLE
Link to subject pages from places in Talk where objects are featured

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1101] opened 2015-07-16 16:10 UTC
For instance, the Notes board:

https://www.zooniverse.org/#/projects/tedcheese/whales-as-individuals/talk/31/204

Or anywhere else that an object is selected as the featured object (like here: https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/9/182 ), there should be a link to go back to the subject page (the "hub" for the image).

Right now, the only way is to manually copy and paste the ID number into the link.

**Comment by aliburchard** [comment] 2015-07-16 18:23
Yes!! +1

**Comment by mschwamb** [comment] 2015-07-16 23:34
you have to do a ^82979398 or whatever the subject number is

**Comment by mschwamb** [comment] 2015-07-16 23:36
duplicate of an already reported ticket #916

**Comment by mschwamb** [comment] 2015-07-16 23:38
Worth noting in other discussions if you use ^15005 or whatever the subject id is, it is supposed to do the same link behavior Talk 1.0 and 2.0 do when you write out APF ASG ids.

**Comment by chrissnyder** [comment] 2015-07-20 17:44
This will definitely be in for the second sprint. Consolidating discussion at #916

**Closed by chrissnyder** 2015-07-20 17:44 UTC
Labels: talk
