### ISSUE TITLE
Limiting number of draw tools

### ISSUE THREAD

**Issue by rjsmethurst** [zooniverse/Panoptes-Front-End#1564] opened 2015-09-16 11:16 UTC
From analysing the data from the bar project which asks users to draw a line for the length and line for the width of the bar in a galaxy image we've realised there's nothing to stop people from drawing as many lines as they want. Could we put something into the Build Project tools that let's you select which drawing tool and limits how many a user can draw?

**Comment by aliburchard** [comment] 2015-09-16 14:46
This comes up a lot (and I swear is an existing issue but I couldn't find it). We get this request constantly from project builders, and would go a long way to simplifying interpretation of results....

**Comment by vrooje** [comment] 2015-09-21 00:43
+1 to both - like Ali I seem to remember this coming up before, but either way I agree this would be a great feature to add.

**Comment by mkosmala** [comment] 2015-09-22 18:45
Might be useful to have both a MIN and a MAX. For example, one task in Jungle Rhythms needs exactly 6 points made. "MIN=6 and MAX=6" would solve this. Right now, "requires" implicitly is a MIN=1. It should be simple to to code to require the number of objects of a particular tool be within specified bounds for the "next/done" button to be un-grayed-out.

**Comment by vrooje** [comment] 2015-09-22 20:07
I like that.

**Comment by aliburchard** [comment] 2015-09-22 21:47
me too!

**Comment by chrislintott** [comment] 2015-10-02 04:10
+1

**Comment by chrissnyder** [comment] 2015-10-16 20:07
Duplicate of https://github.com/zooniverse/Panoptes-Front-End/issues/518

**Closed by chrissnyder** 2015-10-16 20:07 UTC
Labels: feature request
