### ISSUE TITLE
Have to drag and drop avatar and background image twice for it to upload

### ISSUE THREAD

**Issue by frankvitaleiv** [zooniverse/Panoptes-Front-End#1065] opened 2015-07-14 17:01 UTC
When uploading the project avatar and background image in Project Details, the first drag-and-drop displayed the image in the upload area and then quickly reverted to it's neutral state, without uploading the image.  Dragging and dropping the same image a second time resulted in a successful upload.  I'm not sure if this is just lag or an issue with the uploader, but it happened too quick to get a screenshot.

**Comment by vrooje** [comment] 2015-07-15 18:51
I've had some issues knowing whether an avatar successfully uploaded as well. I'm not sure it was exactly the same but I've definitely had the avatar uploader not refresh with the new image, but when I went to view the project it was there.

**Comment by chrissnyder** [comment] 2015-10-13 18:51
Definitely seen some disappearing images that reappear with refreshes within any of the drag-and-drop image upload areas. Tagging as bug to get it fixed.

**Comment by brian-c** [comment] 2015-10-14 18:21
@chrissnyder is there a specific field you've identified as broken? Image uploads for avatars, project backgrounds, and user headers seems to be okay for me.

**Comment by chrissnyder** [comment] 2015-10-16 20:48
https://youtu.be/xfJ9s0xoNvI

Fairly repeatable on Chrome. Seems to happen on hover.

**Comment by brian-c** [comment] 2015-10-16 21:08
Ah weird. I can reproduce it in Chrome 46 but not 47. Will look into it.

**Comment by VVH** [comment] 2016-02-17 14:40
Not pressing, but I'm seeing this behavior pop up again after it seemed to have stopped for a few months.

**Comment by brian-c** [comment] 2016-07-22 15:17
I think this'd be a pretty easy fix. The image selector used for user settings seems to work fine.

**Comment by mschwamb** [comment] 2016-09-23 17:34
closing - repeat of #2317 which has some more detail on the fix for this

**Closed by mschwamb** 2016-09-23 17:34 UTC
Labels: bug, help wanted
