### ISSUE TITLE
Reorder view only shows (n-1) workflows

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4154] opened 2017-11-13 10:00 UTC
I can't reorder my workflows to move the last one on the page up. It disappears from the list when I click on reorder 

When clicked on reorder view
<img width="1095" alt="screen shot 2017-11-12 at 11 48 10 pm" src="https://user-images.githubusercontent.com/753325/32719764-8bbf439c-c805-11e7-9262-59d2464f3e44.png">

Actual number of workflows if not clicked on 'reorder view'
<img width="1119" alt="screen shot 2017-11-12 at 11 55 18 pm" src="https://user-images.githubusercontent.com/753325/32719772-95e4a92a-c805-11e7-93b2-49ed853a50ff.png">

**Comment by eatyourgreens** [comment] 2017-11-21 12:55
I'm not able to reproduce this on my test project. Clicking 'reorder view' lists all four of my workflows.

Workflow listing:
![Workflow listing view, showing four test workflows](https://user-images.githubusercontent.com/59547/33073493-000f4434-cebb-11e7-819a-5799bf1b7f4a.png)

Reorder view:
![Reorder view, showing the same four workflows](https://user-images.githubusercontent.com/59547/33073517-0cfc22f2-cebb-11e7-9848-d02666e4c13d.png)

**Comment by eatyourgreens** [comment] 2017-11-21 13:11
Same result if I go to https://www.zooniverse.org/lab/3219/workflows as an admin and click on 'reorder view':
![Reorder view for P4:Ridges, listing all four workflows](https://user-images.githubusercontent.com/59547/33074239-5e875c2a-cebd-11e7-8b53-9575e4d68207.png)

**Comment by mschwamb** [comment] 2017-11-21 14:03
Could it be that I'm using firefox?

**Comment by mschwamb** [comment] 2017-11-21 14:06
Seems to work for me now. Which is odd. I did just upgrade to Firefox 57.  I wonder if it happens when you just create the workflow. I wanted to reorder right after making it, so that's when I was doing that, so maybe it had the old count before the workflow was created?

**Comment by mschwamb** [comment] 2017-11-21 14:10
I got some odd things when I clicked create workflow and then click on workflow page. It doesn't list the new work flow all the time. Depending on how many times  click on list view it shows up or not. 

<img width="1103" alt="screen shot 2017-11-21 at 6 06 38 am" src="https://user-images.githubusercontent.com/753325/33076773-8afdd206-ce82-11e7-801b-05b71a6d6494.png">
<img width="1094" alt="screen shot 2017-11-21 at 6 07 51 am" src="https://user-images.githubusercontent.com/753325/33076774-8b14aa30-ce82-11e7-8075-17b232d3ba0c.png">
<img width="1071" alt="screen shot 2017-11-21 at 6 08 15 am" src="https://user-images.githubusercontent.com/753325/33076775-8b96dd70-ce82-11e7-88c8-4b6355449c0f.png">

Getting all three as a toggle back and forth between list view. The initial list didn't show the new workflow when I just created it, but the list view did. 

I deleted the new workflow since it was just a test. Someone might be able to reproduce this with a new workflow

**Comment by camallen** [comment] 2017-11-21 14:13
This could be linked to api caching resources and not resetting the cache on workflow changes. See https://github.com/zooniverse/Panoptes/issues/2393

**Comment by eatyourgreens** [comment] 2017-11-21 16:02
Yep, this is a Panoptes bug where a new workflow is not always present in the list of project workflows returned from the API.

**Comment by eatyourgreens** [comment] 2017-11-21 16:03
Closing this in favour of zooniverse/Panoptes#2393

**Closed by eatyourgreens** 2017-11-21 16:03 UTC
