### ISSUE TITLE
Need to be able to add subject sets to workflows for live projects via the Project Builder

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2226] opened 2016-02-23 15:26 UTC
Zooniverse is encouraging projects to work with their subjects in batches. That is, projects should only have some of their subjects live at a given time, because the rate of classification is unclear at the start. When the initial subset of subjects is almost fully retired, a project owner then wants to add in more subjects to keep the project alive and to get more subjects classified.

However, right now, a project owner needs to un-live the project to make changes to workflows, including adding new subject sets to workflows or removing ("pausing") ones that are currently linked. There is then no automatic way to put the project back into "live" mode, and project owners are then dependent on someone at Zooniverse finding the time to do so. 

This week, Jungle Rhythms (@khufkens) needs to link new subject sets to workflows, and next week Season Spotter Questions needs to remove subject sets from workflows for a targeted campaign. We can do work-arounds for these two projects this time. But the need to link and unlink subject sets to workflows for live projects will become a common use case in the future, and should be supported on the Front End.

**Comment by camallen** [comment] 2016-02-23 15:41
Duplicate of #824 - this is a UX issue on the project builder. The api will allow you to link the sets to the workflow without unliving the project.

**Closed by camallen** 2016-02-23 15:41 UTC

**Comment by camallen** [comment] 2016-02-23 15:43
Not that you should have to use the api but adding the docs here for reference, http://docs.panoptes.apiary.io/#reference/workflows/update-subject-set-links
