### ISSUE TITLE
Sidebar doesn't load project Talks properly

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1337] opened 2015-08-05 14:52 UTC
When going from project Talk to project Talk, the sidebar dropdown does not always load new discussions and boards correctly.

Generated the following by going from Whales to WIldebeest (note discrepancy between header and the actual boards).

![screen shot 2015-08-05 at 9 44 36 am](https://cloud.githubusercontent.com/assets/8987864/9088807/906215f6-3b57-11e5-9dd0-ce828ac02d68.png)

Also, neither Season Spotter is in the sidebar, and I still strongly believe that the first item on the list should be the Zooniverse Talk, yes even though there's a link to it at the top of the page.

**Comment by chrissnyder** [comment] 2015-08-05 15:28
The switching behavior is definitely a bug.

That said, let's table the discussion of what to do with the dropdown. There was some thoughts expressed that the sidebar is basically a place in search of content, and might be axed in a refreshed design of Talk.

Not disagreeing on your points, but let's try to look at it from a bit wider perspective.

**Comment by DarrenMcRoy** [comment] 2015-08-05 15:37
My personal feeling is that the fact that the sidebar is devoid of content at this time is not for lack of possible content that could go there. :-) But, agreed, exactly what does go there, or how it exists, is a larger discussion that ties into Heath's new wireframes. I'll trim this down to just the bug.

**Comment by mschwamb** [comment] 2015-08-05 21:31
Same thing as #/1151 @chrissnyder if it's more helpful if I label my tickets so it's easier to find I would need collaborator status. Currently I don't have that for this repo so I can't add labels. if you want to continue adding labels for me based on my tickets that's fine too.

**Comment by aweiksnar** [comment] 2015-08-06 15:00
@mschwamb You should be all set as a collaborator now

**Comment by chrissnyder** [comment] 2015-08-10 20:34
Closing as duplicate of #1151

**Closed by chrissnyder** 2015-08-10 20:34 UTC
Labels: talk
