### ISSUE TITLE
New project centric collection pages don't autoscroll to the top when you advance to the next page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2868] opened 2016-08-09 06:38 UTC
You stay on the bottom in the browser where the page toggle buttons are instead of moving to the top of the page automatically so you can see a new page is shown. 
See https://www.zooniverse.org/projects/mschwamb/comet-hunters/collections?page=2 and advance to page 3 

Just tried in firefox

**Comment by alexbfree** [comment] 2016-08-09 10:55
linking to #2852 and #2762

**Comment by alexbfree** [comment] 2016-08-09 10:58
This is not a regression. Looks like this was never working on collections whether zoo-wide or in project context. It seems this a general issue. Also applies on Zoo-wide collections (zooniverse.org/collections), and on the zooniverse.org/projects page. So it looks like we need to solve this generally. Which we should do in #2852 . 

I'll add a note to #2852 and close this as duplicate.

**Comment by srallen** [comment] 2016-08-09 14:17
Fixing scroll to top with react router isn't the same as building a generalized pagination solution and I don't think they should be conflated together. One is straight forward to fix, while the other would presumably take a bit more time.

**Comment by eatyourgreens** [comment] 2016-08-09 16:12
Closed by #2874

**Closed by eatyourgreens** 2016-08-09 16:12 UTC
Labels: bug, collections, help wanted
