### ISSUE TITLE
Use full width when entering subtasks

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#1785] opened 2015-10-16 15:46 UTC
The display is odd and awkward to use when entering subtasks, you end up having to resize the box to make room if your text is more than 4 words... 

![screenshot](https://cloud.githubusercontent.com/assets/1473244/10546282/fe0c8cac-7424-11e5-99d1-49056bc28e62.png)

either the containing white boxes should be much narrower, to hug the text boxes:

![screenshot](https://cloud.githubusercontent.com/assets/1473244/10546345/57923dda-7425-11e5-8de0-8382ec941a6d.png)

or the text boxes should be wider to fill the containing boxes:

![screenshot](https://cloud.githubusercontent.com/assets/1473244/10546337/50346d42-7425-11e5-9a44-e047b1dca821.png)
(in which case it might even be possible to show them side by side)

This is not just a visual thing, it makes it awkward for data entry when the box is smaller than it needs to be....

**Comment by chrissnyder** [comment] 2015-10-16 19:58
Duplicate of https://github.com/zooniverse/Panoptes-Front-End/issues/621

**Closed by chrissnyder** 2015-10-16 19:58 UTC
Labels: design, project builder
