### ISSUE TITLE
Showing incorrect "confused_with" in the classification

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#5538] opened 2019-10-30 18:03 UTC
## Expected behavior
When you select a species from the list of species in the task, you get "confused with" and list of a few species the chosen one can easily be confused with.

## Current behavior
Lately, all the "confused with" options show the same species we have chosen. 
Screenshot from AmazonCam - I chose Agouti from the list so I should see other species than agouti as the "confused with" - but I see 5 agouti buttons instead:
![ysh_Screenshot_2019-10-30_18-55-05](https://user-images.githubusercontent.com/7211888/67885120-475c6c80-fb47-11e9-8a51-766a413b63a4.png)

Once you click on a "confused with" option, it does show the correct image&description. In this case, the second Agouti shows Capybara:
![ysh_Screenshot_2019-10-30_19-00-06](https://user-images.githubusercontent.com/7211888/67885327-ad48f400-fb47-11e9-85a9-86805bd87424.png)

## Steps to replicate
Go to the classification of AmazonCam, select a species and look at the "confused with" options.

## Additional information
It probably happens in other/all projects of this type. According to: https://www.zooniverse.org/talk/18/1161362?comment=1894453

- **Operating system:** Linux Ubuntu
- **Browser:** Chromium (latest version)

**Comment by yshish** [comment] 2019-10-30 18:07
Also, after submitting the classification from my screenshot, I got a disturbing error in the browser console - look:

![ysh_Screenshot_2019-10-30_19-05-41](https://user-images.githubusercontent.com/7211888/67885783-79ba9980-fb48-11e9-9754-fd4df3bd56f5.png)

Is that related?

**Comment by srallen** [comment] 2019-10-30 19:40
@yshish no, you have a previous classification (maybe from a different project?) in your local storage queue that is failing, with that error about not being a user with an expert role for that particular project. I'm not sure why that might've happened for you without getting more information about the failed classification submission itself. The classification you just made in that screenshot submitted correctly.

For the failed classification, type in this into the javascript console: `copy(localStorage.getItem('failed-classification'))` and then paste the result into an email to contact@zooniverse.org (the classification may have your user id, and that's PII so I don't want you to post that on a public message). We can investigate that more once we get more information.

As for the issue with the confused pairs, an accessibility enhancement seems to have introduced the regression. We're reverting it right now.

**Comment by srallen** [comment] 2019-10-30 19:47
Closing since #5533 is now reverted by #5539  and deployed. Likely issue is this line in #5533: https://github.com/zooniverse/Panoptes-Front-End/pull/5533/files#diff-3bb4a3465c95d0e6d761e7d94f49f939L127

**Closed by srallen** 2019-10-30 19:47 UTC
