### ISSUE TITLE
Bouncing you should log in button shows up with every talk subject image when not logged in

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2571] opened 2016-05-11 22:24 UTC
Would it be possible to remove the button and the animation from Talk? I find it  distracting as my eyes go to the giggling button every time I reply to a Talk comment or recent comment I spot on the recent comments page. A pop-up already shows up when you try and hit reply non-logged in asking you to log in or make an account  cc @brian-c @parrish 

![new_tutorial](https://cloud.githubusercontent.com/assets/753325/15198452/24b777da-1773-11e6-9083-e95d2931a967.gif)

**Comment by alexbfree** [comment] 2016-05-12 08:10
I think that's kind of the point. Users can get rid of it themselves by logging in.

**Comment by mschwamb** [comment] 2016-05-12 08:57
I found it honestly really distracting perusing the recent comments as you scroll down each one of the subject images has a bouncing log in button and then when I click on the talk subject page  to see if there is a comment/discussion from someone else.  i found it rather annoying. I stay non-logged in and log in when I need to reply to something on my project Talks. I know some of the mods on projects do something similar. I get the point of the reminder to login annimating once  but I don't think there should be an animated button on every talk page and every new view of a subject image  as someone is perusing.

**Comment by eatyourgreens** [comment] 2016-05-12 10:44
There's a body of user research that backs you up @mschwamb Animation on web pages can distract some people to the point that they can't actually use pages that contain animation. Standard advice is to keep distracting animation short and, if possible, give users control to turn the animations on and off (see https://www.w3.org/TR/UNDERSTANDING-WCAG20/time-limits-pause.html)

The login prompt follows that advice on time limits, which is good, but I agree that it is annoying on every page and could put people off.

**Comment by alexbfree** [comment] 2016-05-12 11:44
I guess it depends what the point of the feature is. Maybe it was *supposed* to compel people to act to remove the message? Let's ask @brian-c who implemented this. If we can understand what this feature was supposed to achieve that would help.

**Comment by alexbfree** [comment] 2016-05-12 11:48
Hey @mschwamb , this is a side question but i'm just curious to understand why you choose to "stay non-logged in and log in when I need to reply to something on my project Talks". What is the benefit of doing that? Given the projects share the same login, you could sign in once and not have to sign in again. Would be interested to understand why that is preferable...

**Comment by eatyourgreens** [comment] 2016-05-12 11:56
@alexbfree I think, at the moment, it's something like having a small child next to you asking, on each Talk page, "Have you logged in yet?", "Have you logged in yet?" etc. etc. 😄

**Comment by mschwamb** [comment] 2016-05-12 12:05
@eatyourgreens exactly and it's the only animated component on the pages so it really draws my eye and to me stands out against the rest of the site which is still and statics. Also it's just weird placed under the subject. I think this situation in the ticket is an unintended result from the button on the interface that was implemented and animates with every classification non-logged in. I think the button just needs to be hidden. If you try and reply to a thread you get the pop-up asking to sign or register.  

Also it looks like a bug when you scroll down the Talk recent comments page as when you first get there all the buttons for the subject preview at the same time. I think the button was supposed to be hidden here. Most classifiers don't log in so  that would put me off from registering if I was perusing Talk to see what is was. 

I'm not commenting on the issue of it being animated in the classification interface at the moment, I have strong preferences and thoughts on that but to me it looked like the  button being on Talk is an unintended consequence and should be hidden but that was forgotten

**Comment by brian-c** [comment] 2016-05-12 14:22
The intention here was definitely to be slightly annoying to encourage people to sign in. It animates for three seconds; if it's going longer than that (doesn't look like it to me) there's a bug, otherwise it's behaving as intended.

**Comment by chrislintott** [comment] 2016-08-02 16:52
Closing for now pending analysis of effect on behaviour.

**Closed by chrislintott** 2016-08-02 16:52 UTC
Labels: design, question
