### ISSUE TITLE
signout window disappears before you can hit the link if you are viewing a user profile page. 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1298] opened 2015-07-31 04:13 UTC
very low in the queue - when you're on someone's profile page (like https://www.zooniverse.org/#/users/zookeeper)  and try to log out on Mac Firefox the menu disappears before I can get down all the way to sign out. Seems to be fine everywhere else. Also seems fine if I try and go to Profile and Settings, but if I go to the other two on the list, the window disappears before I can hit the link. I get the same behavior on Chrome.

**Comment by chrissnyder** [comment] 2015-09-18 14:29
Can't reproduce this on any browser. Sounds indicative of a larger problem though. Still happening?

**Comment by mschwamb** [comment] 2015-09-18 14:36
Yep -  I think this screen capture will show how I'm reproducing it https://www.dropbox.com/s/tufoua2n1sbforx/mouse.mov?dl=0

**Comment by mschwamb** [comment] 2015-09-18 14:38
In the screen capture, I'm trying to get down and click the sign out  button. I'm using 40.0.3 firefox on mac OSX 10.10.5 (14F27)

**Comment by chrissnyder** [comment] 2015-09-18 14:39
Ok cool, we'll take a look at it.

**Comment by aweiksnar** [comment] 2015-09-18 14:39
This should be fixed with #1586. I'd hold off on any work here till then

**Comment by chrissnyder** [comment] 2015-09-18 14:40
That's what I get for not paying close enough attention. Should indeed, will wait for that to be merged.

**Comment by aweiksnar** [comment] 2015-09-18 14:41
Yeah just tested, it's working on that branch

**Closed** 2015-09-18 14:48 UTC
