### ISSUE TITLE
Bug with tester role and demo mode

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#5312] opened 2019-04-02 21:15 UTC
## Expected behavior

Expect to see the 'demo mode' icon/button when signed in as a tester role. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

https://www.zooniverse.org/projects/zooniverse/notes-from-nature/classify?reload=0&workflow=9891 is a workflow we set up to test the behavior on Notes from Nature after Denslow indicated that it wasn't working for his tester - amzooni2. 

This is what amzooni2 (who is marked as a 'tester' in the Notes from Nature project) sees:
![Workflow 9891 as amzooni2](https://user-images.githubusercontent.com/4975655/55436485-13de4300-5562-11e9-8150-337ff2cb9635.png)

When I go in as tester - testTrouille - I do see the demo mode icon as expected. 
![Screen Shot 2019-03-25 at 1 03 47 PM](https://user-images.githubusercontent.com/4975655/55436511-22c4f580-5562-11e9-9e8c-783e5b80f29c.png)

Note: AmZooni2 setup is: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0. I'm on a macbook pro w/ Chrome. Maybe first thing to check is if something is funny on windows for testers? 

## Additional information

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment] 2019-04-03 08:36
Demo mode is only available to project owners/collaborators and admins. Testers have never had access to it.

**Comment by srallen** [comment] 2019-04-03 14:41
The issue described is that @trouille's tester account can see the demo button, but amzooni's can't. @trouille isn't using her admin account. This does sound like a bug to me.

**Comment by eatyourgreens** [comment] 2019-04-03 14:44
@srallen it's not a bug. I checked the code before closing the issue.
https://github.com/zooniverse/Panoptes-Front-End/blob/fa870fe7d9187a8fba757c925dba13dca0de98ce/app/classifier/expert-options.jsx#L41-L53

**Comment by srallen** [comment] 2019-04-03 14:46
@trouille can you confirm you were logged in with your tester account when trying out that workflow? Thanks.

**Comment by srallen** [comment] 2019-04-03 14:47
Do we have a reason to disallow testers from using this?

**Comment by eatyourgreens** [comment] 2019-04-03 14:49
No idea: https://github.com/zooniverse/Panoptes-Front-End/pull/1673

**Comment by srallen** [comment] 2019-04-03 14:55
Thanks for finding the old issue and checking the current code. @trouille seems like we've never supported this, though, unsure of the reason. Can NfN work around it? We can plan on supporting this in the new classifier.

**Comment by eatyourgreens** [comment] 2019-04-03 15:10
Searching through PFE for 'tester', all I can find is that they can preview inactive workflows, presumably to test them before they go live. https://github.com/zooniverse/Panoptes-Front-End/issues/4180

**Comment by eatyourgreens** [comment] 2019-04-03 15:14
To be honest, we don't record classifications on inactive workflows, so what would demo mode add here?

**Comment by trouille** [comment] 2019-04-03 15:15
Realized I shared the wrong image above - meant to share the one where I'm logged in as 'testTrouille' - which isn't an admin or collaborator. See here:
<img width="1048" alt="Screen Shot 2019-04-01 at 5 17 42 PM" src="https://user-images.githubusercontent.com/4975655/55490477-70407180-55f9-11e9-864b-1163a3200578.png">

**Comment by trouille** [comment] 2019-04-03 15:19
Weird though. Now when I go to it w/ TestTrouille, I don't see the 'demo mode' either. Maybe there was some latency with having been signed in as Trouille when I took that screenshot last week? 

In any case, thanks Jim & Sarah for following up. 

I'll follow up with Denslow to explain how he can still use the 'tester' role/functionality (without the 'Demo mode button' with volunteers to test a workflow before it's live .

**Comment by eatyourgreens** [comment] 2019-04-03 15:21
Now that is a bug, because demo mode should be hidden after you log out as a member of the project team.

**Comment by srallen** [comment] 2019-04-03 15:22
@trouille what the bug might be is that the state of whether or not to show that button isn't reset when you logged out of your admin account and switched to the tester account. 

And @eatyourgreens is correct that we don't count the classifications submitted on inactive workflows toward stats or retirement, so is there specific need for not allowing them to POST at all for NfN? I'll re-close the issue, confirm what I suspect to be the actual bug here (the state not resetting) and then open a different issue for that.

**Comment by eatyourgreens** [comment] 2019-04-03 15:24
@srallen could be a recurrence of the issue you posted here: https://github.com/zooniverse/Panoptes-Front-End/issues/3582

**Closed** 2019-04-03 15:23 UTC
Labels: bug

**Comment by srallen** [comment] 2019-04-03 15:32
It's a very similar bug, perhaps a regression happened at some point? That particular issue was only that it remained on log out. I'm not sure if we fully tested for the account switching case.
