### ISSUE TITLE
Support additional of social media links for a project in project builder

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2109] opened 2016-01-13 23:16 UTC
It just occurred to me that we don't have a mechanism where a project builder can enter their project's twitter ID or facebook page and have a link appear when users visit the project. For example Pulsar Hunters has a Twitter feed but no way to find it from the site.

A workaround can be achieved by manually adding links to the menu bar, but a social media settings page in the project builder (which adds icons for Twitter, Facebook, etc) would be even better.

**Comment by mschwamb** [comment] 2016-01-14 02:01
duplicate of #489 I think

**Comment by srallen** [comment] 2016-12-21 21:36
Closing in favor of #489

**Closed by srallen** 2016-12-21 21:36 UTC
Labels: feature request, project builder, ui
