### ISSUE TITLE
Abiilty to report comments to a moderator on Talk

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1071] opened 2015-07-15 01:10 UTC
I noticed this [thread](https://www.zooniverse.org/#/talk/13/613) on Zooniverse wide Talk started by likely some people playing around. This might be something the moderator for Zooniverse wide Talk (I think that's @DarrenMcRoy) might want to delete, but there's no way currently to alert a moderator to take a look at a post. In previous versions of Talk there was a report button. I think adding that functionality in the near future would be helpful

**Comment by aweiksnar** [comment] 2015-07-15 13:17
Duplicate of #910. This is the next feature coming (look out for it today/this-week)

**Closed by aweiksnar** 2015-07-15 13:17 UTC
