### ISSUE TITLE
Tutorial tab remains highlighed in chrome after completing the tutorial

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4588] opened 2018-05-02 10:17 UTC
In chrome if you click on tutorial and complete the tutorial, the tutorial tab remains teal until you click on something else. This behavior doesn't happen in Firefox. It seems like a bug since it would be odd to continue highlighting once you've completed the tutorial

Before clicking on the tutorial tab

<img width="1110" alt="screen shot 2018-05-02 at 12 13 24 am" src="https://user-images.githubusercontent.com/753325/39518256-1a4c640a-4d9e-11e8-9d12-9310f774e772.png">

After clicking on the tutorial tab and completing the tutorial

<img width="1115" alt="screen shot 2018-05-02 at 12 13 36 am" src="https://user-images.githubusercontent.com/753325/39518310-4174bb40-4d9e-11e8-98ec-6a9876186908.png">

**Comment by srallen** [comment] 2018-05-02 14:17
I'm not sure if this is a bug, but rather a difference in Firefox and Chrome in how they handle focus.

**Comment by mschwamb** [comment] 2018-05-02 15:35
maybe the focus should go back to the classification interface tab after the tutorial is completed?

**Comment by eatyourgreens** [comment] 2018-05-02 15:42
It actually does do that when the tutorial opens automatically. Focus returns to the tutorial button if you opened the tutorial from that button. Standard behaviour for modal popups on OSX and Windows is that they return focus to whichever element was being interacted with when they opened. If you open the tutorial from the tutorial button, focus returns to the tutorial button and you continue navigating the interface from there.

**Comment by mschwamb** [comment] 2018-05-02 15:49
I could see people not being sure if they're classifying a tutorial image or not given this behavior doesn't happen you come in from the landing page.

**Comment by eatyourgreens** [comment] 2018-05-02 15:55
Closing this because this is intended behaviour. We can re-open it if it does cause problems for anyone.

**Closed by eatyourgreens** 2018-05-02 15:55 UTC
Labels: facelift

**Comment by eatyourgreens** [comment] 2018-05-02 16:00
Linking #4522 since the redesigned tutorial will open a tab in the task area. The popup will only appear on first visit to a project.
