### ISSUE TITLE
When you delete a subject from a subject set the counter doesn't update

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#1781] opened 2015-10-16 14:36 UTC
At the top of the list it shows the number of subject - but this doesn't update when you delete one.

**Comment by chrissnyder** [comment] 2015-10-16 14:38
Duplicate of https://github.com/zooniverse/Panoptes-Front-End/issues/1128

**Closed by chrissnyder** 2015-10-16 14:38 UTC
Labels: bug, project builder
