### ISSUE TITLE
Echo: After finishing the classification, new subject loads but the previous one is actually displayed

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#3729] opened 2017-04-14 09:49 UTC
## Expected behavior
When you finish the classification, new subject should load and display. When you visit the Talk, you should see the same subject you have just classified.

## Current behavior
After finishing the classification, new subject does load but the previous one is actually displayed. When you go to the Talk, you see something else than you saw on the Classification page.
(Happened to me 3 times in a row on AmazonCam Tambopata, and another volunteer is experiencing the same from two different computers, even with a fast internet connection). It doesn't happen all the time.
_Will provide some browser console screenshots when it happens the next time._

## Steps to replicate:

1. Classify a subject (call it subject A) on AmazonCam Tambopata.
2. When finished classifying, click "Done".
3. If you're "lucky", you'll get a new subject (subject B) as expected but you'll actually see the same as in the step 1 (subject A). (You won't see how the subject B looks like).
4. Classify the subject (you see subject A but it is actually subject B), and click "Done & Talk". 
5. Subject B will load on the Talk although you were expecting to see the subject A there (It was the one you classified).

## Additional information:
It may look like a repeated subject (with no *Already seen* banner) but when you classify it and go to the Talk, it displays the new subject and not the one you saw in the classification. 
It is not always obvious that the subject you see is the same one as you have just finished. Especially when there are no animals present...
Discussed also here: https://www.zooniverse.org/projects/rainforestexpeditions/amazoncam-tambopata/talk/683/286699

- **Operating system: Linux x86_64** (for me; will ask what the other volunteer uses)
- **Browser: Chromium 48** (for me; will ask what the other volunteer uses)

**Comment by yshish** [comment] 2017-04-14 12:22
Here is a screenshot of the browser console errors:
[LINK](https://lh3.googleusercontent.com/NY7r3_ZLrRD0CJJoR_FZWFiho7h-1vUHLFLx59XEXqrXiye0nqYdsG5xjtzRqHEBXaEFT6DyO6-fuDbLmRYFqEawFau7F_Zgpkj1C-88LN5B3lBnJgAQsQu29tgTZJqXDS2jtdhQSiMYRZ9eTwkABM092eKzMqIer5I8UNoMQJIszRCJ9igVRv-9IxeNxBLLOEcZxoJYr3TdcJ67cc-XdLNHUBMSQcspzxqdN9oZ1S7ig-cheRrXIvIyqdee9hmJhHULwB_wjfeRp27S4yYH8-rQ-gOiEMwm-S1oelkIvFZXBN7Pd-FumDxZ43ZFyX8LWLjHPPuk977D3Bv8e66zwT_EEd_F14VCaRQz_LeIxiHmaLI4f6SzYWqXHkXk7UdfZtMXy2IkJgkUICsa6ThD64307AIaiKuTrSzpXaftPkjrxKFZFOb35hZeiJBc8zXtEoND0-RcKMw8tGppI0CiHEJafuJ32XQyfGNMdxe3KSSN1QybdH64J2vQehZS5WhFvJHixoXJmk0ftP47MqMZGyGhvv7kugg-ruUidocjzc4TqGvwONX3dVdtGS-WeyD5zGBH0QsTVm2_2QvpZsZOixdV7okl7pTO4NvQJfBRY9rPUU4d4RkR=w1810-h966-no)
![](https://lh3.googleusercontent.com/NY7r3_ZLrRD0CJJoR_FZWFiho7h-1vUHLFLx59XEXqrXiye0nqYdsG5xjtzRqHEBXaEFT6DyO6-fuDbLmRYFqEawFau7F_Zgpkj1C-88LN5B3lBnJgAQsQu29tgTZJqXDS2jtdhQSiMYRZ9eTwkABM092eKzMqIer5I8UNoMQJIszRCJ9igVRv-9IxeNxBLLOEcZxoJYr3TdcJ67cc-XdLNHUBMSQcspzxqdN9oZ1S7ig-cheRrXIvIyqdee9hmJhHULwB_wjfeRp27S4yYH8-rQ-gOiEMwm-S1oelkIvFZXBN7Pd-FumDxZ43ZFyX8LWLjHPPuk977D3Bv8e66zwT_EEd_F14VCaRQz_LeIxiHmaLI4f6SzYWqXHkXk7UdfZtMXy2IkJgkUICsa6ThD64307AIaiKuTrSzpXaftPkjrxKFZFOb35hZeiJBc8zXtEoND0-RcKMw8tGppI0CiHEJafuJ32XQyfGNMdxe3KSSN1QybdH64J2vQehZS5WhFvJHixoXJmk0ftP47MqMZGyGhvv7kugg-ruUidocjzc4TqGvwONX3dVdtGS-WeyD5zGBH0QsTVm2_2QvpZsZOixdV7okl7pTO4NvQJfBRY9rPUU4d4RkR=w1810-h966-no)

**Comment by yshish** [comment] 2017-04-14 13:18
It also happens on Windows 7 desktop using Chrome and on Microsoft Edge on a tablet.

**Comment by yshish** [comment] 2017-04-16 12:04
It seems to be affecting many people, using different browsers and OS. To me, it happens like every few minutes. Very annoying.

**Comment by srallen** [comment] 2017-04-17 19:11
I haven't been able to replicate this myself yet, but the problem is probably with these lines:     https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/classify.cjsx#L232-L233
Saving the classification isn't finishing before the next subject is called. This change came in with #3681 to fix a bug with Talk loading the wrong subject when Done & Talk is clicked. I think using the promise there will have to be revisited. 

@eatyourgreens any thoughts on this?

**Comment by yshish** [comment] 2017-04-17 19:52
Thanks for looking at this, there are already volunteers leaving the project because of the necessity to reload the page so often. Sometimes like every <10 subject.

**Comment by eatyourgreens** [comment] 2017-04-18 10:38
That fix mentioned above was for #3680 where the classification interface freezes when you press Done, and won't show you a new subject unless you reload the page.

I haven't been able to reproduce this either. I press Done, a new photo loads and I can classify it. If I press Done & Talk, Talk loads with the photo I just classified. When I go back to Classify, in that case, a new photo loads and I can classify it.

@yshish can I ask for a clarification of this
>If you're "lucky", you'll get a new subject (subject B) as expected but you'll actually see the same as in the step 1 (subject A). (You won't see how the subject B looks like)
If the new photo doesn't load, how do you know that a new subject has loaded? Is it that the buttons gray out then become clickable again?

**Comment by eatyourgreens** [comment] 2017-04-18 10:50
#2500 fixed the race condition where the new subject might load before the classification had finished saving, so I'm not sure if that is the problem here.

**Comment by eatyourgreens** [comment] 2017-04-18 11:47
@yshish can you try doing some classifications via this link, and let us know if you still have the same problem?
https://classification-queue.pfe-preview.zooniverse.org/projects/rainforestexpeditions/amazoncam-tambopata/classify?env=production

**Comment by yshish** [comment] 2017-04-18 16:53
@eatyourgreens 

>can I ask for a clarification of this

>>If you're "lucky", you'll get a new subject (subject B) as expected but you'll actually see the same as in the step 1 (subject A). (You won't see how the subject B looks like)

>If the new photo doesn't load, how do you know that a new subject has loaded? Is it that the buttons gray out then become clickable again?

When it happened for the first time, I wanted to figure out whether the problem is in the display or whether it is a true repetition. So I classified what I saw (when you choose a category, the Finished button is clickable again) and then went to Talk. And there was a different subject than I saw in the classification. 

Most volunteers told that they just classify the same image a couple of times - so it causes wrong results.

It doesn't happen all the time, so sometimes I get like 30 subjects in a row without any troubles, sometimes I have to reload the page like every 3 subjects to get a new one.

I'm going to try your link now.... Will need some time to make sure whether something has changed.

**Comment by yshish** [comment] 2017-04-18 17:44
So far so good:) Will go on classifying using that magical link and will let you know if I get any troubles later.

**Comment by yshish** [comment] 2017-04-19 20:48
![screenshot_2017-04-19_22-35-40_echo2](https://cloud.githubusercontent.com/assets/7211888/25201324/a3dcce4c-2551-11e7-8042-14e3bd115812.png)

@eatyourgreens using your link, it has just happened again. Here's a screenshot of the browser console. Btw, I'v tried to click on the pause symbol below the image and it didn't work. Also, this time, it was impossible to choose a category. When I clicked on any, nothing happened but a new error appeared in the list. It is possible that it was the same when I was using the regular link for classification but I only tried to classify it once. And not since then. Will ask the others whether they are able to click on a category. 

Sorry I have very little time for testing it some more before Saturday.

**Comment by yshish** [comment] 2017-04-20 04:20
Another volunteer using the regular link to classify has confirmed that:
*when it happens now, the play button is stuck on pause, and it isn't possible to make a classification but could classify when the problem first appeared*.

**Comment by srallen** [comment] 2017-04-20 14:31
@yshish I think that might be an unrelated bug. I'll look to see if I can replicate it.

**Comment by yshish** [comment] 2017-04-21 15:22
OK, we realized that when you hit the DONE button before the classified sequence stopped playing, the classification freezes for the next subject - the play button is stuck and we're unable to classify. That is what we've been experienced lately with the echo bug. Better solution than reloading the page is to click on the About button (top menu) and then coming back to the Classify page. Is that helpful?

**Comment by yshish** [comment] 2017-04-21 15:27
So, that is an unrelated bug. I've tested that and didn't let the sequence stop before hitting the DONE button on a purpose. The next subject has loaded (I did see a new image there) but the classification wasn't possible, even when the next subject wasn't playable sequence but a single imaged subject.

I'll try to make sure that playing of the sequence has stopped before clicking on the DONE and will tell you when the echo problem appears whether I am able to classify (as I definitely was when it appeared first) or not.

**Comment by yshish** [comment] 2017-04-21 15:59
I've just experienced another "echo" and was able to classify! 

I made the first screenshot when the new subject loaded but I saw the previous one instead (with a selected category to show you that I am able to classify).
![screenshot_2017-04-21_17-46-18_echo3](https://cloud.githubusercontent.com/assets/7211888/25285649/4cb55efc-26bb-11e7-9307-d1fe1018150e.png)

I made the second screenshot after I clicked on the About button and got back to the Classification page (as I know it should show me the same subject as I was about to classify before leaving the classification), but as you can see, the image looks different before I left the classification.
![screenshot_2017-04-21_17-47-54_echo3x](https://cloud.githubusercontent.com/assets/7211888/25285749/9aae69e6-26bb-11e7-8f42-08739c8f620d.png)

I made the third screenshot after I hit DONE & TALK and got to the Talk page to show that it is not just another from the 3 pictures of the same sequence as the subject is made of a single image.
![screenshot_2017-04-21_17-49-41_echo3xx](https://cloud.githubusercontent.com/assets/7211888/25285797/c9b9ff48-26bb-11e7-908c-be8ea158d79f.png)

Hope this is helpful. Please, let me know if you don't follow what I mean. The language barrier is a little higher today :]

**Comment by yshish** [comment] 2017-04-21 16:39
@eatyourgreens And I've managed to experience the Echo bug while using your magical link too, and I was able to classify as you can see in the screenshot below:

![screenshot_2017-04-21_18-35-39_echo4](https://cloud.githubusercontent.com/assets/7211888/25287474/c4884f4c-26c1-11e7-9b63-685024232a5d.png)

**Comment by yshish** [comment] 2017-05-08 07:56
As for the unrelated bug that freezes the classification when a sequence is playing when you hit the Done button (described above), it also happens when the sequence is stopped but not on the 1st frame when you hit the Done button.

I did some testing and this seems to be related to the type of the new subject.

There are three types: 

 1. sequence made of 3 frames
 2. sequence made of 2 frames
 3. single framed subject (no playing)

When the sequence of 3 frames is playing when I click on the Done button and the new sequence is also made of 3 frames, then nothing wrong happens. The new sequence is playing already at the moment it loads but I am able to classify without any troubles.

When there is a sequence of 3 frames and I am on other than the 1st frame when I hit the Done button and the following subject is made of 1 frame only, the classification freezes (because it tries to display the 2nd or 3rd frame that is not part of the subject?).

Sometimes it even displays a frame from the previous subject together with the single frame of the new subject and plays them together, although they aren't related). But when I go to the About page and back to the Classification, I find there is only a single framed subject loaded.

Shall I create new issue for the freezing bug?

**Comment by eatyourgreens** [comment] 2017-05-08 10:45
Hi @yshish can you try classifying using this link and see if your bug still happens? https://default-file-viewer.pfe-preview.zooniverse.org/?env=production

That link uses #3767, which should fix the `React.createElement: type should not be null…` error that you are seeing in the console.

I suspect you are right and the bug with the number of slideshow frames is a different problem, but let's see if #3767 fixes that too. If not, then certainly open it as a new issue.

**Comment by yshish** [comment] 2017-05-08 10:59
I tried the link you provided. This is what loaded after I hit the Done button while the sequence was playing...

![screenshot_2017-05-08_12-56-33_test01](https://cloud.githubusercontent.com/assets/7211888/25801498/20e35898-33ee-11e7-850b-0ac368a52031.png)

**Comment by eatyourgreens** [comment] 2017-05-08 11:02
@yshish That's extremely useful. So the slideshow has to be playing to trigger this bug?

I think I've been unable to reproduce it because I've been classifying with the slideshow stopped or paused.

**Comment by eatyourgreens** [comment] 2017-05-08 11:08
@yshish one more question, did the `Unknown file type` message stay there, or did it show briefly and then the next subject loaded, ready to classify?

**Comment by yshish** [comment] 2017-05-08 11:14
When the unknown file type appear, it was first flashing - it seemed to try plying the image with no image like a sequence but then it stopped on the unknown file type screen.

I tried it again with the sequence stopped on the 3rd frame and the following 2framed sequence loaded as unknown file type but there were two circles just below those words and when I clicked on one it showed me the frame from the new sequence.

I'll try a few more classifications to make sure what happens and let you know then.

**Comment by eatyourgreens** [comment] 2017-05-08 11:18
Thanks. Like you said, it sounds like the slideshow is still playing three frames, even if the new image only has one frame. That `unknown file type` message means it's trying to show frame 2 or 3, which doesn't exist.

**Comment by yshish** [comment] 2017-05-08 11:23
Yes. Now I hit done while playing a 3-framed sequence, the new was a 1-framed subject. Again, the *unknown file type* appeared, flashing alternately with the frame of the new subject. But then it stopped on the actual frame so I could classify it without clicking on any circle.

I haven't experienced the echo bug for some time. Not sure how (or if at all) it is related to this.

**Comment by eatyourgreens** [comment] 2017-05-08 11:32
@yshish Thanks again. Sounds like #3767, which you've been testing, has fixed the React error, but the underlying problem is that the slideshow is broken.

We probably haven't seen this before because it needs a project where some subjects are slideshows but others are single frames, and also the slideshow needs to be playing when the Done button is pressed.

**Comment by eatyourgreens** [comment] 2017-05-08 11:34
I think the fix for this issue will be to overhaul the [SubjectViewer component](/zooniverse/Panoptes-Front-End/blob/master/app/components/subject-viewer.cjsx), and ensure that the slideshow playing state and initial frame are correctly reset when a new subject loads.

Pinging @rogerhutchings since he worked on the default frame view for slideshows recently, so might be most familiar with this.

**Comment by eatyourgreens** [comment] 2017-05-08 13:18
@yshish could you try some classifications at this link: https://fix-3729.pfe-preview.zooniverse.org/?env=production

That's testing a version of the code which stops the slideshow, and resets it, when a new subject loads.

**Comment by yshish** [comment] 2017-05-08 14:09
@eatyourgreens Seems to be working perfectly, as far as I can tell :+1:

**Comment by eatyourgreens** [comment] 2017-05-08 14:13
Excellent. 👍

**Closed** 2017-05-08 14:25 UTC
