### ISSUE TITLE
Can't see talk moderator controls for a project I'm a collaborator on

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#1085] opened 2015-07-15 17:07 UTC
Seems my section project roles are in the next page of roles from the api and not being assigned correctly as per project talk retrieves all user roles and not all user : project roles, https://talk.zooniverse.org/roles?user_id=X

@brian-c this is the issue i was talking about on slack. Can provide more details if needed.

**Comment by parrish** [comment] 2015-07-15 17:19
This is a duplicate of #1083

**Comment by camallen** [comment] 2015-07-15 17:35
Related but i think the front end could be more specific when in a project talk to just return that section / resources roles otherwise eventually a prolific user will just bump past an arbitrary page size. 

perhaps https://talk.zooniverse.org/roles?user_id=X&section_id=Y

Either that or enumerate all the pages with extra network hops.

**Comment by parrish** [comment] 2015-07-15 17:45
I have a feeling that if a user has more than 100 roles, we're doing it wrong.

At that point they'd probably just a zooniverse role, right?

Looking at Grant for instance:

```
4-Kitteh Zoo: admin
70-Kitteh Zoo (By Grant) : admin
71-MICO: admin
81-SOCS: admin
project-125: admin
project-126: admin
project-137: admin
project-137: team
project-324: admin
project-351: admin
project-355: admin
project-356: admin
project-4: admin
project-70: admin
project-71: admin
project-74: admin
project-81: admin
zooniverse: admin
```

`zooniverse: admin` is the only role needed here.

**Comment by edpaget** [comment] 2015-07-15 17:47
The other admin roles are created when you create a new project by Panoptes. If we want to make sure the Talk admin flags and the Panotpes admin flags remain in sync I'll skip the role creation for admins.

**Comment by parrish** [comment] 2015-07-15 17:53
> I'll skip the role creation for admins. 

Only if the user is already a zooniverse admin.  This does break if a user ever lost their zooniverse admin role though.

**Comment by camallen** [comment] 2015-07-15 21:40
100 sounds like a reasonable limit, a power user over time with lots of small projects who possibly moderates on other projects could perhaps get up to that limit. 

Re Grant's example, zoo section admins are prob not indiciative of normal users. I (and others in the team) have the Zoo section team role but that doesn't allow me to moderate projects, i'd stil need the project specific mod roles for talk.

Is there any sense in restricting the moderation component to to search for section roles only? e.g. [here](https://github.com/zooniverse/Panoptes-Front-End/blob/e220bf868d470f0cdb25c3cd9e6ecdd2af3ca972/app/talk/lib/moderation.cjsx#L44) could be `talkClient.type('roles').get(user_id: user.id, section: section, page_size: 100)`. This makes more sense to me and would restrict the possible page size to the number of roles we offer (unless we allow dups). Thoughts?

**Comment by parrish** [comment] 2015-07-15 21:46
In that case, it certainly could be scoped to the section

**Comment by aweiksnar** [comment] 2015-07-15 21:47
I think it'd have to be `section: ['zooniverse', section]`so we get the zooniverse-wide label everywhere

**Closed** 2015-07-16 02:23 UTC
