### ISSUE TITLE
Workflow suggestion: add "cross-task text" field

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#821] opened 2015-06-26 02:39 UTC
Not a first-release thing, clearly, but:

We don't have tutorials. Yet, often there's an important piece of information you need to make sure the volunteer knows at all stages of classification, without requiring them to click the Help button. In GZ this text is "Note: Please always classify the galaxy in the center of the image."

There's currently no way to do this without manually adding it to each task in a workflow.

I'm doing this right now as a workaround in the GZ Bar Length project, but it's causing issues, e.g. #816. (The post-classification summary page looks weird too.)

Can we add an optional field to a workflow containing text that will show up at the top of every task?

**Comment by aliburchard** [comment] 2015-06-26 19:17
Another option would be to allow a single pop up that appears the first
time the user goes to classify. Like a 1 window tutorial. It would render
markdown just like the help pop ups but would ensure that volunteers saw
the necessary info. Because as much as they like "just in time" learning, I
get the impression that a lot of people don't click on the "need help"
button when classifying.

On Friday, June 26, 2015, Brooke Simmons <notifications@github.com> wrote:

> Not a first-release thing, clearly, but:
>
> We don't have tutorials. Yet, often there's an important piece of
> information you need to make sure the volunteer knows at all stages of
> classification, without requiring them to click the Help button. In GZ this
> text is "Note: Please always classify the galaxy in the center of the
> image."
>
> There's currently no way to do this without manually adding it to each
> task in a workflow.
>
> I'm doing this right now as a workaround in the GZ Bar Length project, but
> it's causing issues, e.g. #816
> <https://github.com/zooniverse/Panoptes-Front-End/issues/816>. (The
> post-classification summary page looks weird too.)
>
> Can we add an optional field to a workflow containing text that will show
> up at the top of every task?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes-Front-End/issues/821>.
>


-- 
Sent from my moderately intelligent phone.

**Comment by chrissnyder** [comment] 2015-10-16 20:12
Duplicate of https://github.com/zooniverse/Panoptes-Front-End/issues/484

**Closed by chrissnyder** 2015-10-16 20:12 UTC
Labels: feature request, project builder
