### ISSUE TITLE
Task categories grayed out after a video subject loads (Chimp&See)

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#5869] opened 2020-12-30 11:53 UTC
## Expected behavior
Experienced with Chimp&See project. Once a video subject has loaded in the classification interface you should be able to select a category from the Task.

## Current behavior
Sometimes after a video subject loads all the Task categories stay grayed out and you are unable to select any of them.
This lasts even after you finish playing the video (video length is 15 seconds).
Playing the video for the 2nd time helps - after another few seconds all the categories lighten up and let you classify.
Discussed here: https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/2269/1763131?comment=2869881
To me it takes about 20-30 seconds to have the categories clickable. Happens despite a perfect internet connection speed.

## Steps to replicate
It happens occasionally (for me a couple of times per hour). Keep classifying subjects in row unless it happens. 

## Additional information
Happens to various volunteers using various devices, browsers and OS. (So far reported on ipad with Safari and Chrome, and in Ubuntu with Chromium).
Browser console shows large number of 415 errors while classifying. I guess they are related to the missing thumbnails and not to this problem. Anyway, the latest two errors say:

5dcebe01-3cb4-4373-9244-e6d35d8f62e6.jpeg:1 GET https://thumbnails.zooniverse.org/500x999/panoptes-uploads.zooniverse.org/production/workflow_attached_image/5dcebe01-3cb4-4373-9244-e6d35d8f62e6.jpeg 415
Image (async)
gt @ vendor-295edb9252ce7a64e56e.js:72
Fo @ vendor-295edb9252ce7a64e56e.js:72
Ro @ vendor-295edb9252ce7a64e56e.js:72
Io @ vendor-295edb9252ce7a64e56e.js:72
ks @ vendor-295edb9252ce7a64e56e.js:72
Ms @ vendor-295edb9252ce7a64e56e.js:72
Ys @ vendor-295edb9252ce7a64e56e.js:72
Yn @ vendor-295edb9252ce7a64e56e.js:72

132classify:1 GET https://thumbnails.zooniverse.org/500x500/panoptes-uploads.zooniverse.org/production/workflow_attached_image/7ba40191-50b2-422a-aa7b-514ccfab10fd.jpeg 415

**Comment by AnLand** [comment] 2020-12-30 14:47
From volunteer descriptions and own experience, it might be a performance problem.

**Comment by srallen** [comment] 2021-01-06 20:43
Possibly a duplicate of #5867

**Comment by srallen** [comment] 2021-01-06 20:43
Survey task might not be usable until all the thumbnail image requests fail. Solution would be fixing the thumbnails, but survey task should be usage even if image requests are not finished yet.

**Comment by srallen** [comment] 2021-01-07 17:09
@yshish are you still seeing this problem?

**Comment by yshish** [comment] 2021-01-12 20:43
@srallen I'm sorry for the delay, haven't classified on C&S much lately. I did few classifications today without experiencing that. Will let you know in case it appeared again.

**Comment by srallen** [comment] 2021-01-13 16:56
@yshish Ok, I'm going to close the issue. Please do reopen if you or other volunteers report that it reoccurs. Thanks!

**Closed by srallen** 2021-01-13 16:56 UTC
