### ISSUE TITLE
Add blog link

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#778] opened 2015-06-25 13:57 UTC
We should add a link to blog.zooniverse.org in the top bar next to the 'Collect' tab

**Comment by chrissnyder** [comment] 2015-06-25 13:58
Duplicate of #698

**Comment by mrniaboc** [comment] 2015-06-25 13:59
Sorry. I'm the worst.

**Closed by chrissnyder** 2015-06-25 13:58 UTC

**Comment by chrissnyder** [comment] 2015-06-25 14:00
Dont worry, I know you mean well. :facepunch:
