### ISSUE TITLE
Viewing tutorial causes workflow to change

### ISSUE THREAD

**Issue by bamford** [zooniverse/Panoptes-Front-End#3561] opened 2017-03-08 12:16 UTC
## Expected behaviour

After closing the project tutorial I expect to be in the same place I was before.

## Current behavior

Upon closing the tutorial popup, the screen jitters a bit and changes randomly to another workflow.

## Steps to replicate

See movie at https://zooniverse.slack.com/files/bamford/F4G179HT8/gz3d_bug.mov

Note that I classified a few galaxies on one workflow before logging in, and noticed a similar behaviour when the login pop-up closed, so may be related to login history?

## Additional information

- **Operating system:**
OS X 10.10.5
- **Browser:**
Safari 10.0.3

**Comment by CKrawczyk** [comment] 2017-03-08 13:14
I am not sure if it related to this bug, but the project this was observed on has 3 workflows and at the time did not have a `default workflow` set: https://www.zooniverse.org/projects/klmasters/galaxy-zoo-3d

**Comment by bamford** [comment] 2017-03-08 13:30
After @CKrawczyk set a `default workflow` I no longer encounter the issue.

Is there a way to ensure an unset `default workflow` does not occur, or otherwise avoid this in future projects?

**Comment by CKrawczyk** [comment] 2017-03-08 14:29
OK, I have a project that recreates this bug on staging: https://master.pfe-preview.zooniverse.org/projects/cmk24/test-project-2/classify

steps to reproduce:
1. go to the link above and log out
2. close the tutorial
3. click the page to "zoom in" and focus the project
4. there is about a 1-in-5 chance the workflow will change

The cause of the problem: the `preferences.preferences` object is empty when you don't select a workflow from the project's home page (e.g. going directly to the classify link above).  When the tutorial is closed it updates `preferences.preferences.tutorials_completed_at` causing the `componentWillReceiveProps` to trigger on `app/pages/project/index.cjsx`.  At this point `if nextProps.preferences?.preferences.selected_workflow isnt @state.selectedWorkflow.id` triggers and this block of code is run: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/index.cjsx#L128-L142

With no default workflow set that block of code picks a random live workflow and loads that one.  Since it is random there is a chance it will not be the workflow you were currently viewing.

**Comment by srallen** [comment] 2017-03-08 15:21
This is a bug I likely introduced while refactoring API calls on the project this week. Projects shouldn't have to set default workflows if they don't want to. Some projects actually do want workflows randomly selected. What shouldn't be happening is those lines firing after the project preferences are updated for seeing the tutorial. Those lines are for Gravity Spy's workflow promotion feature. I'll take a look at this today.

**Closed** 2017-03-09 12:15 UTC
