### ISSUE TITLE
Video subjects not working in Safari? 

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#5873] opened 2021-01-14 01:35 UTC
## Expected behavior

Projects like chimpandsee.org with video subjects should have the video subjects work in all supported browser types. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/classify, as an example - the video subjects don't appear to load correctly. 

Same for https://www.zooniverse.org/projects/obhasin/buzzy-bee-african-canopy-pollinators/classify

Note, in chrome, the video subjects don't appear to have this same problem. 

## Steps to replicate

Go to https://www.zooniverse.org/projects/obhasin/buzzy-bee-african-canopy-pollinators/classify

## Additional information

- **Operating system:**
Macbook pro mojave 10.14.6

- **Browser:**
Safari Version 14.0.2 (14610.3.7.1.10)

**Comment by srallen** [comment] 2021-01-14 15:48
@trouille did someone from the C&S team contact you separately? I've been discussing this with the team (see: https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/2269/1773901?comment=2899184). At least for C&S, it's very likely an encoding issue and not really one we can fix for them. It'll take some debugging and experimenting on their ended with encoding from the raw videos into mp4 using ffmpeg. 

If another video project is having issues, then it's most helpful to get specific subjects to have a look at. Do we have subject ids for the bee project to look at?

**Comment by trouille** [comment] 2021-01-14 15:52
I posted this in response to a question from busy bee (in https://www.zooniverse.org/projects/obhasin/buzzy-bee-african-canopy-pollinators/talk/3682/1738995) noting that their videos weren't working in safari. And C&S is my go-to to check videos to see if other projects are having the same issue.

**Comment by trouille** [comment] 2021-01-14 15:53
https://www.zooniverse.org/projects/obhasin/buzzy-bee-african-canopy-pollinators/talk/subjects/53354978 is an example that doesn't work in safari. (And just let me know if that isn't a helpful way to provide a specific subject to consider).

**Comment by srallen** [comment] 2021-01-14 16:44
@trouille there's something strange with their files. The media extension on both of those subjects is mp2, which isn't even a video file extension. It's intended for audio. I'm guessing they tried to encode with H.222/H.262? Regardless, these are encoded incorrectly for the web and for what we recommend and support. They should be using H.264/mp4 encoding to have the most cross browser support.

**Comment by eatyourgreens** [comment] 2021-01-14 16:45
Here's a Buzzy Bee video that won't load in Safari. Maybe it's the `.mp2` extension?
https://panoptes-uploads.zooniverse.org/subject_location/8d3a83ae-9b0f-4fb5-9740-a277cee6d38c.mp2

**Comment by trouille** [comment] 2021-01-14 18:02
Thanks both! I'll pass this info on to the team and post here to note if they have success with the correct extension and encoding.

**Comment by trouille** [comment] 2021-01-18 16:14
Buzzy bee [at]obhasin lead wrote in https://www.zooniverse.org/projects/obhasin/buzzy-bee-african-canopy-pollinators/talk/3682/1738995?comment=2905436&page=1: "I just checked the media info and it seems that subjects are already encoded in H.264/mp4. I work on Adobe Media Encoder to automate the process of creating multiple encoded versions of source files and I specifically select H.264 as video output format option. I do intentionally disable audio export though, as it helps reducing file size and I would not be able to manage subject size <1Mo otherwise."

![wCRyjaP](https://user-images.githubusercontent.com/4975655/104938025-1c408180-5974-11eb-9de7-419b24c78eb5.png)

But if you right-click on a subject like https://www.zooniverse.org/projects/obhasin/buzzy-bee-african-canopy-pollinators/talk/3570/1764032, you see that the file type is mp2, as noted above. 

The next question I'll ask [at]obhasin is what process they used to upload the images. Maybe there's something that happens in the upload process? I'll post here once I have that info.

**Comment by lcjohnso** [comment] 2024-01-19 17:26
Closing -- issue was resolved by using CLI for video subject upload.  There is a small chance that the drag-and-drop uploader in the Lab is causing mimetype / format mismatch or misassignment, but that is unconfirmed.

**Closed by lcjohnso** 2024-01-19 17:26 UTC
Labels: bug
