### ISSUE TITLE
Slide tutorial: Keeps popping up in Firefox

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2115] opened 2016-01-18 12:24 UTC
@brian-c See https://www.zooniverse.org/projects/zooniverse/wisconsin-wildlife-watch/talk/203/27612

Slide tutorial keeps popping up in Firefox. May also do this on iPad (haven't checked that since early December).

**Comment by brian-c** [comment] 2016-01-18 17:48
I still haven't been able to reproduce this. Might be a race condition between sign-in and tutorial fetching, but that should still only happen once.

#2123 should prevent the tutorial from popping up more than once per session.

**Comment by srallen** [comment] 2016-07-11 18:06
Gonna just close this since there haven't been any more reports of this. Will reopen if reported.

**Closed by srallen** 2016-07-11 18:06 UTC
Labels: bug
