### ISSUE TITLE
Add ability to hover over the bars of the stats barchart and get back the plotted value

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2610] opened 2016-05-18 19:58 UTC
A minor suggestion for the stats page. Not sure if this is doable, but one of the features I really like in the Ouroboros stats page is that you can hover your mouse over a single bar from the classifications per day bar chart and a box pops up with the exact value. I'm not sure if that's doable on this version, but it would be nice if you go two days before and hover over and get the exact value of classifications per day. 

cc @CKrawczyk

**Comment by CKrawczyk** [comment] 2016-05-19 09:01
Duplicate of https://github.com/zooniverse/Panoptes-Front-End/issues/2587.

**Closed by CKrawczyk** 2016-05-19 09:01 UTC
Labels: enhancement, feature request, stats
