### ISSUE TITLE
Add info on who last updated a thread and when to the index of thread in a  Talk discussion board

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1113] opened 2015-07-17 03:18 UTC
Right now only on the Talk front page do you know what's been updated but if I click on the science board for example, there is only information about who created the board, so I can't tell when threads have been active and which ones are really old conversations.  Talk 2.0 has this feature in it

Panoptes Talk 

![screen shot 2015-07-17 at 11 14 39 am](https://cloud.githubusercontent.com/assets/753325/8739997/67c01efe-2c75-11e5-9f54-96fc2f33abf6.png)

Ouroboros Talk 

![screen shot 2015-07-17 at 11 14 32 am](https://cloud.githubusercontent.com/assets/753325/8739993/59a61ff8-2c75-11e5-816c-fb80035a0ef5.png)

**Comment by DarrenMcRoy** [comment] 2015-07-17 03:22
Duplicate of #874 I think. Alex has just submitted a pull request to fix this I believe (see last post in #1106).

**Closed by DarrenMcRoy** 2015-07-17 03:22 UTC

**Comment by mschwamb** [comment] 2015-07-17 03:24
Thanks. I looked but coudln't find it.
