### ISSUE TITLE
Adding 'discipline' and 'other' tags is broken

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#4907] opened 2018-09-18 10:05 UTC
Tags won't save, and I see the following error in the console:

![image](https://user-images.githubusercontent.com/5321335/45680394-bc7f0500-bb32-11e8-8293-c7a04cd4b476.png)

**Comment by srallen** [comment] 2018-09-18 12:27
Likely duplicate of #4801

**Closed** 2018-09-24 16:07 UTC
