### ISSUE TITLE
Project Background Sizing Issues

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#3662] opened 2017-03-28 18:20 UTC
## Expected behavior
A project's background issue should size to fit the container.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
The background image for Arizona Batwatch is huge, and it only happens when going to the redirect URL (not when accessing the project from zooniverse/projects).

![screen shot 2017-03-28 at 1 18 50 pm](https://cloud.githubusercontent.com/assets/14099077/24420635/205a891e-13b9-11e7-8b56-48ca2bf1757f.png)

vs.

![screen shot 2017-03-28 at 1 19 25 pm](https://cloud.githubusercontent.com/assets/14099077/24420659/2e8d3f72-13b9-11e7-8874-9528f32aed20.png)

## Steps to replicate
Visit Arizona Batwatch redirect [link](arizonabatwatch.org) (arizonabatwatch.org).

## Additional information
This issue doesn't seem to appear on other projects with redirect URLs, which is peculiar.

- **Operating system:**
- **Browser:**
Chrome

**Comment by srallen** [comment] 2017-03-28 18:33
Possible duplicate of #3372

**Comment by eatyourgreens** [comment] 2017-03-28 18:47
And #2935 It's caused by `background-size: cover` in the CSS.

**Comment by wgranger** [comment] 2017-03-28 18:58
I'm not so sure this is a duplicate. Every project looks fine except for Arizona Batwatch and only when you go to the redirect.

**Comment by eatyourgreens** [comment] 2017-03-28 19:23
Could be something to do with applying that `background-size` rule to the whole page, instead of just the first section.

**Comment by mcbouslog** [comment] 2017-06-15 21:50
Closed with https://github.com/zooniverse/static/pull/22

**Closed by mcbouslog** 2017-06-15 21:50 UTC
Labels: help wanted
