### ISSUE TITLE
There's no way to exit out of the tutorial and help boxes

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4330] opened 2018-01-31 06:31 UTC
There's no x on the top of the right corner for the help text and the tutorial. So now you can't exit out of the tutorial if you want to. You have to skip to the end and hit 'let's go'. Same thing for the help text, you have to scroll all the way down to 'close' for it to close. 

<img width="1280" alt="screen shot 2018-01-30 at 8 17 00 pm" src="https://user-images.githubusercontent.com/753325/35608249-5a15a3ec-05fc-11e8-8d72-2c31fd7f6cb4.png">

<img width="1280" alt="screen shot 2018-01-30 at 8 17 26 pm" src="https://user-images.githubusercontent.com/753325/35608262-6545524e-05fc-11e8-8ff5-9cb7d204ffc7.png">

If you scroll down on the website, then the 'x' on the top right pops up. Like to here:

<img width="1280" alt="screen shot 2018-01-30 at 8 28 46 pm" src="https://user-images.githubusercontent.com/753325/35608269-78ca1426-05fc-11e8-9b9f-9ad5a2285228.png">

then there's the 'x'

<img width="1280" alt="screen shot 2018-01-30 at 8 28 50 pm" src="https://user-images.githubusercontent.com/753325/35608277-82689fe8-05fc-11e8-8e7a-e5e35c9e9864.png">

<img width="1280" alt="screen shot 2018-01-30 at 8 29 07 pm" src="https://user-images.githubusercontent.com/753325/35608281-85a57f5a-05fc-11e8-9f2b-71f9b415bb9a.png">

I get the same behavior on the latest versions of mac firefox and chrome

**Comment by eatyourgreens** [comment] 2018-01-31 11:00
I don't think the Help box has ever had an `x` button to close it. Looks like the close button for the tutorial is being hidden behind the project navigation. Maybe related to changes that @simoneduca pushed recently? I'm not sure.

**Comment by eatyourgreens** [comment] 2018-01-31 11:58
After a bit of digging around in the code, the problem is `z-index: 20` in the site navigation CSS: https://github.com/zooniverse/Panoptes-Front-End/blob/cd079d5aa4a0349cab8009ff4215a1fcf3c82261/css/site-nav.styl#L8

**Comment by simoneduca** [comment] 2018-01-31 13:25
Thanks @eatyourgreens, perhaps @srallen knows why that was introduced? Can we do without it?

**Comment by mschwamb** [comment] 2018-01-31 14:54
help box does have an 'x' if you do the weird trick of scrolling down in the browser and then hit the help button the x appears.If you hit the help box button without scrolling no 'x' as in the screen grab above

here's when I scroll and hit the help button, the 'x' for the help box appears

<img width="1135" alt="screen shot 2018-01-31 at 4 52 54 am" src="https://user-images.githubusercontent.com/753325/35629477-d19d7430-0642-11e8-9085-1506a4f52d9e.png">

**Comment by srallen** [comment] 2018-01-31 15:12
I'm not sure why the z-index was increased other than it appears that the new project nav also has a high z-index, so perhaps it was added to keep the main nav at the same z-index of the new project nav: https://github.com/zooniverse/Panoptes-Front-End/pull/4218/files
I didn't do the primary development of it, but I can roll in a fix with #4322

**Comment by mcbouslog** [comment] 2018-02-01 21:39
Closing as #4322 should fix.

**Closed by mcbouslog** 2018-02-01 21:39 UTC
Labels: help wanted
