### ISSUE TITLE
Collections, User-Collection's-Page, Collection's-Counter, Contributors.

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#2460] opened 2016-04-16 22:44 UTC
The collection's counter, on a user-collection's-page, also counts the number of assigned users (contributors/viewers).

Expected: Collection's counter showing (only counting) the number of collection's on the user-collections's page.

(*for those collection's the viewer has permission. cq: this is as expected.*)

*edited for more clarity, I hope.*

Local stuff: Chrome, Desktop, Windows, 1024x768.

_\*Unsubscribed\*_

**Comment by camallen** [comment] 2016-04-18 09:38
@MvGulik i'm pretty confused about what the problem is.

If this is a bug report / issue can you outline what the current vs the expected behaviour is. Bonus points if you can provide screen shots that point out the issue too, https://github.com/zooniverse/Panoptes-Front-End/blob/master/CONTRIBUTING.md

**Comment by MvGulik** [comment] 2016-04-18 16:06
Hope this will do the trick.
![image](https://cloud.githubusercontent.com/assets/666868/14610648/18de26fc-058f-11e6-9245-b0cd09b68c91.png)

Note: That 5 might just be an all-collectors count here. As every collection also has its owner as  collaborator. (*cq: 5 might be the result of using the wrong data field [all contributors]. Just speculating here, ignore it if its not making any sense.*)

**Comment by MvGulik** [comment] 2016-04-18 18:46
[offtopic] (*just to balance things out*)
>https://github.com/zooniverse/Panoptes-Front-End/blob/master/CONTRIBUTING.md

Yes, I know. But that's not the whole story I think.

Viewpoint from the other side: http://sifterapp.com/academy/essays/responding-to-bug-reports/
[/offtopic]

Note: I generally never turn down a question. Which, I think/hope, should work fine.

**Comment by camallen** [comment] 2016-04-19 11:51
@MvGulik thanks very much for the detailed response. That screen shot is very useful, this is a bug in the collections api response, it's not doing a distinct query, see https://github.com/zooniverse/Panoptes/issues/1774

**Comment by MvGulik** [comment] 2016-04-23 22:21
Thought I found something new, but realized (*after the image was almost done*) its probably a side effect of the currently used subject counter/counting.

Not to let the image go to wast.
![image](https://cloud.githubusercontent.com/assets/666868/14764216/670f7f54-09b0-11e6-9a9a-d651188d25cb.png)

Two side effects:
1 - Less than, the default 12, subjects on page 1.
2 - Same subject on page 1 and 2.

No collection subjects where missing/skipped, so minor side effect at best.

**Comment by camallen** [comment] 2016-06-14 10:11
This should be fixed, please re-open (and provide a URL for testing) if not.

**Closed by camallen** 2016-06-14 10:11 UTC
Labels: collections
