### ISSUE TITLE
New talk comment is indented in new talk, which could be confusing

### ISSUE THREAD

**Issue by crowston** [zooniverse/Panoptes-Front-End#1852] opened 2015-10-23 15:49 UTC
In the new talk (e.g., Fossil Finder), the box for a new comment is indented compared to the existing comments, which might confuse a user into believing that the new comment is a reply to the previous comment rather than just being added to the list of comments.

**Comment by crowston** [comment] 2015-10-23 15:56
Screen shot:
![untitled](https://cloud.githubusercontent.com/assets/1709163/10698065/0cbab4ce-797d-11e5-8ff0-56438ab27bb0.gif)

**Comment by aweiksnar** [comment] 2015-10-23 16:05
Duplicate of #1776

**Closed by aweiksnar** 2015-10-23 16:05 UTC
