### ISSUE TITLE
Talk Comments cannot be more than 10000 characters?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2365] opened 2016-03-31 21:11 UTC
Maybe @parrish would know the answer? 

We hit this on Comet Hunters Talk. One of the advanced volunteers is making lists helping to vet comet candidates and identify blends with background stars that make it look like the asteroid has a tail.  Originally the volunteer was editing one comment each time they reviewed a new candidate and looked for additional repeat images of the asteroid on Comet Hunters Talk. 

The volunteer claims they had to post in multiple comments, because comments cannot be more than 10,000 characters.  If that's true, could we add in a character count so that people know when they need to split into multiple comments.

**Comment by trouille** [comment] 2016-04-01 03:05
OldWeather whaling mods recently brought up this 10K character limit in a call. They've also found it limiting/inconvenient.

**Comment by mschwamb** [comment] 2016-04-01 03:09
I've find the limit fine and none of the mods on my two projects have mentioned an issues about this, but I've never hit. This is the first time a volunteer has mentioned this to me.  I think it helps promote reasonable length posts, but having a character counter on the box to make the writer aware would be helpful.

**Comment by parrish** [comment] 2016-04-01 17:59
Yeah... It's a validation defined in the front end [here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/lib/comment-validations.coffee).

I'm hesitant to change it since it's definitely an edge case (0.07% even come close).  Here's what the histogram looks like for comment lengths:

| length range | count |
|----|----|
| [1,1111) | 91414 |
| [1111,2220) | 1091 |
| [2221,3281) | 233 |
| [3343,4423) | 64 |
| [4570,5517) | 24 |
| [5575,6644) | 29 |
| [6721,7765) | 18 |
| [7970,8878) | 11 |
| [8881,9944) | 73 |
| [9989,9990) | 1 |

I'm going to close this for now since it's working as intended.  I also don't think a character limit countdown is necessary either.  Splitting a huge post into multiple comments is probably a good thing.

**Closed by parrish** 2016-04-01 17:59 UTC
Labels: feature request, question, talk

**Comment by mschwamb** [comment] 2016-04-01 19:09
@parrish Sounds like a reasonable error upon submission comes back. Maybe there should be a line the Talk commenting help box to mention the limit? If you think that's a good idea and can point to me to where I need to make the change I can do a pull request for the development team's consideration.
