### ISSUE TITLE
Top Recently Launched Projects on the Project Page Move Around in Order

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2503] opened 2016-04-27 15:32 UTC
I noticed when I've showed people the new project page recently that the top panoptes ones keep changing on the default filters when you go to the project page. I've kept some screenshots to post in a ticket in case it helps. 

2016-04-27 at 10.50.43 PM local time in Taiwan
<img width="1110" alt="screen shot 2016-04-27 at 10 50 43 pm" src="https://cloud.githubusercontent.com/assets/753325/14857640/a2656f56-0ccf-11e6-991f-3061232d88bc.png">

2016-04-26 at 10.49.04 PM local time in Taiwan

<img width="1144" alt="screen shot 2016-04-26 at 10 49 04 pm" src="https://cloud.githubusercontent.com/assets/753325/14857666/b89eefb8-0ccf-11e6-8a22-d14c9e9426d9.png">

 2016-04-26 at 3.22.38 PM local time in Taiwan
<img width="1106" alt="screen shot 2016-04-26 at 3 22 38 pm" src="https://cloud.githubusercontent.com/assets/753325/14857699/d1599440-0ccf-11e6-9abf-41f0ee0aecfb.png">

2016-04-26 at 1.18.34 AM local time in Taiwan

<img width="1125" alt="screen shot 2016-04-26 at 1 18 34 am" src="https://cloud.githubusercontent.com/assets/753325/14857812/2bcf2f8e-0cd0-11e6-9b59-9a4d053663aa.png">

**Comment by alexbfree** [comment] 2016-04-27 16:15
Hah! That would explain what I observed here https://zooniverse.slack.com/archives/dev/p1461585557000059 . Maybe I wasn't imagining it after all!

**Comment by mschwamb** [comment] 2016-04-27 16:21
I don't have access to slack, but it just changed again. Maybe it's actually reading when the most recent classification is?

2016-04-28 at 12.19.08 AM local time in Taiwan

<img width="1172" alt="screen shot 2016-04-28 at 12 19 08 am" src="https://cloud.githubusercontent.com/assets/753325/14859526/16837ebc-0cd7-11e6-8aef-4a88537a8694.png">

**Comment by alexbfree** [comment] 2016-04-27 16:24
Oh sorry! It was basically just me saying 
"I just noticed that Pulsar Hunters is showing up as our “Most Recently Launched” project in the projects page - can we do something about this".
When I went back later to check, it was no longer at the front.

I don't think it can be most recent classification, or why would a finished project (Pulsar Hunters) keep coming at the top.

I wonder if it's doing something odd like ordering by time of day, instead of date+time of day. definitely seems like a bug!

**Comment by alexbfree** [comment] 2016-04-27 16:25
Might be a back-end issue rather than a front-end one, but we can probably diagnose at the front end.

**Comment by amyrebecca** [comment] 2016-04-27 17:03
It's possible that the sort algorithm we're using just isn't stable.

**Comment by alexbfree** [comment] 2016-04-27 17:11
I just had to look up what "stable" means in this context > https://en.wikipedia.org/wiki/Sorting_algorithm#Stability

**Comment by camallen** [comment] 2016-04-27 18:03
I can't reproduce this, it's using this query `https://www.zooniverse.org/api/projects?page=1&sort=-launch_date&launch_approved=true&cards=true&include=avatar` that should be returning a stable sort on the `launch_date` field (if it's been set). 

@mschwamb i noticed the total count changes (49 -> 48) from the first to second image, maybe a lead there. It'd be nice to have the URL and selected disciplines  in the images as well.

**Comment by eatyourgreens** [comment] 2016-04-27 21:11
@camallen I've been able to reproduce this by leaving zooniverse.org/projects open in a browser for a couple of hours and refreshing the page.

**Comment by camallen** [comment] 2016-04-27 21:14
thanks @eatyourgreens, hours? Maybe a query cache thing then, perhaps because there are empty `launch_dates`, will have a look.

**Comment by mschwamb** [comment] 2016-04-27 22:08
@camallen in case it's helpful taken at 2016-04-28 at 6 04 47 am local time in Taiwan

to show the url and selected discipline:

<img width="1190" alt="screen shot 2016-04-28 at 6 04 47 am" src="https://cloud.githubusercontent.com/assets/753325/14869655/604fde84-0d07-11e6-9a2c-ebf4725f4679.png">

and a screen capture of the full page:

![fireshot capture 18 - projects zooniverse - https___www zooniverse org_projects](https://cloud.githubusercontent.com/assets/753325/14869676/838b6242-0d07-11e6-9b4c-84d0607120ea.png)

**Comment by camallen** [comment] 2016-04-27 22:11
Yep seems to be a database query cache issue. The `launch_dates` are missing for a set of projects (the ones that are changing), linked to https://github.com/zooniverse/Panoptes/issues/1765

I'll be setting those manually and once the above is fixed it'll happen automatically so the sort order won't change without data changes.

**Comment by camallen** [comment] 2016-04-27 22:40
This should be fixed now, re-open / comment if not.

**Comment by CKrawczyk** [comment] 2016-05-17 13:46
The `launch_date` for Computer Vision: Serengeti and Snapshot Wisconsin are both `null` leading to the two projects currently showing up in the wrong order when the project list is sorted by launch date.

**Comment by alexbfree** [comment] 2016-05-17 13:50
Well spotted @CKrawczyk 

@camallen how is launch date supposed to get set? How did it become null?
audit log looks ok, https://www.zooniverse.org/admin/project_status/alexbfree/computer-vision-serengeti
`Grant Miller changed launch_approved from false to true 7 days ago`

**Comment by camallen** [comment] 2016-05-17 14:11
@alexbfree https://github.com/zooniverse/Panoptes/issues/1765

launch dates are manual now - anything that get launched needs one of us to set it up till we fix the above issue. i've updated manually for now.

**Closed by camallen** 2016-05-17 14:11 UTC
Labels: bug, projects page

**Comment by alexbfree** [comment] 2016-05-17 14:55
@camallen is it only settable via the DB?

Maybe we could add a feature to admin project status page, so that it can be set there... or even set automatically when you set launch_approved
