### ISSUE TITLE
I've marked my collaborators and fellow scientists but they can't see my project

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#193] opened 2015-04-14 16:47 UTC
http://demo.zooniverse.org/panoptes-front-end/workflow-editor/#/projects/brooke/Galaxy+Zoo+Bar+Lengths/

Even if they go to Labs -- even after clearing their cache -- they can't view this project. Have currently added zookeeper and mrniaboc as collaborators.

**Comment by camallen** [comment] 2015-04-15 09:16
I think the only projects that show up in labs currently are the ones you actually own. As a workaround you can share the link directly or they can find the project on the index page (by clicking projects in the top left).

**Comment by brian-c** [comment] 2015-04-15 10:15
@camallen is there a quick way to get any projects in which the current user has a role?

Should I maybe re-title "collaborator" to "co-owner" in the client, since the permissions are basically the same?

**Comment by camallen** [comment] 2015-04-15 10:18
No - we've only got the owner fillters end point (i.e. projects a user explicitly owns). We could override this end point to return projects the user has similar roles on, like collab (co-owner) or we could add another endpoint for retrieving projects that a user has collab like roles for projects they don't own.

**Comment by vrooje** [comment] 2015-04-15 10:25
Yesterday neither Grant nor Chris could access the project even with the link; I've since added Cam and Kyle (willett on panoptes); and with both I also ticked the Tester box. Both can see the project via the link.  Is that a bug or a feature?

**Comment by camallen** [comment] 2015-04-15 10:28
Scientists, testers, translators, collaborators and moderators should all be able to see the see and list the project. It'd be nice to reproduce this to see what's going on.

**Comment by vrooje** [comment] 2015-04-15 15:19
rjsmethurst is currently having this problem (added as collaborator, scientist, tester)

**Comment by brian-c** [comment] 2015-04-15 15:33
@vrooje I just deployed a workaround for now: There's now a "Private" checkbox on the edit-project-details page. Uncheck it and everybody'll be able to see the project.

**Comment by camallen** [comment] 2015-04-15 16:22
I assume this is a cache issue with projects listing.
 
rjsmethurst does the direct URL work for you? Does it show up on the projects listing page if you try cmd+shift+r ?

**Comment by rjsmethurst** [comment] 2015-04-15 16:40
![image](https://cloud.githubusercontent.com/assets/5754386/7164156/5eb4e07e-e396-11e4-965e-6f23b0c0f899.png)

That's what happens with direct URL. Doesn't show up on the projects screen either

**Comment by brian-c** [comment] 2015-04-15 16:42
@rjsmethurst What's the URL you're on? You should be getting something like this:

![screen shot 2015-04-15 at 5 41 38 pm](https://cloud.githubusercontent.com/assets/464389/7164221/c1231a8c-e396-11e4-9a53-6cc7d2c32277.png)

**Comment by rjsmethurst** [comment] 2015-04-15 16:43
![image](https://cloud.githubusercontent.com/assets/5754386/7164254/f3dccaa4-e396-11e4-8ff1-b4f6e109628e.png)
that look right to you?

**Comment by brian-c** [comment] 2015-04-15 16:44
Lose the trailing slash.

**Comment by rjsmethurst** [comment] 2015-04-15 16:48
Sorted. And I can also see it now on the projects list

**Comment by brian-c** [comment] 2015-04-16 12:29
@vrooje @rjsmethurst Is this a solved problem more generally? I know we were having trouble the other day, was that also just due to having the wrong URL?

**Comment by vrooje** [comment] 2015-04-18 13:40
Not sure - I haven't tested changing just the URL versus having the right category ticked etc. Want me to add you to my project so we can test it?

**Comment by vrooje** [comment] 2015-04-23 21:28
Don't know, but quite possibly; have just noticed the first link I sent to
Grant had the trailing slash and the second didn't, so perhaps it was just
that after all. Possibly we could close this and if we rediscover it I'll
re-open it? (not sure if that's good practice.)

**Comment by chrissnyder** [comment] 2015-06-16 17:09
It might be out of date, but should confirm it's solved before closing.

**Comment by brian-c** [comment] 2015-06-22 14:21
I believe this was an issue with trailing slashes, which redirect now. Re-open if there're still problems.

**Closed by brian-c** 2015-06-22 14:21 UTC
Labels: bug
