### ISSUE TITLE
Looks like if you delete a subject from your subject set  it messes with collections and possibly Talk?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#886] opened 2015-06-29 21:29 UTC
This might be both the backend and front end. I deleted a subset set of images we were testing with and I noticed in my favorites collection there are subjects from that set that now show up blank and don't load. Should subject sets every really be 'deleted' so that if someone has already commented on them in Talk or collected them they don't end up with this:

![screen shot 2015-06-30 at 5 25 14 am](https://cloud.githubusercontent.com/assets/753325/8418946/ea33d17c-1ee8-11e5-8e90-5ca4d63da0c5.png)

I'm not sure how often this would happen

**Comment by chrissnyder** [comment] 2015-07-09 20:29
@edpaget I know this has been discussed elsewhere, but has the behavior here changed in the last 10 days?

Deleting a subject from the front end doesn't seem to make a difference to the collection (it just deletes the set_member_subject link I think). Deleting a subject via the API deleting the subject from the collection as well (which seems correct).

**Comment by camallen** [comment] 2015-07-10 10:33
@chrissnyder did you actually delete a subject via `DELETE /api/subjects/X`?

**Comment by chrissnyder** [comment] 2015-07-10 10:36
I did `zooAPI.type('subjects').get(subject_id).delete()`, which hits that route

**Comment by camallen** [comment] 2015-07-10 10:45
Yeah - so deleteing that subject will leave an orphaned record in collections. However you're right in that removing a subject set will only remove the links to the subject (set_member_subject).

@mschwamb - can you provide some links to the collection that is problematic, I can only see your swiss cheese terrain one.

**Comment by mschwamb** [comment] 2015-07-10 12:38
It's a favorites collection. I added you both @camallen and @chrissnyder to it as collaborators so you should be able to see it now

**Comment by camallen** [comment] 2015-07-10 12:52
Thanks, so the subject is still there, however both those images are 0 bytes in size. 

Makes me wonder what happened here. I'm going to test something out will report back.

**Comment by chrissnyder** [comment] 2015-07-10 12:54
To be clear, my tests from the front end successfully deletes the subject
from the collection. Maybe this error was from before we deleted subjects
after failed uploads?

**Comment by mschwamb** [comment] 2015-07-10 13:03
Question related, if you delete a subject from a subject_set should it delete the subject from the collection at all?

**Comment by mschwamb** [comment] 2015-07-10 13:04
Just thinking about if I collected something and the science team deletes the subject because they need to make space, and I came back to my collection. I'd be confused why I can't find my favorite Zooniverse subject. Maybe I'm misunderstanding how collections and deleting subjects work.

**Comment by camallen** [comment] 2015-07-10 14:43
OK - i just tested manually by adding a subject to a collection and then removed the subject set. Subject still shows up in collection so I think this is actually another issue. Perhaps bad upload and no delete like you said @chrissnyder, I'm not sure though.

I'm going to close this issue as I can't reproduce, please re-open if you can reproduce this issue.

**Closed by camallen** 2015-07-10 14:43 UTC
Labels: bug
