### ISSUE TITLE
Autosaving kind of confusing

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#581] opened 2015-06-17 17:47 UTC
It looks like there is some new autosaving feature, but I'm unclear when its saved and when its not especially in the workflow editor - thought I provide the feedback in case its useful

**Comment by brian-c** [comment] 2015-06-17 17:56
The field turns yellow when while saving, green if it was successful, and red if it failed. Maybe "Saving", "Saved", and "Error" labels are necessary here.

**Comment by mschwamb** [comment] 2015-06-17 18:02
I only noticed that once on the science page but the science page label text had green around so I wasn't sure what it was doing but guessed maybe that was it, but sometimes I clicked away before that happened and my changes were saved. 

I  hard time finding that color change for the help in the workflow. 

Maybe a more explicit banner on the top of the browser - like 'content saved'? not sure if that's possible. 

 Personally I liked the option of explicitly saving by hitting a button. Perhaps  the dual option like wordpress has, where it autosaves, but you can also  hit the save button?

**Comment by alexbfree** [comment] 2016-03-11 15:53
It's especially confusing when you have a text box that's too long - it turns red but it's very unclear what the problem is and also without a character count, very hard to fix without using an external character count tool.

**Comment by srallen** [comment] 2016-12-21 21:23
Closing in favor of #2895

**Closed by srallen** 2016-12-21 21:23 UTC
Labels: design
