### ISSUE TITLE
Preview of uploaded subjects doesn't seem to be working

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#1629] opened 2015-09-24 08:38 UTC
When I click the preview icon, I get this forever...
![screenshot](https://cloud.githubusercontent.com/assets/1473244/10068849/cd08eba0-629f-11e5-96ae-b37bbebc63b6.png)

Javascript console shows 
```
GET https://zooniverse-static.s3.amazonaws.com/panoptes-uploads.zooniverse.org/…phOpelBMwUW7je%2BISYF0RN1%2F8GMdS1CQvadSti8QiGSrhNlNJ72N2%2F8g%2BdeOsAU%3D 403 (Forbidden)
```

**Comment by camallen** [comment] 2015-09-24 08:47
@alexbfree reload the page, it's using the PUT url that it uploads to instead of the get after upload. we probably need an auto refresh on these resources after put success.

**Comment by mschwamb** [comment] 2015-09-24 10:35
duplicate of #981 I believe

**Closed** 2015-09-24 10:36 UTC
Labels: bug, project builder
