### ISSUE TITLE
Points cannot be added within a previously placed polygon

### ISSUE THREAD

**Issue by hallba** [zooniverse/Panoptes-Front-End#4165] opened 2017-11-19 22:25 UTC
## Expected behavior

The workflow consists of first drawing a polygon, then placing points within the polygon.

https://www.zooniverse.org/projects/hallben/send-in-the-clones

## Current behavior

Points cannot be placed within polygons. If an ellipse is used instead of a polygon, points can be placed successfully.

## Steps to replicate

Run the workflow in https://www.zooniverse.org/projects/hallben/send-in-the-clones

## Additional information

- **Operating system:**
Win10
- **Browser:**
Chrome

**Comment by eatyourgreens** [comment] 2017-11-20 11:42
Caused by #4076, I think.

**Comment by simoneduca** [comment] 2017-11-20 12:02
I'll have a look.

**Comment by eatyourgreens** [comment] 2017-11-21 16:39
Hopefully fixed by #4171

**Closed** 2017-11-21 16:57 UTC
Labels: bug
