### ISSUE TITLE
Inactive workflows shouldn't be able to be set as default workflows

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#4789] opened 2018-08-15 16:00 UTC
Just ran into this problem when trying a new beta project. They had deactivated the default workflow and left two others active. No classifications were loading. Presumably because the inactive workflow was still set as the default?

**Comment by eatyourgreens** [comment] 2018-08-15 16:02
Duplicate of #4431?

**Comment by mrniaboc** [comment] 2018-08-15 16:08
Yes. Sorry :(

**Comment by eatyourgreens** [comment] 2018-08-20 21:50
I think PELIcams have got this problem too. https://www.zooniverse.org/projects/jaimibutler/pelicams/talk/1914/713926?comment=1189223

**Closed** 2018-08-21 15:44 UTC
Labels: bug, help wanted
