### ISSUE TITLE
A project is removed or made private, but still shows up in the list of projects?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#619] opened 2015-06-19 09:52 UTC
Manuscript adventure has a card on the projects list but if you click it you get 'Error: Couldn't find project Simoneduca/manuscript-adventure'

**Comment by camallen** [comment] 2015-06-19 09:53
@mschwamb duplicate of #604, got a fix coming through soon.

**Closed by camallen** 2015-06-19 09:53 UTC
