### ISSUE TITLE
Workflow editor: No new task should be pre-defined

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#408] opened 2015-05-25 21:43 UTC
In demonstrations to newcomers to Panoptes, the double-column layout of the workflow editor seemed a bit confusing: it wasn't clear that the left column is the summary side and the right column is the task details side. 

There are probably many ways to indicate this with design, but one option is to *not* pre-populate the workflow with a question task, and have the right column load blank. Then when people make a new task, the right column will fill and the connection will be clear. If the "new task" buttons are made a bit more obvious too (#407) I think it will really help.

**Comment by aliburchard** [comment] 2015-05-28 21:00
Along the same lines of  #245.

**Comment by vrooje** [comment] 2015-06-04 14:46
definitely.

**Comment by chrissnyder** [comment] 2015-06-16 16:11
Duplicate of https://github.com/zooniverse/Panoptes-Front-End/issues/245

**Closed by chrissnyder** 2015-06-16 16:11 UTC
