### ISSUE TITLE
Talk: replies to top-level message opens reply box at bottom of page without scrolling the user down

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1189] opened 2015-07-22 17:47 UTC
If there are several messages in a discussion and I click 'reply' to one at the top, a reply box opens at the bottom of the discussion -- off my screen. When this first happened, I was totally confused and didn't understand why the 'reply' button wasn't working. Either the reply box should open directly under the message to which a user is replying, or the window should auto-scroll down to the bottom so the user can type into the reply box directly.

**Comment by DarrenMcRoy** [comment] 2015-07-22 17:57
I agree. Hitting the reply button should take you to the bottom of the page.

**Comment by mschwamb** [comment] 2015-07-22 22:25
duplicate of #999

**Closed** 2015-07-23 20:51 UTC
