### ISSUE TITLE
Gold-standard mode check-box doesn't get checked upon click.

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#4984] opened 2018-10-11 13:54 UTC
## Expected behavior
To do a gold standard classification for a project, there is a check-box next to the Done button that pops-up after clicking on a cog button. When I click on the check-box, it is supposed to get 'checked' and display I am doing a gold standard classification by adding a star into the Done button, and add a star together with 'Gold Standard mode text' just below.
When I want to cancel the Gold standard mode, I click on the cog button to uncheck the box and the check-box changes to an empty check-box.

## Current behavior
When I click on the check-box, nothing seems to happen. No matter how many times I click or how long I wait. After escaping the pop-up with the check-box, it doesn't show a star for gold classification. But when I choose any category and go back to the list of categories, it suddenly shows the results of checking the check-box = I see the start together with 'Gold standard mode' text. 
When I decide to cancel the Gold standard mode, no matter how many times I click on the check-box, it stays checked. Just after choosing any category and getting back to the list of categories, it suddenly shows the results of canceling the Gold standard mode.

Why is that a problem? It seems I haven't succeeded in setting the gold standard mode when I first choose the category and then try to set the gold standard mode. I realize it was a Gold standard after finishing my classification. That may be too late. The same when I manage to set the gold standard and then realize there may be more animals in the bush and decide not to do a gold standard but cannot uncheck the box. Then it is safer to leave the classification instead of trying one's luck and clicking on the Done button to see the results. (Unless you know you can see the results when you go to any category and back. But that took me a while to figure out.)

## Steps to replicate
I guess trying to check the box and then uncheck it? I'll try to test that on another device later today.

## Additional information
Happens on Western Shield Camera Watch (new data released today). Unable to test it elsewhere.

Screenshot of the browser console errors:
![ysh_screenshot_2018-10-11_15-46-43_gold_doesnt_check](https://user-images.githubusercontent.com/7211888/46808626-114a2000-cd6d-11e8-9d04-9fe61fe57dfb.png)

- **Operating system:**
Ubuntu
- **Browser:**
Chromium 69

**Comment by eatyourgreens** [comment] 2018-10-11 13:57
Duplicate of #4564, I think.

**Closed** 2018-10-15 15:30 UTC
