### ISSUE TITLE
Seabird Watch About 'team' page missing team members

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#5617] opened 2020-01-13 20:32 UTC
Context (which may or may not be relevant / the reason for the bug): in December, the owner of seabird watch unintentionally added a non-team member as a collaborator. The non team member changed the landing page. We then went in and unlinked all collaborators from the project while we tracked down the user, etc. Once we identified who had caused the trouble, we re-linked all known collaborators. But now the 'about' team page doesn't list anyone as expected in the right-hand column of the page, under 'team'. 

See https://zooniverse.slack.com/archives/C0DTP3L2K/p1576880012029000

## Expected behavior

Showing the listed owner + collaborators on the https://www.zooniverse.org/projects/penguintom79/seabirdwatch/about/team project

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

Not listing the owner + collaborators at https://www.zooniverse.org/projects/penguintom79/seabirdwatch/about/team

## Steps to replicate

Visit https://www.zooniverse.org/projects/penguintom79/seabirdwatch/about/team

## Additional information

Chrome and Safari, logged in and not logged in. 

- **Operating system:**
- **Browser:**

**Comment by camallen** [comment] 2020-01-14 16:53
This was caused by a deleted user still having a role on the project. The lab wouldn't let me delete the 'busted' role and the UI didn't handle the error when it couldn't find a deleted user for the existing role. 

I've manually fixed the data. Closing this issue for now but something to handle gracefully on the rebuild.

**Closed by camallen** 2020-01-14 16:53 UTC
Labels: bug
