### ISSUE TITLE
Clicking on links in the notifcations page give empty blank pages

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3279] opened 2016-11-25 17:25 UTC
Something is going on with the links:

My notifications page link tried to go to https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/84/135468?comment=236250 and it's blank

<img width="1095" alt="screen shot 2016-11-25 at 11 20 13 am" src="https://cloud.githubusercontent.com/assets/753325/20632223/9e5adb70-b301-11e6-9870-c69974cb5391.png">

If I click enter in the url address bar it reloads and then displays the content

<img width="1099" alt="screen shot 2016-11-25 at 11 24 58 am" src="https://cloud.githubusercontent.com/assets/753325/20632265/daa3b7dc-b301-11e6-96ff-291b3bc44660.png">

**Comment by mschwamb** [comment] 2016-11-25 17:25
related to #3259

**Comment by mschwamb** [comment] 2016-11-25 17:26
I'm on latest version of Firefox on mac

**Comment by MvGulik** [comment] 2016-11-27 05:33
###### _Local stuff: Chrome(49), Desktop, Windows(xp), 1024x768._

Seems a other page loading/timing thing.
The appending of the page-setting can fail on requested Talk-page.
This is for both when a page is opened in the same tab (*rare*), as being opened in a new tab (*often*).

**Comment by eatyourgreens** [comment] 2016-11-28 12:30
This seems to be caused by `@state.discussion` being [undefined here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/discussion.cjsx#L62) during `componentWillMount` for the `TalkDiscussion` component. It should be fixed by #3282

**Closed** 2016-11-28 15:25 UTC
Labels: bug
