### ISSUE TITLE
Project builder reporting zero subjects after uploading to a subject set

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#2124] opened 2016-01-19 11:46 UTC
![image](https://cloud.githubusercontent.com/assets/59547/12417739/0fe7663c-bea2-11e5-8f09-9950b31034f8.png)

After running a script to create a new subject set, and uploading 10 test subjects, I opened the subject set in the project builder. It lists the subjects, but says the set contains 0 subjects.

**Comment by simoneduca** [comment] 2016-01-19 12:43
I've seen this before, but it was momentary and changed to the correct number of subjects after a few seconds.

**Comment by eatyourgreens** [comment] 2016-01-19 14:26
Yeah, looks like there's a delay updating `set_member_subjects_count` on the subject set.

**Comment by srallen** [comment] 2016-01-19 17:12
Duplicate of #1128

**Comment by eatyourgreens** [comment] 2016-01-19 17:17
I'm not sure if this is the same as #1128 The 'This set contains 0 subjects' text appeared after refreshing the page.

**Comment by srallen** [comment] 2016-01-19 17:19
Oh, yeah, I see. This may be the cause of #1128 then, if there's a delay in that number updating on the subject set.

**Comment by camallen** [comment] 2016-01-19 17:22
So uploads linking the subjects to subject sets normally happens in batches, so in the api layer we just delay the job to count in the future (hopefully when all the batches are finished), see [here](https://github.com/zooniverse/Panoptes/blob/b81d2dbfa423d4c9020717ff879e435ec3e29be5/app/controllers/api/v1/subject_sets_controller.rb#L74).

Your seeing the delay between batch upload and the count worker running. Perhaps we need to message this better in the front end?

**Comment by mschwamb** [comment] 2016-01-24 13:34
I've definitely thought more than once that something went wrong with the upload since it has zero subjects in the count also I still get errors  uploading even in batches of 25 subjects being uploaded on a T1 line which might have something to do with the previous uploading finishing. Why not just get the uploading window/progress bar up until the counter is updated and everything is finished?

**Comment by alexbfree** [comment] 2016-03-11 12:28
Just encountered this myself and raised #2279 but closed as duplicate.

@camallen there is more to this than just a delay, since the pagination is able to correctly calculate the number of pages it must also be able to calculate the total number of subjects. It's really important that if we show a number to the user, it's accurate, as that's pretty much the only way to tell whether your upload worked.

**Comment by eatyourgreens** [comment] 2016-03-11 12:41
@alexbfree Here's the line that displays that count: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/subject-set.cjsx#L157 

Feel free to open a PR with a fix. Sounds like it's a small change from what you've said.

**Comment by camallen** [comment] 2016-03-14 11:24
@alexbfree the api is presenting the wrong information and it is actually just a delay your experiencing, and it does fix itself after 3 mins. Check the code i linked above if you want to figure out a better way of doing it. 

Agree it's not the greatest returning an incorrect count but it's better to be delayed and right than fast and wrong.

**Comment by mschwamb** [comment] 2016-03-14 11:34
What about keeping up the uploading message until after it updates in 3 minutes ? have it say processing or something like?

**Comment by camallen** [comment] 2016-03-14 11:41
yeah - or just increment the known counter for each upload client side?

**Comment by mschwamb** [comment] 2016-03-14 11:49
yeah. basically I use it to check that the full upload was successful and it's bit scary when you're like wait uploaded 500 images and the counter didn't change  and then you wonder if something went wrong even though it looked like a successful upload

**Comment by camallen** [comment] 2016-09-20 13:29
This should have been fixed by the recent counters work in the API.

**Closed by camallen** 2016-09-20 13:29 UTC
Labels: bug
