### ISSUE TITLE
Error messages are not displaying correctly

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/Panoptes-Front-End#6234] opened 2022-11-01 15:59 UTC
## Expected behavior
When trying to load a project I don't have permission to see, I should see an error message (either: "project not found", or "you don't have permission to view this resource", or similar).

## Current behavior
I see `[object Object]` in red text.

![Screen Shot 2022-11-01 at 10 52 53 AM](https://user-images.githubusercontent.com/2006101/199278643-6b0b692f-6c50-4dd9-b2ec-befaf2ad4f18.png)

See associated console errors:

![Screen Shot 2022-11-01 at 10 55 27 AM](https://user-images.githubusercontent.com/2006101/199278731-e018a0ff-d993-4e25-9995-e4491a53fb96.png)

## Steps to replicate
Try to navigate to a project builder / lab page where you are not a owner/collaborator.

## Additional information
Seems similar to reported behavior in #6232 -- likely due to same underlying problem?  An issue with error messages broadly in the app?

**Comment by eatyourgreens** [comment] 2022-11-01 16:11
Caused by version 4.2 of the API client, I think.

**Comment by eatyourgreens** [comment] 2022-11-01 16:41
This is caused by the changes in https://github.com/zooniverse/panoptes-javascript-client/pull/164. Looks like PFE expects the client to reject with an error, even when there's a valid response body from the API.

**Comment by eatyourgreens** [comment] 2022-11-01 16:51
https://github.com/zooniverse/panoptes-javascript-client/pull/175 should fix this. It'll need to be published as a patch to the API client, after the PR merges.

**Comment by eatyourgreens** [comment] 2022-11-01 17:13
There's also some code in the lab which isn't catching API errors properly here.
https://github.com/zooniverse/Panoptes-Front-End/blob/d9844accc8d2bbc0b8f8eeb6b12af83f1d9ae52d/app/pages/lab/project.jsx#L306-L312

**Comment by eatyourgreens** [comment] 2022-11-01 17:16
Weirdly, I do get the expected message when I navigate to a random project ID in the lab. I still think there are bugs in the API client and the project editor, I'm just not sure how to reproduce this.

<img width="818" alt="Error page saying 'You don't have permission to edit this project' for a randomly chosen project ID.'" src="https://user-images.githubusercontent.com/59547/199295338-02960a66-7290-4908-844c-bd210474958d.png">

**Comment by goplayoutside3** [comment] 2022-11-03 00:26
This is fixed on production - @eatyourgreens okay to close?

**Comment by eatyourgreens** [comment] 2022-11-03 07:02
@lcjohnso opened the issue so it's up to him, I suppose.

**Comment by eatyourgreens** [comment] 2022-11-03 11:29
I can't reproduce this any more on www.zooniverse.org.

**Closed by eatyourgreens** 2022-11-03 11:29 UTC
Labels: bug
