### ISSUE TITLE
New survey task image uploading behavior

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#2687] opened 2016-06-14 15:29 UTC
- [ ] Before uploading, make sure the image is no larger than 100KB. Skip and display an error if it is.
- [ ] At any given time, the UI should also list errors for images referenced in the workflow but missing from the workflow's media.
- [ ] If Delete all images, warnings about not having images don't return like they should

**Comment by mcbouslog** [comment] 2016-07-07 21:16
mentioning @trouille

**Comment by aliburchard** [comment] 2016-07-08 08:39
are these for subjects? our subject size limit is currently 600kb. every project currently live has subjects > 100kb...

**Comment by brian-c** [comment] 2016-07-08 19:44
@aliburchard this is for the survey task editor, where a couple dozen images might be loaded at the same time.

**Comment by aliburchard** [comment] 2016-07-10 21:23
So for the spot in the survey task where you upload reference/thumbnail photos and icons?

**Comment by rpmady** [comment] 2019-02-19 17:53
Hello, I'm on the Battling Birds project team and I just tried to upload new images to a survey task. There was a problem in which the image thumbnails were not appearing when trying to classify. So I deleted all the images and re-uploaded them. Now more image thumbanils are not appearing.

**Comment by trouille** [comment] 2019-02-19 20:20
@rpmady Could you post context info as well: your project you're working on, attach a few of the images that aren't uploading properly, and provide a few screenshots. 

A good way to test/hone in on what's causing trouble is to create a test workflow with a paired down version of your survey task, to test if it's specific images that aren't working, etc.

**Comment by rpmady** [comment] 2019-02-20 01:57
I'm working on Battling Birds. This survey task, with all of its images, has previously worked in another workflow.  I've attached 2 of the images not working properly as well as some screenshots of the problem. The images seem to be there, so when you click on the name of a species that doesn't have a picture, the picture is there.  


![problem_survey](https://user-images.githubusercontent.com/42630011/53060498-c497f380-3488-11e9-9441-b447d19f40ff.jpg)
![problem_survey2](https://user-images.githubusercontent.com/42630011/53060499-c497f380-3488-11e9-97d7-0de693b8d835.JPG)
![bhco 2](https://user-images.githubusercontent.com/42630011/53060486-b9dd5e80-3488-11e9-884c-fbaa63e9d282.jpg)
![bluejay](https://user-images.githubusercontent.com/42630011/53060489-be097c00-3488-11e9-9e2e-f8d8ee8097dd.jpg)

**Comment by rpmady** [comment] 2019-02-20 02:00
When I test the survey task in a workflow by itself, some of the images load, but still not most of them 
![problem_survey3](https://user-images.githubusercontent.com/42630011/53060692-64558180-3489-11e9-8598-25436e7a3598.JPG)

**Comment by camallen** [comment] 2019-02-21 13:39
Hi @rpmady - that issue was caused by a misconfiguration in one of our image services. We've fixed it and I've tested it on your worklfow so it should be working for you now.

I'm closing this again, please do report back here if there are still issues.

**Closed by camallen** 2019-02-21 13:39 UTC
Labels: project builder, refactor

**Comment by rpmady** [comment] 2019-02-21 18:15
Hi @camallen, thank you very much for looking into this and resolving it. I just tested out the workflow and the pictures are showing up now. Just did want to let you know they do take a moment to load (i.e. some pictures appear and others are blank and then appear).

**Comment by camallen** [comment] 2019-02-21 19:27
Thanks we know about this issue and are working on it. Those images will cache in your browser so you should only notice this "slow down" on the first page load. Thanks for letting us know :)
