### ISSUE TITLE
Talk: Add 'Continue to Classify' button

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#896] opened 2015-06-30 11:12 UTC
I felt a bit lost after I added a comment to a subject: no obvious links/buttons to point me to some actions.
![screen shot 2015-06-30 at 12 02 47](https://cloud.githubusercontent.com/assets/8989606/8429494/0af14462-1f20-11e5-9c53-63bb3d21ca7c.png)
)
I ended up clicking on the 'Notes' breadcrumb at the top, but even then there was obvious actions to be taken, except from adding a new discussion.

![screen shot 2015-06-30 at 12 10 42](https://cloud.githubusercontent.com/assets/8989606/8429601/1aae1708-1f21-11e5-918b-389b92e0b077.png)

I think adding a 'Continue to Classify' button on both pages would be helpful.

**Comment by edpaget** [comment] 2015-06-30 12:52
We should just keep the project top bar around on all pages. It has a big link that says classify. Which makes more sense to me than having two buttons to do it.

**Comment by simoneduca** [comment] 2015-06-30 12:56
@edpaget Fair enough. However, when I thought of clicking 'Classify' in the main menu, I felt my workflow was being interrupted. A bit like hitting 'home' on a website when you can't find what you want on the current page. But maybe it's just me.

**Comment by mschwamb** [comment] 2015-06-30 13:11
FWIW, I have the same sentiment in #863

**Comment by simoneduca** [comment] 2015-06-30 13:18
@mschwamb Sorry I missed that. Thanks for referencing it.

**Comment by aweiksnar** [comment] 2015-06-30 14:52
Duplicate of #863

**Closed by aweiksnar** 2015-06-30 14:52 UTC
Labels: duplicate, enhancement, talk, ui/ux
