### ISSUE TITLE
having active users list show up on instances there's a talk side bar

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1017] opened 2015-07-09 13:07 UTC
maybe this isn't the permanent home for this feature, but it would be nice if the active user list showed up on this side bar as well 

![screen shot 2015-07-09 at 9 06 29 pm](https://cloud.githubusercontent.com/assets/753325/8595887/806cb8b0-267e-11e5-9210-1f8836dfd6b9.png)

**Comment by mschwamb** [comment] 2015-07-25 00:19
Also if the hastags could show up as well on the side bar everywhere - I think that would be extremely helpful

**Comment by vrooje** [comment] 2015-07-27 11:29
+1
and +1 :)

**Comment by mschwamb** [comment] 2015-10-07 23:42
@aweiksnar would it be easy to add the active users and popular hashtags to the Talk side bar on the Talk side bar that shows when you click on the board like [here](https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/10/)?

 I'm finding I have a hard time remember what the evolved hashtag for a feature is and having it somewhere not just on the Talk front page would help. I also love the list of active users and so if it could show up there too, it would give the feeling there are other people around. 

I ask because the toolbar looks to be exactly the same as the one on the main Talk page in design that this seemed maybe easy to replicate.

**Comment by parrish** [comment] 2015-10-14 17:53
Duplicate of #892

**Closed by parrish** 2015-10-14 17:53 UTC
Labels: feature request, talk

**Comment by mschwamb** [comment] 2015-10-14 21:12
@parrish Well slightly different I think. Currently the side bar that exists on the boards doesn't show active users or hashtags. The other ticket is asking for the side bar to be everywhere which I imagine is more work moving things around. Since I thought this was an easy change to make on the side bars of the discussion boards I made it a different ticket.

**Comment by mschwamb** [comment] 2015-10-14 21:13
@parrish Likes look you made it all standard which is awesome. thanks
