### ISSUE TITLE
Subject count reflects total subjects, not those assigned to the currently active workflow.

### ISSUE THREAD

**Issue by khufkens** [zooniverse/Panoptes-Front-End#2224] opened 2016-02-22 22:01 UTC
The subject count gets updated (increases) due to new subject uploads, although they are not yet attached to the project.

This can confuse people about the state of the project. Since no new data will actually show up.

The count should reflect the actively used subject sets, not the total uploaded count.

**Comment by camallen** [comment] 2016-02-22 22:21
duplicate of https://github.com/zooniverse/Panoptes/issues/1482

**Closed by camallen** 2016-02-22 22:21 UTC
