### ISSUE TITLE
Some private message threads don't have listed who the thread is from

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4762] opened 2018-07-30 23:34 UTC
Laura from Planet Four: Ridges science team is having a hard time with this and mentioned this behavior to me.  I'm not sure why some private message threads have usernames and some don't.  See screenshot. 

<img width="1047" alt="screen shot 2018-07-30 at 1 32 28 pm" src="https://user-images.githubusercontent.com/753325/43429086-4358cd70-93fd-11e8-9395-e1ba9a72c343.png">

**Comment by adammcmaster** [comment] 2018-07-31 06:54
This is probably due to #4325

**Comment by eatyourgreens** [comment] 2018-07-31 07:30
@mschwamb has the sender archived the conversation on their side?

**Comment by eatyourgreens** [comment] 2018-07-31 07:44
Could be a duplicate of #3934.

**Comment by camallen** [comment] 2018-07-31 09:31
This is because the other party has deleted the conversation on their side. 

If one side of the private conversation deletes the message and the client requests the conversation details via `https://talk.zooniverse.org/conversations?user_id=1058671&page_size=10&sort=-updated_at&include=users` their is only 1 linked for that conversation. 

Moving from the client away from the `include=users` to fetch the users via the `conversation.participant_ids` would allow the client to know the linked users and the behaviour of the app to be more like email. If we need to signal “deleted on other side” state we can use both to determine which user has deleted their link to the conversation.

**Closed** 2018-07-31 15:52 UTC
