### ISSUE TITLE
Improvement for modal-form modal-dialog

### ISSUE THREAD

**Issue by mbiesiad** [zooniverse/Panoptes-Front-End#6098] opened 2022-02-17 15:14 UTC
## Expected behavior
With a smaller size, it still looks fine.

## Current behavior
After making smaller window of the browser, the modal-form modal-dialog looks bad.

## Steps to replicate
Go to the "Build a Project" (as a logged in user): https://www.zooniverse.org/lab
Click on the "Create a new project" button.
Make a browser window smaller. See the results.

Screenshot (correct view):
![image](https://user-images.githubusercontent.com/18367606/154510529-010a7df0-0e25-4c94-befe-c5c287b58c1f.png)

Screenshots (incorrect view):
![image](https://user-images.githubusercontent.com/18367606/154510645-09c8e73a-c18e-408b-8f39-1c79d937143e.png)

![image](https://user-images.githubusercontent.com/18367606/154510719-0c0558d7-4972-48c8-beb2-d5f6c0f73f4f.png)

Best wishes,
Michal

**Comment by shaunanoordin** [comment] 2022-08-08 16:49
@mbiesiad Thank you very much for this report. We plan to tackle this layout issue within this week, as part of the Zooniverse Oxford Summer Internship programme. I appreciate your detailed writing and screenshots, as this is very very helpful.

@MaysaB I'm assigning you this bug so we can walk through it tomorrow (Tue 9 Aug)

Here's what to expect:
1. set up Panoptes-Front-End and get it running on localhost 
2. (optional, recommended) set up local.zooniverse.org on your `hosts` file
3. replicate the problem on localhost
4. use your browser's web inspector to examine the issue (because it's a CSS problem)
5. figure out where in the Panoptes-Front-End code the problem is happening
6. try some solutions on localhost
7. examine your solution on multiple browsers & devices
8. create a PR, get it reviewed, get it merged
9. (bonus) deploy

**Comment by MaysaB** [comment] 2022-08-09 10:21
Acknowledged - working on this now.

**Closed** 2022-08-10 15:37 UTC
Labels: bug, ui

**Comment by MaysaB** [comment] 2022-08-10 16:00
Hello @mbiesiad,

The issue has been fixed and deployed and should be visible on the Zooniverse website. 
Thank you for bringing this issue to our attention.

**Comment by mbiesiad** [comment] 2022-08-10 19:13
Hello @shaunanoordin and @MaysaB My pleasure! Thank you for your updates and info here. Checked - works fine now. ✔ Great work! 🎉 Best wishes,
