### ISSUE TITLE
moving between pages of project listing 

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes-Front-End#1162] opened 2015-07-21 15:58 UTC
when I'm on page one of the project listings and I click on page 2, it would be nice if the page would automatically be at the top.

**Comment by chrissnyder** [comment] 2015-10-12 15:20
Duplicate of https://github.com/zooniverse/Panoptes-Front-End/issues/957

**Closed by chrissnyder** 2015-10-12 15:20 UTC
