### ISSUE TITLE
Some videos are displayed as corrupted in Firefox/Safari browsers on Mac (Chimp&See)

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#5693] opened 2020-04-26 10:38 UTC
## Expected behavior
When you get a video to classify, you click on "play" button and you see what has been recorded (in this case an elephant).

## Current behavior
Some browsers (Safari) display the video as corrupted, see this screenshot:
![](https://i.imgur.com/z6X0k45.jpg)

while other browsers (Chrome) display it as a playable video.

Here is the link to the video from the screenshot: https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/subjects/35835085

## Steps to replicate
See the discussion here: https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/2269/1368621?comment=2227256&page=1

## Additional information
It seems to be affecting videos that have squarish format while others (rectangular) are played in the same browser without troubles. 

- **Operating system and browser:**
If I understand correctly, the problem occurred in Safari, Mac but while the same video worked fine in Chrome. (As a Chrome user, I haven't experienced the problem.) 
Edit: the screenshot comes from Firefox 75 on macOS (Sierra)
Edit2: also happens in Firefox on OS 10.13.6

**Comment by AnLand** [comment] 2020-04-26 10:42
This image above (from me) is not with Safari. Another user reported the same problem for Safari. The problem occurs for me with: Firefox 75 on macOS (Sierra).

**Comment by Orohena** [comment] 2020-04-26 10:54
Here is what I see, using Safari (on macOS High Sierra):

![Capture d’écran 2020-04-26 à 11 53 08](https://user-images.githubusercontent.com/53482862/80305436-8d238600-87b4-11ea-8942-89ee49f27e62.png)

**Comment by yshish** [comment] 2020-05-18 08:45
We get some additional information from another volunteer:
[This subject](https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/subjects/35705469) won't play for them although they can display the content frame-by-frame. Our moderator @AnLand can verify that with her system (Firefox) it happens too. She can 

>click the screenshots 2 to 16 and they will show an undisturbed image, while the video itself is pixelated (mostly green).

**Comment by srallen** [comment] 2020-06-15 20:17
Noting my response on Talk here as well: https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/2269/1368621?comment=2402016

**Comment by srallen** [comment] 2020-06-15 20:18
From analyzing one subject, it seems likely an encoding issue, but it unknown precisely what the problem is.

**Comment by srallen** [comment] 2020-06-19 14:36
Confirmed by analyzing a few videos plus one re-encoded one that the issue is the original encoding which we don't have any control over. These subjects will have to be re-encoded and there isn't anything we can do in the javascript code to get the videos with this issue to play correctly. Closing since there's not anything we can do on our end. Gave the recommendation on the associated Talk thread.

**Closed by srallen** 2020-06-19 14:36 UTC
