### ISSUE TITLE
SW-HSC: bug with Done being actioned when not clicked

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#4573] opened 2018-04-30 22:14 UTC
## Current behavior
From a citizen "On 2 occasions now it has told me that I've missed a lens before I've even clicked 'Done'. The first time I thought I must have done it in error but the second time? Maybe just me being trigger happy - but not sure!"

## Additional information

- **Operating system:**
- **Browser:**
Windows 10 
Firefox Quantum
59.02 (64-bit)

**Comment by eatyourgreens** [comment] 2018-05-02 13:44
This is a bug with feedback being triggered before the first task, rather than after. I haven't quite figured out the circumstances that trigger it, but it doesn't affect their ability to classify. After they dismiss the feedback box, they should be able to classify the subject, click Done and get the correct feedback for their classification.

**Comment by eatyourgreens** [comment] 2018-06-18 14:28
I think this is caused by `checkForFeedback` being called at the beginning of the first task in a workflow, rather than the end. It should have been fixed by #4697 and #4701.

**Closed by eatyourgreens** 2018-06-18 14:28 UTC
Labels: Project: feedback

**Comment by aprajita** [comment] 2018-06-18 15:18
thanks!
