### ISSUE TITLE
Error linking subjects 

### ISSUE THREAD

**Issue by melaniebeck** [zooniverse/Panoptes-Front-End#402] opened 2015-05-23 19:35 UTC
After uploading a subject set and associating it with a given workflow, I am having problems with classification. When I go to classify images, I can get through a half dozen before I get the "Error: No subjects available for workflow XXX". I try to refresh the page but can't get a new image to load. The only way to fix it is to sign out, go back to the Project, classify a few without signing in and then sign in again to repeat the process. 

After further testing I've determined that this happens when I receive a duplicate image -- one which I've already classified. The "already viewed" red banner in the upper left corner of the image doesn't appear until I've already classified the image and then the screen immediately goes to the "Error: No subjects" screen.

**Comment by edpaget** [comment] 2015-05-23 20:59
I think this is a duplicate of #393

**Comment by melaniebeck** [comment] 2015-05-23 21:38
I disagree. #393 references how long it takes for the images to load initially. My issue is that even once they HAVE loaded, they stop randomly and error out.

**Closed** 2015-05-28 08:05 UTC
Labels: duplicate
