### ISSUE TITLE
Background image zooms in on refresh

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#4099] opened 2017-10-17 16:25 UTC
On a PFE project if you go to any of the tabs that aren't the landing page and refresh the page, the background image is then zoomed-in when you go back to the landing page.

- **Operating system:** Ubuntu 
- **Browser:** Chrome

**Comment by eatyourgreens** [comment] 2017-10-17 16:32
Also reported as #3372, #2935 and #3662.

**Comment by mrniaboc** [comment] 2017-10-18 10:13
Sorry :(

**Comment by eatyourgreens** [comment] 2017-10-18 10:19
I'm going to leave this open as it might be a slightly different bug from the others. I think the underlying cause is that the background image is sized to fit whichever page you are on when the project first loads.

**Comment by eatyourgreens** [comment] 2017-10-18 10:35
OK, this is going to sound really dumb, but the reason for this bug appears to be that the homepage CSS only works if the URL has a`/` at the end.

**Comment by eatyourgreens** [comment] 2017-10-18 10:51
Actual cause of this bug is that the background image is applied to the entire project home page, when it should only be applied to the top section.

**Comment by eatyourgreens** [comment] 2017-10-18 11:55
Preferred fix: get rid of the [generic project background element](/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/project-page.cjsx#L114) and [associated javascript](/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/project-page.cjsx#L57-L64). Instead, apply the background specifically to the individual elements that use it.

**Comment by simoneduca** [comment] 2017-10-19 13:33
Which is the top section you mean @eatyourgreens?

**Comment by simoneduca** [comment] 2017-10-19 14:29
As far as I can see, when refresh happens on a page that isn't the home, [`@state.backgroundHeight`](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/project-page.cjsx#L109) becomes `null`. So when one goes back to the home page the background looks zoomed in.

**Comment by eatyourgreens** [comment] 2017-10-19 15:35
`state.backgroundHeight` is a hack to work around the background being set on the whole page. If the background is moved to the elements that it is supposed to fit, that hack isn't needed.

**Comment by simoneduca** [comment] 2017-10-19 15:53
I can see any suitable children element of [`project-page`](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/project-page.cjsx#L113) on this file.

**Comment by eatyourgreens** [comment] 2017-10-19 16:20
Why not just pass it down as a prop?

**Comment by eatyourgreens** [comment] 2017-10-20 10:25
Looking at this again, having the background behind the project navigation makes it more difficult.

**Comment by simoneduca** [comment] 2017-10-20 13:16
I can pass it as prop to `project-home.jsx` fine, but I don't think that the right place either.

**Comment by simoneduca** [comment] 2017-10-23 10:42
@eatyourgreens I'm stuck with this. The suggestion of passing the `background` prop to a child element (I've tried `project-home`) kind of works for the home page only.
The bug is resolved by displaying the background with a standard `img` element. However, a `z-index = 1` needs to be added to the footer to work on all pages. Another issue with this approach is that I don't know how to programmatically set the alt text to something useful.

**Comment by eatyourgreens** [comment] 2017-10-23 10:56
I was suggesting passing the background as a prop to all child pages, then adding the background to each individually.

**Comment by eatyourgreens** [comment] 2017-10-23 11:06
By the way, background images should be set using CSS `background`, so that they aren't read out by screen readers.

**Comment by simoneduca** [comment] 2017-10-23 11:11
As in `background: url(//whatever.org.uk)`?

**Comment by eatyourgreens** [comment] 2017-10-23 11:19
:+1:
https://developer.mozilla.org/en-US/docs/Web/CSS/background

**Comment by simoneduca** [comment] 2017-10-23 14:44
[This is where I got so far](https://github.com/zooniverse/Panoptes-Front-End/tree/fix-4099/app/pages/project). The `background` prop is passed down to all the children that require it. This, however, still doesn't fix the bug. The background image still zooms in/out across pages. I haven't use the `background` CSS property as suggested, because that would have overridden much of the original styling. I have already changed 6 files so far. An apparently simple bug is requiring a disproportionate amount of effort and it feels that is because of how the layout was originally designed (poorly).

**Comment by simoneduca** [comment] 2017-10-23 15:18
I see. So that means the styling of each element will also need to be changes to accommodate the styling of the background. I'll try that.

**Comment by eatyourgreens** [comment] 2017-10-23 15:24
Yeah, the current setup seems to use an absolutely positioned, empty div (which has a height of 0 by default.) Some CSS and JavaScript magic is then used to size that div to the appropriate height, which seems to be the cause of the odd behaviour that people have been reporting in the linked issues.

I thought a simpler approach would be to apply the background image directly to the content that it is supposed to appear behind, but I didn't realise that it appears behind the project navigation, which might complicate things.

**Comment by simoneduca** [comment] 2017-10-24 12:55
[This is what I got by including the project background on each project page that requires it](url). Note, while home, about, classify and talk all have their own page, classify doesn't for some reason. Instead it falls back to its parent `project-page`. So in order to give classify page a background, one needs to be assign to the parent page. Of course the result is that now all the other pages have two overlapping backgrounds.
Clearly I'm thinking about this wrong. It seems to me a rewrite of the project layout is needed to fix this bug. Which seems crazy at the same time because the bug isn't affecting the user hugely. it might also be I've been looking at it for too long, so I'm going to leave this for a bit. I'd be keen to hear other people's thought in the meantime.

**Comment by eatyourgreens** [comment] 2017-10-24 12:58
The classify page is in `/app/classify`.

**Comment by eatyourgreens** [comment] 2017-10-24 12:59
Sorry, it's actually in `/app/pages/project/classify.cjsx`, which then loads in the other page.

**Comment by simoneduca** [comment] 2017-10-24 13:00
Sorry I didn't mean classify, but collections. Edited.

**Comment by simoneduca** [comment] 2017-10-24 13:01
I also updated the link to seabirdwatch to see how messy this gets.

**Comment by eatyourgreens** [comment] 2017-10-24 13:04
Hmmm, yes. Also you haven't applied the project home page background to the top section of the page either. It's still being laid out behind the entire page.

**Comment by simoneduca** [comment] 2017-10-25 09:21
I've sadly run out of ideas for now. As mentioned before, navigation is in the way of getting the background to behave as expected. I wasn't able to find a way to solve that.

**Comment by simoneduca** [comment] 2017-10-30 13:16
Just a thought, I'm not convinced this deserves any time given [the planned redesign of the classifier](https://github.com/zooniverse/Panoptes-Front-End/issues/4068#issuecomment-332588942). Anyone thinks otherwise?

**Comment by srallen** [comment] 2017-10-30 14:50
This issue has to do with the project layout and its CSS, not the classifier page itself. We won't be touching the project layout with the classifier redesign.

**Comment by srallen** [comment] 2017-10-30 14:51
Just to clarify, I understand that the background placement for the eventual classifier page design is changing, but that's a long way off from the initial plans which is the classifier itself being rebuilt. I don't think this should be held off for that.

**Comment by chrislintott** [comment] 2017-10-31 13:35
Agreed with Sarah

**Comment by simoneduca** [comment] 2017-10-31 13:45
Sorry, I saw @srallen comment only now. Fine by me. I would still love to hear how to get round the problem of having the navbar in the way of the background, without changing the app basic layout.

**Comment by eatyourgreens** [comment] 2017-10-31 13:46
The new classifier uses the same layout as the project home page, in that there's a top section with the background image behind it. So this layout change is going to have to be made in order to implement the new classify page anyway.

**Comment by simoneduca** [comment] 2017-10-31 14:13
Sounds like a plan. I'll have a go.

**Comment by eatyourgreens** [comment] 2017-10-31 14:16
Maybe start by extracting the project navigation out into its own component. Would that help?

**Comment by simoneduca** [comment] 2017-10-31 14:17
Good suggestion, yes. Thanks.

**Closed** 2017-11-22 15:29 UTC
Labels: bug, help wanted
