### ISSUE TITLE
The main Talk page stopped displaying the most recent posts

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#1650] opened 2015-09-26 17:42 UTC
The main Talk page stopped displaying the most recent posts. For example the Zooniverse board shows post from 2 months ago, instead of 3 hours ago. It doesn't seem to be on a purpose to me.

https://lh3.googleusercontent.com/-sZGmlOaUqiw/VgbUnuQc37I/AAAAAAAAIf0/Q9D1QT5hkFM/s0-Ic42/ysh_2015-09-26.jpg

with browser console
https://lh3.googleusercontent.com/-kJgVcTaW7Kg/VgbXXMYxKnI/AAAAAAAAIgM/oavujUYRgFU/s0-Ic42/ysh_2015-09-26_19-32-18.jpg

Tested on Ubuntu Firefox (laptop) and Chrome on Yoga tablet, both the same results.

**Comment by mschwamb** [comment] 2015-09-26 19:47
@parrish this looks like the same thing that happened on Planet Four: Terrains talk a few weeks ago caused by a data migration I think you said. Ticket  #1528

**Comment by DarrenMcRoy** [comment] 2015-09-28 16:09
Not only that, posts are no longer displaying in the order of most recently commented.

![screen shot 2015-09-28 at 11 11 38 am](https://cloud.githubusercontent.com/assets/8987864/10141289/57c2edf2-65d1-11e5-8cdf-876924c10ca0.png)

I would call this a high-priority fix @aweiksnar @parrish

**Comment by parrish** [comment] 2015-09-28 16:37
Yeah, there's nothing actually broken, but it's a confusing result.

Right now discussions come back in order of most recently updated.  If somebody edits the discussion title, or one of their comments, it'll bump the discussion in the list.

I'll create a separate ticket for changing the ordering to last comment creation time.

**Comment by DarrenMcRoy** [comment] 2015-09-28 19:07
Um, now everything is TOTALLY messed up. Even the boards have started moving around. Discussions seem to be ordered completely at random now, and the "most recent" certainly isn't working.

What happened? :-(

**Comment by parrish** [comment] 2015-09-28 19:09
Data is currently migrating.  There are currently ~6,500 discussions left to update.  In the next hour or so, you'll see the correct order.

I'll just leave this open until then.

**Comment by parrish** [comment] 2015-09-28 20:25
This should be fixed now.

**Closed by parrish** 2015-09-28 20:25 UTC
Labels: talk
