### ISSUE TITLE
subject viewer now displaying really wide for all projects

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2329] opened 2016-03-21 12:02 UTC
I suspect this was introduced to fix some of the display issues, but I'm not a fan.

![screen shot 2016-03-21 at 11 58 05](https://cloud.githubusercontent.com/assets/6217406/13917990/45c468a0-ef5c-11e5-9930-2c24888bb11d.png)
![screen shot 2016-03-21 at 11 57 31](https://cloud.githubusercontent.com/assets/6217406/13917991/45c4c160-ef5c-11e5-8809-69465d8a10a3.png)
![screen shot 2016-03-21 at 11 59 25](https://cloud.githubusercontent.com/assets/6217406/13918047/9f7a9d88-ef5c-11e5-8ca0-49cbc3e61a57.png)

**Comment by alexbfree** [comment] 2016-03-21 12:31
tagging @srallen @eatyourgreens - i think all of us have looked at tickets in this area.

I would agree this is a bit unsightly - do we have any agreement on what the preferred alternative is? keep image in same positions as above but make the outsides of the image viewer transparent?

![screenshot 2016-03-21 12 28 33](https://cloud.githubusercontent.com/assets/1473244/13918656/a1d55560-ef60-11e5-996c-cbc918747fb0.png)

Just had a quick go at tweaking it do that in browser but that seems to have an issue with the image gettting repeated, so this may be a bit tricky to do... but even we fix that, the white outline box is still visible around the empty space. And the buttons are off to the right.
 Not sure what the correct solution is. Maybe the entire page should be centred to a fixed 990px or whatever, blog style...

It may be that the current implementation is the least worst option design wise.

**Comment by ggdhines** [comment] 2016-03-21 12:34
What were the original display issues that this fix was meant to address?

**Comment by alexbfree** [comment] 2016-03-21 12:56
@ggdhines not sure exactly when this was introduced, and whether it came in deliberately or by accident, there have been a few different issues changes in this area such as #2285 , #2305 , #2302.
My gut instinct is that given black has been explicitly assigned to the background that this was by design, so maybe @srallen or @eatyourgreens can comment?

**Comment by srallen** [comment] 2016-03-21 14:12
Flex is super buggy in IE11 and the most recent PR was to fix the subject viewer since it wasn't displaying at all in IE11. I'll take a look at it again to see what I can do, but may not be able to exactly get it as it was displaying before since we would want a working interface in IE11.

**Comment by ggdhines** [comment] 2016-03-22 14:25
I just realized that as things currently stand, this setup allows for people to have markings easily go outside of the image. In the past, such markings were possible but rare. Usually a problem with the interface (possibly when people use a tablet computer). I added in a check where I discard any markings which go outside the boundaries. If this set up stays in place for any reasonable length of time, I should probably change so that such markings are no longer discarded. Might have to do something like "trim" markings so that they lie within the image itself. Not completely trivial and I have enough other things to do - but do we have an ETA for a fix on this?

**Comment by camallen** [comment] 2016-03-22 14:26
@ggdhines @srallen has already issued a PR to fix it. might not work in 100% of cases though. https://github.com/zooniverse/Panoptes-Front-End/pull/2330

**Comment by eatyourgreens** [comment] 2016-03-22 14:28
@ggdhines I haven't been able to click outside of the image on the examples I've checked. You can drag marks outside of the image area, though, which is a known bug.

**Comment by ggdhines** [comment] 2016-03-22 14:36
@eatyourgreens - yeah that's what I was referring to. Didn't realize it could happen even without the black borders. Will have to look into that

**Comment by eatyourgreens** [comment] 2016-03-22 14:42
@ggdhines Here you go: #2125

**Closed** 2016-03-22 16:17 UTC
