### ISSUE TITLE
sub-tasks for markings is buggy

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes-Front-End#588] opened 2015-06-18 10:56 UTC
when "no sub-tasks  defined for tool" is shown I click on "add task" - the resulting window for subtask creation has a number of issues:
- the "add task" at the bottom of the windows should probably be "add another task" - I thought the "add task" would close the window and save what I had done
- if I create a second subtask, keep it blank, and then "click on remove task"  - that task will disappear but a new one will automatically reappear
- sometimes clicking on allow multiple clears the main text
- with one task sometimes clicking on "remove task" closes the task only for it reappear shortly after

**Comment by ggdhines** [comment] 2015-06-18 13:01
Just after you opened this menu if you enter text and then click on allow multiple, the text disappears

**Comment by ggdhines** [comment] 2015-06-18 13:03
clicking on the plus button to add another output option can clear text for previous output options

**Comment by ggdhines** [comment] 2015-06-18 13:05
sometimes clicking on the plus button will cause an output option to actually disappear

**Comment by chrissnyder** [comment] 2015-07-01 18:24
Pretty sure this was all caused by auto-save behavior, which is fixed as of https://github.com/zooniverse/Panoptes-Front-End/commit/3d0f270814744fa002f5f83f88b0382b397cd383

**Closed by chrissnyder** 2015-07-01 18:24 UTC
Labels: bug
