### ISSUE TITLE
Adding the To: to the header of direct message after their sent and showing in your mailbox

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#940] opened 2015-07-02 06:39 UTC
I wrote a private message to a volunteer and it's showing up in my inbox with saying I wrote it, but doesn't say who I sent it to, if I have multiple messages and the person hasn't replied yet you have no idea who you sent it to from what's displayed

Can a to: line be added to header to list the recipient of a post -

Not sure if that makes sense -  I mean adding a To field to get printed to this:

![screen shot 2015-07-02 at 2 37 51 pm](https://cloud.githubusercontent.com/assets/753325/8471171/1c5fb982-20c8-11e5-8157-3a08ee067220.png)

**Comment by aweiksnar** [comment] 2015-07-02 11:41
Duplicate of #738

**Closed by aweiksnar** 2015-07-02 11:41 UTC
