### ISSUE TITLE
'Done & Talk' Shaded but 'Done' not when nothing selected in classification interface

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4591] opened 2018-05-02 10:38 UTC
This might be a bug or not, but before classifying it looks like the classification interface is emphasizing 'Done' or 'Talk & Done'. 'Talk & Done' does become bright once an answer is selected

<img width="1054" alt="screen shot 2018-05-02 at 12 34 45 am" src="https://user-images.githubusercontent.com/753325/39519055-ef95d5f4-4da0-11e8-8865-f68bbe266b27.png">

It seems like the buttons should have the same behavior look. 

<img width="1023" alt="screen shot 2018-05-02 at 12 36 12 am" src="https://user-images.githubusercontent.com/753325/39519079-04148e62-4da1-11e8-8f56-a3ef5ac9ca8f.png">

Also you get the weird cross strike through if I mouse over done and not when I mouse over 'Talk & Done' when nothing is selected.

**Comment by srallen** [comment] 2018-05-02 14:15
I've already noted to review the disabled styles with @beckyrother in #4570.

**Comment by srallen** [comment] 2018-05-03 17:37
Done & Talk's disabled cursor is fixed. This is a duplicate of the issue I'm using to track doing an audit of the disabled styles in #4600

**Closed by srallen** 2018-05-03 17:37 UTC
Labels: facelift
