### ISSUE TITLE
Can't save changes to project

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#429] opened 2015-05-28 00:19 UTC
Any ideas? Possibly a back-end issue (@camallen @edpaget)

![screen shot 2015-05-27 at 19 14 11](https://cloud.githubusercontent.com/assets/6217406/7850216/a04bb6aa-04a4-11e5-9d99-482290742307.png)

**Comment by aliburchard** [comment] 2015-05-28 00:21
And this...
![screen shot 2015-05-27 at 19 20 42](https://cloud.githubusercontent.com/assets/6217406/7850291/8ac85b0c-04a5-11e5-9b93-ebf049c58920.png)

**Comment by vrooje** [comment] 2015-05-28 11:12
Usually I get the 401 after I've left a window up for a long time and then come back to it; if I reload it fixes things. I think it may be unrelated to the 403 error in Zooniverse/Panoptes-Front-End#409 but I'm not sure...

**Comment by chrissnyder** [comment] 2015-05-28 11:47
Session timeout after two hours. Possibly the cause?

**Comment by vrooje** [comment] 2015-05-28 12:07
Is there any way to put up a more helpful error message, or refresh the session in the background, or something similar?

**Comment by vrooje** [comment] 2015-05-28 12:07
PS - this is the same as #411, right?

**Comment by edpaget** [comment] 2015-05-28 14:03
@vrooje yes they are they same.

**Comment by chrissnyder** [comment] 2015-06-16 16:08
@vrooje @aliburchard This looks potentially outdated. Can you check if it works or not now and close if this is taken care of?

**Comment by chrissnyder** [comment] 2015-06-18 03:14
Definitely outdated after the auto-saving feature. Closing.

**Closed by chrissnyder** 2015-06-18 03:14 UTC
