### ISSUE TITLE
Add timestamps and sender names to inboxes/direct messaging

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#891] opened 2015-06-30 01:26 UTC
From the inbox view, it's impossible to see who a message is from. The only thing that appears is the subject line.

![screen shot 2015-06-29 at 8 24 17 pm](https://cloud.githubusercontent.com/assets/8987864/8422124/e19a675c-1e9c-11e5-981e-92ca2bd8040c.png)

Also, messages come without any timestamps or other information except the person's name; it can be important to know when they were sent!

**Comment by aweiksnar** [comment] 2015-06-30 01:37
@DarrenMcRoy please don't post private messages on github. I removed that screenshot from your comment.

**Comment by DarrenMcRoy** [comment] 2015-06-30 01:41
Right, good point; thank you.

**Comment by aweiksnar** [comment] 2015-06-30 15:33
Duplicate of #738

**Closed by aweiksnar** 2015-06-30 15:33 UTC
Labels: duplicate, talk
