### ISSUE TITLE
deleting a comment updates the "most recent" post on Talk front page

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#970] opened 2015-07-04 12:10 UTC
I deleted an old test post in a thread that hasn't been posted in for a week, and when I went back to the talk front page for GZ Bars, it looked as though that was the most updated thread:

![screen shot 2015-07-04 at 13 09 26](https://cloud.githubusercontent.com/assets/2357126/8507865/0409155e-224e-11e5-8f15-8836e9ed4048.jpg)

Post deletions should be excepted from displaying of updates.

**Comment by vrooje** [comment] 2015-07-04 12:11
Addendum: the thread also shows up at the top of the thread list on that board now.

**Comment by DarrenMcRoy** [comment] 2015-07-16 21:32
@aweiksnar Will this be fixed by any of the PRs you put in today related to "most recent posts?"

**Comment by aweiksnar** [comment] 2015-07-16 22:04
I believe so, since this is perhaps a duplicate of #873

**Comment by aweiksnar** [comment] 2015-07-20 15:44
Should be all set now via #1106

**Closed by aweiksnar** 2015-07-20 15:44 UTC
Labels: bug, talk
