### ISSUE TITLE
The "collect" and "metadata" icon/buttons are so similar I can't tell them apart

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1182] opened 2015-07-22 12:26 UTC
![screen shot 2015-07-22 at 13 21 29](https://cloud.githubusercontent.com/assets/2357126/8825133/9cc0329e-3074-11e5-9a5c-928596b1df40.jpg)

I keep clicking the wrong one, and I've been using this interface for a while so I don't think it's going to go away and I definitely think new people are going to have issues.

Maybe the collect icon could be some sort of loot-bag icon, like I used to see in old video games? e.g. 

![I don't know why this is so bloody huge](http://www.clker.com/cliparts/U/a/v/n/h/w/bag-hi.png "Except, y'know, not 2342341 pixels wide")

**Comment by edpaget** [comment] 2015-07-22 12:29
Maybe they should just be text? Wrt #651

**Comment by vrooje** [comment] 2015-07-22 12:31
Cool, that too.

**Comment by chrissnyder** [comment] 2015-07-22 13:04
I really want to use that loot bag image somewhere.

**Comment by chrissnyder** [comment] 2015-07-22 20:21
Duplicate of https://github.com/zooniverse/Panoptes-Front-End/issues/651

**Comment by chrissnyder** [comment] 2015-07-22 20:22
On second thought, not quite. Re-opening as an issue of "the buttons below a subject need some work".

**Comment by chrissnyder** [comment] 2015-10-12 15:00
Changed at some point.

**Closed by chrissnyder** 2015-10-12 15:00 UTC
