### ISSUE TITLE
Phantom back button w/ experimental 'shortcut' tool 

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3171] opened 2016-11-01 01:19 UTC
## Expected behavior
If there's only one task, there shouldn't be a grayed out 'back' button on the classification interface, next to done. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Currently there's a grayed out 'back' button next to 'done' in the classification interface for a 'single' task workflow that includes the shortcut option. 

See https://www.zooniverse.org/lab/2416/workflow/1687

If instead I make a single task workflow that just has the marking tool, there's no grayed out 'back' button. 

## Additional information

- **Operating system:**
mac osx 
- **Browser:**
chrome

<img width="1047" alt="screen shot 2016-10-31 at 8 18 45 pm" src="https://cloud.githubusercontent.com/assets/4975655/19876772/401aef0e-9fa7-11e6-8c2f-54a166949d37.png">

**Comment by eatyourgreens** [comment] 2016-11-01 11:28
Duplicate of #287

**Comment by eatyourgreens** [comment] 2016-11-01 11:30
Also see #2189

**Comment by trouille** [comment] 2016-11-01 14:33
I think this is new/different from the issues above. A single task workflow that doesn't include the shortcut now looks like this (with no grayed out 'Back' button):

<img width="1230" alt="screen shot 2016-11-01 at 9 32 38 am" src="https://cloud.githubusercontent.com/assets/4975655/19893161/27958024-a016-11e6-8825-ee0391dd2aa5.png">


While a single task workflow that does include the shortcut does have the grayed out back button.

**Comment by wgranger** [comment] 2016-11-01 15:15
We are currently showing the back button if there is more than one task for any workflow (regardless if it is the first question or not). Technically, shortcut/nothingHere is considered a task, which is why the back button appears. I'll see if I can get a quick fix up.

**Comment by trouille** [comment] 2016-11-01 15:20
Oh, I see. Thanks for the explanation. 

Is there a reason that I may be overlooking that we should keep the back button in this case (when there's only one task + shortcut)? I don't think so, but I may not be thinking about a scenario where this would apply.

**Comment by wgranger** [comment] 2016-11-01 15:22
I can't think of one. The shortcut should act as a hidden task that only steps in when needed, so it makes sense to hide the back button in this instance.

**Closed** 2016-11-09 17:09 UTC
Labels: bug
