### ISSUE TITLE
PFE image selector/uploader breaks when uploading fails

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#4077] opened 2017-10-04 11:04 UTC
## Expected behavior
Handling situation where image can't be uploaded, e.g. too big, etc.

## Current behavior
PFE image selector/uploader will render with a URL that points to a file that doesn’t exist on S3, giving a zero-height image in the project editor

## Steps to replicate
https://www.zooniverse.org/talk/17/448971?comment=749011&page=1
## Additional information
N/A

**Comment by eatyourgreens** [comment] 2017-10-04 12:58
#952 mentions an upcoming delete button and better feedback for image uploads, but I guess those never happened.

**Comment by srallen** [comment] 2017-10-04 14:23
Hey, so some components for this are actually copied into the Zooniverse-React-Components repo. There may be some improvements done to it already for the pfe-lab and if this specifically hasn't been address, I'd prefer the fixes go there because the long term plan is to add ZRC as a dependency to PFE and import the shared components from there. 

I haven't done that yet since it was in early development with pfe-lab, but after the next two PRs merged into it, I'm going to publish to NPM and likely open a PR to add it to PFE and start replacing the imports for the shared components.

**Comment by simoneduca** [comment] 2017-10-05 09:17
I like that idea @srallen . So, just checking if I got it right: if any changes should be made to address this bug, they should be made on the Zooniverse-React-Components repo, probably the `image-selector`. Correct?

**Comment by srallen** [comment] 2017-10-05 14:35
We shouldn't have duplicate versions of the same components around. I haven't imported ZRC yet to PFE because it was under a lot of development initially for pfe-lab. Now it's getting more stable and more projects are starting to rely on it, so I'm planning on publishing to NPM for the next version release. So I think the bug fix so go to ZRC only and plan on adding this as a dependency to PFE.

Depending on what the issue is, the bug fixes may be for some of the child components, which are also in the repository. 

If I were to do this, I'd pull down ZRC, npm link it to PFE to work with to see if the bug is still present in the version of it that's in that repository. If it isn't, then we can wait for the new version and add as a dependency.

If the bug is still present, then fix it and open a PR for ZRC. Then later, when the next version is released, we can add it as a dependency to PFE.

**Comment by simoneduca** [comment] 2017-10-05 14:52
Sounds good, thanks for clarifying.

**Comment by eatyourgreens** [comment] 2017-10-09 11:20
Just to clarify, the bug here is that the [`img` element](/zooniverse/Panoptes-Front-End/blob/master/app/components/image-selector.cjsx#L37-L41) renders with zero height if its source URL points to a file that doesn't exist. The fix is probably to make sure that there's a minimum height on that element, so that it is always clickable.

**Comment by simoneduca** [comment] 2017-10-09 11:34
PR to address that is here https://github.com/zooniverse/Panoptes-Front-End/pull/4085
@srallen the fix didn't seem to require the ZRC.

**Comment by eatyourgreens** [comment] 2017-10-09 12:07
#4085 doesn't change the height of the image. Does that change fix the bug?

**Comment by simoneduca** [comment] 2017-10-09 12:56
It does, i.e. you can click the area and upload another image.

**Closed** 2017-10-09 12:58 UTC
Labels: bug

**Comment by eatyourgreens** [comment] 2017-10-09 13:00
Excellent! 👍 

This was only a small CSS fix, but @srallen is right that we should be careful not to put a lot of work into these old components since we're developing new versions in Zooniverse-React-Components.
