### ISSUE TITLE
Thread summaries on board don't display latest timestamp

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#976] opened 2015-07-04 21:55 UTC
When you're viewing the contents of a board each thread summary only shows who started it and when, without info on the latest post. This makes it impossible to see which threads have been updated since your last visit, especially sticky threads. I've had reports from the GZ Bars moderators that it's making the "Notes" board with post-classification subjects extremely difficult to keep an eye on -- and this board should be the heart of Talk, so I'm worried about this.

![screen shot 2015-07-04 at 22 54 21](https://cloud.githubusercontent.com/assets/2357126/8509518/b68f802c-229f-11e5-8248-d09d191fe54e.jpg)

I think it would be most useful if the thread summaries were:

[thumbnails of linked images, if any] [Post title]
Started by [avatar] [user]; [if necessary:] latest post by [avatar] [user]
[first X characters of the latest post] 

Also, it would be kind of cool to show the mini-avatars of anyone who's posted on the thread, maybe on the same line as the post title and right-justified, Discourse-like.

**Comment by DarrenMcRoy** [comment] 2015-07-04 21:59
Critically important, but a duplicate of #874.

**Comment by vrooje** [comment] 2015-07-04 22:25
ah, right, I thought it had been posted before but I was searching for "thread" and "board" so I missed it.

**Closed** 2015-07-16 17:04 UTC
Labels: talk
