### ISSUE TITLE
Annotations disappear from view in final step of workflow

### ISSUE THREAD

**Issue by tedcheese** [zooniverse/Panoptes-Front-End#1529] opened 2015-09-04 02:07 UTC
At the final step of the Whales as Individuals workflow I'm usually shown the image with my annotations. Those annotations are not showing up on the images, have not been showing up for a few days. Actual data is coming through in classification exports, so it is getting recorded but not displayed

<img width="1192" alt="screen shot 2015-09-04 at 4 55 45 am" src="https://cloud.githubusercontent.com/assets/7146233/9675117/2eb4ff08-52c2-11e5-9bea-3ad6dcdec116.png">

**Comment by vrooje** [comment] 2015-09-07 12:23
I've just tried this on GZ Bar Lengths and, likewise, on the summary page any markings I've made on the subject don't show. I can see them fine when I'm actually on the marking task, though -- it's just the post-classification summary for me.

**Comment by tedcheese** [comment] 2015-09-07 13:46
@vrooje That's exactly my experience. Misery (well not really but...) loves company :)

**Comment by Jim-Salmons** [comment] 2015-09-08 16:17
Confirmed for the FactMiners project under development. As I am new to the platform/community, I don't know the proper terminologies, etc. but I think of this page as a "review/confirm-before-submission" page and by showing the annotations we mean the boxes not being rendered on the image though coming through on the 'summary column' and in the data export.

BTW, to start providing better issue reports I have discovered and used the Windows-based StepShot to quickly and easily generate this ['illustrated issue report' PDF] (https://www.dropbox.com/s/ioxhy97zw63le7z/Classification_Boxes_Not_Displaying.pdf?dl=0).

![image](https://cloud.githubusercontent.com/assets/546022/9740489/a2599c1a-561a-11e5-84bc-291d53f4c7d7.png)

[StepShot](http://stepstoreproduce.net/) is the 'pro'/commercial version of this freebie, http://StepsToReproduce.net. While the websites are short on identification of the developer, it is this brilliant Ukrainian test automation expert, [Oleksandr Reminnyi (LinkedIn profile)](https://www.linkedin.com/pub/oleksandr-reminnyi/21/b2/5b7).

The ONLY thing that would make me love this awesome 'helper tool' even more would be for its export feature set to include generation of 'pasteable Markdown' with image-url rewriting as part of export template configuration!

**Comment by vrooje** [comment] 2015-09-08 17:12
Hmm, just to clarify though -- this page we're talking about isn't confirm-before-submission; by the time a user gets to the summary page the submission has already occurred (it happens when the button to advance to the next task says "Done" instead of "Next"). @tedcheese has verified that the data is still all being submitted; it's just not being displayed after the submission on the front end.

**Comment by brian-c** [comment] 2015-09-09 10:32
Yep I know what's going on here, just a display bug. There's also some debate about whether this step is going to continue to exist at all.

**Comment by Jim-Salmons** [comment] 2015-09-10 17:35
If this page continues to exist... which I think is a good thing if, like an e-Commerce check-out, you can tweak your contribution before submission, that is a good thing UX-wise. I would recommend two presentation-visual tweaks however:

1. Put the Back and Next/Done buttons at BOTH the top and bottom of the textual confirmation column. This way, on lower resolution devices or on submissions that are textually long, the User will at least see the Back/Next/Done buttons and not have to think to scroll down to find them.

2. Related to item one, truncate with ellipses on the instructional text included in the default view. Since virtually all listed items include a More button to see data submission detail, the default could be to truncate the instructional text to 20-40 characters with the full text shown if/when the User clicks More. ALSO, render the markdown of the feedback text on this confirmation page (along with truncating).

While it is recommended that folks make instructions/descriptions and titles as short as possible, this should not be a requirement to get a decent looking project presentation.

**Comment by Jim-Salmons** [comment] 2015-09-14 18:29
It sure would be great if display of draw boxes on the summary/submission page could be restored soon... as in time for this Thursday's Global Collaboration Day for educators.

FactMiners.org and The Softalk Apple Project will be hosting a "TOC-Mapping Drop-by Party" for Global Collaboration Day, this Thursday, Sept. 17th. (GCD info: http://www.globalcollaborationday.org/) Here's a YouTube promo video: https://youtu.be/8R9J0fIhx9k.

If there is any way we can help document and fix this problem. I don't yet have a local development instance running as I am on Windows and haven't found info on setting up a Windows developer's config.

**Comment by Jim-Salmons** [comment] 2015-09-14 18:33
QUICK QUESTION: On this "review/thanks-for-classification" page, is this a "receipt"/thank-you? That is, has the data already been submitted and will be included in the next data dump even if the person where to close the browser or switch off the computer? OR, does the classifying User have to press the **Next** button to "submit" the classification to have it included in the classification data?

**Comment by Jim-Salmons** [comment] 2015-09-14 18:45
While we're at the point of restoring the box/annotation rendering on this review/summary/thank-you page, here area couple usability tweaking I would suggest:

* Duplicate the **Talk** and **Next** buttons at the top of the "text summary column" such that a set of these buttons will be visible in the default rendered display regardless of the length of the generated text summary column. This is a copy/paste tweak and will avoid the "What do I do now?" situation if a User is shown a summary page with the "workflow stepper" button far down the page and not visible.

* Truncate the instructional text field included in text summary column. While the best practice recommends ruthlessly short instructional text, there should not be a usability bias in the event that following this guideline is not practical.

* Optional but helpful: Render the markdown in the instructional text included in the summary text column. (Together with truncating this text, rendering formatting would greatly improve the look and readability of this review page.)

**Comment by vrooje** [comment] 2015-09-14 19:45
It is a "receipt", not a "just-to-confirm" page. The main purpose of the page (aside from the summary/receipt) is to give the volunteer the option of going to Talk or loading another subject for classification.

**Comment by Jim-Salmons** [comment] 2015-09-14 20:40
Ah, that's kind of what I thought. I will adjust our prompts accordingly.

In this case, the easiest minimally-acceptable tweak while fixing the box/annotation-rendering issue might be to simply duplicate the **Talk** and **Next** buttons at the top of the "submission summary" text column. Don't sweat the truncation and markdown rendering.

As long as Classifiers can see and quickly decide to talk/next, that is the main thing UX-wise.

It might be good, too, to update the message generated at the top of the page from **"Thanks! Your classification:"** (which is a bit ambiguous) to something like **"Data submitted. Thank you! Your submitted classification data:"**

And add a minimal standard prompt along the lines of _"Press **Talk** to comment in the Forums on this classification, or **Next** to continue classifying."_ Since we cannot add text to this generated page, some prompt to encourage/suggest **Talk/Next** would be helpful.

As soon as we've nailed our project in advance of hosting a drop-by party for Global Collaboration Day this Thursday, I'll try to dig into the code and at least make specific suggestions if not submit a patch. But again, I don't yet have a development box set up locally. So I'm not sure how effective I'll be in the short-run.

**Comment by vrooje** [comment] 2015-09-14 20:58
I'm concerned about putting in a Talk/Next button pair above the summary box. I think in most cases if such a thing is needed, it means the text for the questions in the workflow is too long, i.e. this is a project design issue, not a site design issue. 

In the screen shots above, for example, it seems like the task would be less intimidating to the new user and less redundant to the experienced user if the last 2 paragraphs of text were in the help box instead of the workflow main text. You could replace it with a much shorter sentence reminding users that pressing the help button will bring up more information.

**Comment by vrooje** [comment] 2015-09-14 21:01
Also, this seems to have wandered from the original topic -- I'd suggest starting a new issue if you want to request other changes or report other bugs. Thanks :)

**Comment by chrissnyder** [comment] 2015-09-18 13:04
@brian-c Was the display bug taken care of and can we close this?

**Comment by brian-c** [comment] 2015-09-18 15:01
Nope, I think we need to rework this step. I'd rather leave it blank for now than have people think they can go back and edit things.

**Comment by chrissnyder** [comment] 2015-10-12 13:30
Closing for cleanliness. I've noted the issue and we'll reference back when we go a broader rework of the summary step.

**Closed by chrissnyder** 2015-10-12 13:30 UTC
