### ISSUE TITLE
Talk thread that's blank but appears to not be blank

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4660] opened 2018-05-30 16:23 UTC
Going to this thread
https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/210/630302?page=1&scrollToLastComment=true

<img width="750" alt="screen shot 2018-05-30 at 6 22 22 am" src="https://user-images.githubusercontent.com/753325/40733666-ea2001ca-63d1-11e8-9995-400a9c6ca4c9.png">

I don't see anything visible but  it looked like there is content according to the preview:

<img width="721" alt="screen shot 2018-05-30 at 6 15 52 am" src="https://user-images.githubusercontent.com/753325/40733308-fcef854c-63d0-11e8-8c8d-dd13d9b48bbf.png">

**Comment by marten** [comment] 2018-05-30 16:26
Thanks. One of @mcbouslog's recent merges broke something. He's on the case to put in a fix.

**Comment by mschwamb** [comment] 2018-05-30 16:28
If it helps, this thread shows https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/8/645355?page=1&scrollToLastComment=true with no problem. I haven't checked Comet Hunters in about 2 weeks.

**Comment by mcbouslog** [comment] 2018-05-30 17:06
Sorry about that. The issue was caused by PRs merged within the last few hours, and it looks like #4661 fixed the issue so discussions properly load, but let us know if not. Thanks,

**Closed by mcbouslog** 2018-05-30 17:06 UTC
