### ISSUE TITLE
Recent development: the landing page "About" introduction box has become a floating object

### ISSUE THREAD

**Issue by khufkens** [zooniverse/Panoptes-Front-End#1120] opened 2015-07-17 20:29 UTC
The introduction box on the bottom of a project has become a floating object on screens with a lot of vertical resolution. It does not align with the bottom of the browser window any more, creating a floating box although the links to zooniverse projects etc. still remain attached to the bottom of the page.

Validated on both Chromium and Firefox. I guess someone touched an alignment variable, should be an easy fix.

**Comment by mschwamb** [comment] 2015-07-18 00:33
Are you on windows? On Mac Firefox  39.0  I don't see any change in the About box. It's at the bottom of the screen attached to the Zooniverse box. 

![screen shot 2015-07-18 at 8 32 57 am](https://cloud.githubusercontent.com/assets/753325/8759500/a6851f2e-2d27-11e5-908a-1fb4f690d010.png)


Does yours look different from this? Maybe it's a windows issue?

**Comment by khufkens** [comment] 2015-07-18 01:12
Can't reproduce it on OSX. My system at work is a Linux box (both Chromium and FF were affected, not sure if they use the same engine?).

**Comment by chrissnyder** [comment] 2015-07-18 16:36
@khufkens Could you add "bumishness" as a collaborator on your project so I can take a look?

**Comment by khufkens** [comment] 2015-07-18 16:53
Can't add you as you don't show up (I have @bumish and @bumishness1-5), this is actually another bug I should report. Not all user handles carried over between zooniverse systems it seems. Normally you should be able to see it without login in. 

Best way to test it is to have a monitor in portrait mode or artificially lengthen your browser window past the physical extent of the desktop. This way the behaviour is shown on OSX but it snaps back into place after a while (browser window resizes). I don't think Linux enforces the resizing or allows control of the window size (by either the OS or the web page content). An example of the behaviour described is shown below, with no zooniverse footer attached to the introduction text bar (the background is showing).

Instead of enforcing window resizing behaviour the zooniverse footer should move up. It's a recent development as I only noticed it this week.

![screen shot 2015-07-18 at 12 50 37](https://cloud.githubusercontent.com/assets/1354258/8762590/b7da2d40-2d4b-11e5-96b1-7c66e7d15bc3.png)

**Comment by mschwamb** [comment] 2015-07-18 22:54
If it helps - My search returns back but Chris is listed last, I had to scroll to the bottom of the list. Since the list sorted displayname. If you search Chris Snyder instead it will be pop up as the first result so you can add him.

**Comment by khufkens** [comment] 2015-07-20 18:56
Ok, I'm on my linux machine and this is what is shown on my portrait mode screen (lots of vertical pixels). This is an extreme user case but will arise as well on high pixel density displays I guess.
![introduction_issue](https://cloud.githubusercontent.com/assets/1354258/8784341/8307ec1a-2eef-11e5-96fc-550b0c943f23.png)

**Comment by chrissnyder** [comment] 2015-10-13 14:41
Closing as "working as intended".

That said, we are aiming to dramatically improve the general design of the project landing page in the near future. Expect changes in this area.

**Closed by chrissnyder** 2015-10-13 14:41 UTC

**Comment by khufkens** [comment] 2015-10-13 14:45
Could there be an email to project managers when you roll out the new GUI? -It's kind of a major change.

**Comment by chrissnyder** [comment] 2015-10-13 14:47
Absolutely. We'll likely send around a URL with the proposed changes implemented when we do.

**Comment by khufkens** [comment] 2015-10-13 14:47
Wonderful! - thanks
